### ISSUE TITLE
Fix min version check in build script

### ISSUE THREAD

**Issue by tapkain** [EOSIO/eos#10243]
Hi, I was building eosio on macOS BigSur 11.1 but the check for min version inside eosio_build_darwin.sh is 14, therefore it does not allow to build.

**Comment by spoonincode** [comment]
The script was fixed in 2.1. We didn't backport the fix to 2.0.x because we usually don't add platform support in patch releases and fixing the script for macOS 11 was kind of a form of platform support.

It's unfortunate the script has that defect. As far as I know 2.0.x passes all tests on macOS 11.

@aclark-b1 unless you're interested in reentertaining backporting of this fix seems like we can close

**Comment by spoonincode** [comment]
With 2.1 released and this fixed, might as well close
