### ISSUE TITLE
Non-producing Node Sync Problem

### ISSUE THREAD

**Issue by joslee7410** [EOSIO/eos#10939]
Good day guys, i'm here for asking about the block sync problem.

I'm facing this problem around 6 hours ago.

```
local_height:219611239
remote_height:219611346
```
and currently

```
local_height:219619411
remote_height:219661989
```
Having different:42578 blocks

I'm running with v2.0.13. All the log seems normal.

Somebody please help me. Thank you.

**Comment by heifner** [comment]
The EOS mainnet was very busy today. Over 1.3 million new accounts were created. My guess is your node is just not able to keep up with the load today. It has slowed down now so maybe you will be able to catch back up. If not you may need faster hardware. Alternatively it could be the nodeos you are syncing from are too overloaded because of the same issue.
