### ISSUE TITLE
push_transaction无法发送交易

### ISSUE THREAD

**Issue by arayalways** [EOSIO/eos#11075]
自建的EOS节点
 "server_version_string": "v2.1.0"；
正确构造的交易，push transaction 超时无法发送成功,或者直接没有响应，但是get info这些接口是OK的。

同样的交易，使用https://api.eosflare.io这个api就能成功发送
 "server_version_string": "v2.0.13",

这个问题最近才出现的，之前都是没问题。

**Comment by matthewdarwin** [comment]
Since last week there are periods of time where someone (or more than one person) is abusing the EOS Mainnet by sending a lot of transactions that ended up failing. This generates load on many nodes as they try to process those transactions. This can be mitigated via configuration options.

1) If you don't need to process p2p transactions on your nodeos (only process incoming API transactions), then you can turn off p2p transactions all together. (you will still receive blocks)

   p2p-accept-transactions = false

2) If that doesn't work for you, then auto-block "spammy" accounts

   disable-subjective-billing = false

**Comment by arayalways** [comment]
Thank you. I will try
