### ISSUE TITLE
Exchange wallet issue

### ISSUE THREAD

**Issue by Shinbum** [EOSIO/eos#1474]
Hello,
About 2 weeks ago, I transferred EOS tokens to Yobit exchange,,,,, and the wallet is on MAINTENANCE.

It was embarassing, I should have checked the wallet statement, it's also my mistake.
I sent email to Yobit support and no reply did not come.
And I also sent email to EOS, they said I'd better to contact Yobit.

Anybody had same experience like this? Do I need to be patient until they make it?
Do I give up the tokens?

Or if anyone can help this issue?

My mom will be angry if she knows about this, because I borrowed money to buy the token from her.

**Comment by rebelyante** [comment]
same here, I have sent my eos tokens a week ago, no support, wallet on maintenance, 0 on the wallet, nothing. tokens gone.

**Comment by koosa** [comment]
This also happened to me 1 week ago i didnt notice wallet was offline and i trasnsfered 804 eos tokens. yobit tolled me the wallet for this cryptocurrency is temporally not working. i thought i had to wait for it do be resolved and from yobits end. just today i checked the eos wallet status and it showed its status as online so i wrote ticket requesting my coins as they werent in my walllet, they replied with this
----------------------------------------------------
Deposit\Withdrawal coin will be available after you upgrade the source code of the wallet. Unfortunately the developers are in no hurry to send you updates
- therefore, in order to avoid the loss of users, the network is not available.
If you have updated the source code of the coin, send us (https://yobit.net/en/maintenance_request/ Free)and we will promptly correct the problem on the coin.
Thank you for contacted the support.
........................................................................
i know this is just utter bullshit i know, we are the ones left with this problem .. i trasnfered over 10k and and not prepared to loose it.. 
does anyone know where we how we can get this sorce code for eos updated on yobits wallet????

**Comment by rebelyante** [comment]
Hi, unfortunately I have received the same answer couple of times, and still waiting to update it.

**Comment by koosa** [comment]
we need a developer that can do the update because waiting for yobit to do the update isnt going to help.. im willing to pay someone that can do this upgrade

**Comment by rebelyante** [comment]
I just checked the wallet. My EOS finally got there!  I'm out this exchange forever. Hope you have yours too.

**Comment by Shinbum** [comment]
I also received to my wallet.
Thanks to you letting me know about the update!
