### ISSUE TITLE
Getting error while calling transaction method of eoslib/transaction.hpp 

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1590]
i make a contract and try to call "transaction( transaction&& trx )" method but it is calling this method "transaction( const transaction& ) = delete;" 
![image](https://user-images.githubusercontent.com/36531568/37153803-e8ac7634-2303-11e8-84de-b55b1e6a1e77.png)

helloworld.cpp
![image](https://user-images.githubusercontent.com/36531568/37153834-fbc9714a-2303-11e8-8845-a5250fb51bc4.png)

helloworld.hpp
![image](https://user-images.githubusercontent.com/36531568/37153885-242fd296-2304-11e8-8887-3c31b11785e9.png)

Output after running the code
![image](https://user-images.githubusercontent.com/36531568/37153937-5ad87e60-2304-11e8-924a-6e94017bd226.png)

Please check the code and let me know where is the error

**Comment by andriantolie** [comment]
According to the given definition, you can't use copy constructor there, instead, you will need to use move constructor. Try to move the Hello:trx isntead of copying it, i.e. `eosio::print(eosio::transaction(std::move(Hello::trx)));`

I'm going to close this issue because the above transaction smart contract api is outdated, if you encounter problem with new api, please open a new ticket. Thanks!
