### ISSUE TITLE
DAWN-660 ⁃ Avoid using Boost MultiIndex in our multi_index implementation to reduce WASM code sizes

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1592]
Boost MultiIndex adds a lot of code bloat to the compiled WASM contract code, in particular because of the way `multi_index` uses Boost MultiIndex, a copy of the MultiIndex template exists for each primary table used by the contract.

Using a single Boost MultiIndex for all possible object types is one possible solution. It would require the indices to become composite indices that are first sorted on the table name. But still requires all of the overhead of Boost MultiIndex (although only one copy of it).

Since the number of objects (per table) kept in the cache during the execution of a contract is expected to be small, it will likely be sufficient to not even bother keeping the `item`s in sorted order and to just do a linear search for the right `item` as necessary. This avoids using Boost MultiIndex entirely in the WASM contract code, which should considerably reduce code size.

**Comment by arhag** [comment]
There were two approaches selected to redesigning `multi_index` in order to reduce compiled WASM code sizes.
The first was to simply remove the Boost MultiIndex cache from the `multi_index` implementation and do a linear search instead.
The second approach went further and used inheritance and virtual dispatch to reduce code duplication as much as possible.

The way contract developers used `multi_index` did not change going from the "original" design of `multi_index` (the one in commit 4be244f47f22fcaae75254d08247e17ce54e862e) to the "remove-boost" design (the one in commit b1bd7566069843b302df5a1612bf4fb50d535678). 
However the change to the "inheritance" design (the one in commit 53350a479a9aed339130dfd3ed22489f544dcf84) required contract developers to have their structs that were used as the table objects inherit from a `table_row` class and to override the virtual method `primary_key()`.

The "inheritance" was not even completed at the time of posting this comment. While it compiles (albeit with `has no out-of-line virtual method definitions` warnings), the tests fail.
Nevertheless, the broken implementation was enough to get very good estimates of the compiled WASM code that would be generated with a properly functioning version of the "inheritance" redesign of `multi_index`. 
And as will be seen in the table below, the benefits of any additional code size reduction likely does not justify the performance cost of additional indirection, not to mention the further development cost of debugging the problems with the "inheritance" design at this time. 

The table below shows how the code size of four different contracts (currency, exchange, identity, test_api_multi_index) changed as a result of these two redesigns of `multi_index`.
It looks at the .wast (human readable WebAssembly), .wasm (compiled WebAssembly code), and .wasm.gz (gzipped .wasm) file sizes under the three different designs: "original" (commit 53350a4), "remove-boost" (commit b1bd756), and "inheritance" (commit 4be244f4).

|                      | original |       |          |   | remove-boost |       |          |                                       |   | inheritance |       |          |                                       |
|----------------------|----------|-------|----------|---|--------------|-------|----------|---------------------------------------|---|-------------|-------|----------|---------------------------------------|
| Contracts            | .wast    | .wasm | .wasm.gz |   | .wast        | .wasm | .wasm.gz | % reduction of .wasm.gz from original |   | .wast       | .wasm | .wasm.gz | % reduction of .wasm.gz from original |
| currency             | 175 KB   | 26 KB | 7.0 KB   |   | 115 KB       | 17 KB | 5.6 KB   | 20%                                   |   | 101 KB      | 16 KB | 5.7 KB   | 19%                                   |
| exchange             | 453 KB   | 63 KB | 12 KB    |   | 280 KB       | 43 KB | 9.5 KB   | 21%                                   |   | 256 KB      | 43 KB | 9.7 KB   | 19%                                   |
| identity             | 392 KB   | 51 KB | 13 KB    |   | 248 KB       | 32 KB | 10 KB    | 23%                                   |   | 210 KB      | 29 KB | 10 KB    | 23%                                   |
| test_api_multi_index | 576 KB   | 72 KB | 14 KB    |   | 465 KB       | 56 KB | 12 KB    | 14%                                   |   | 377 KB      | 46 KB | 11 KB    | 21%                                   |

The currency contract uses two tables (each with no secondary indices). 
The exchange contract uses one table with no secondary index and two very similar additional tables that each have (essentially the same) three secondary indices.
The identity contract uses three tables (each with no secondary indices) and one additional table that has one secondary index.

There is no improvement in the compressed wasm sizes going from the "remove-boost" design to the "inheritance" design; in fact, the .wasm.gz sizes actually increase a little going from "remove-boost" to "inheritance" for the currency and exchange contracts.
While the "inheritance" design tries to avoid code duplication, it does add some overhead and it cannot avoid having copies of some parts of the methods (emplace, modify, erase) that require knowing the specific template arguments provided to `multi_index`.
As the code sizes for the three contracts show, in practice the net effect at this attempt by the "inheritance" redesign to reduce code duplication may not actually help.

One contract where the "inheritance" redesign does make a difference over simply removing Boost MultiIndex is in the test_api_multi_index contract.
Granted, this contract (which is a collection of unit tests on `multi_index`) is likely not typical of most contracts that will actually be deployed on a live network.
It consists of three different table types (each with one unique secondary index), and the first two of these table types are instantiated twice under different table names (something that should be very unusual in practice).

Looking at the "% reduction of .wasm.gz from original" columns, it seems clear that majority of the code size reductions come from simply removing Boost MultiIndex.
So, we will not bother with the "inheritance" redesign and just go forward with removing the Boost MultiIndex cache.
However, some small changes were still needed beyond commit b1bd756. These small changes (up to commit 69d3905) did not make much of a difference to code sizes (in fact in some cases slightly reduced them). 
Further changes to `multi_index` that are not part of this pull request are already known to be necessary to fix a new bug (GH #1644 or DAWN-673) found in `multi_index` (it isn't expected for those changes to dramatically change the WASM code sizes).

**Comment by SheldonHH** [comment]
![image](https://user-images.githubusercontent.com/16319106/37696462-9c12b8c0-2d11-11e8-8411-0a6bbaf24b48.png)

```
 "tables": [{
      "name": "account",
      "type": "account",
      "index_type": "i64",
      "key_names" : ["currency"],
      "key_types" : ["uint64"]
    },{
      "name": "stat",
      "type": "currency_stats",
      "index_type": "i64",
      "key_names" : ["currency"],
      "key_types" : ["uint64"]
    }
  ]
```

**Comment by andriantolie** [comment]
Related PR is https://github.com/EOSIO/eos/pull/1645

**Comment by andriantolie** [comment]
ATC:
- Ensure all tests/chain_tests for test_multi_index still pass after the change applied

**Comment by andriantolie** [comment]
ATC passes
