### ISSUE TITLE
DAWN-631 ⁃ Code Upgrades: Should TX’s specify the code version they are expecting, or is “versioning” a wasm concern

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1761]
Code Upgrades: Should TX’s specify the code version they are expecting, or is “versioning” a wasm concern

Need Dan's input.

ATC:  I can issue transactions before a code upgrade and those transactions will be automatically rejected because of the change (instead of applied to unintended code)

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

This should be changed to adding a check to the chain code which rejects transactions whos TAPOS is "before" the block where the code it is accessing has changed.  Developers can then TAPOS their transactions to the block or after and this can signal acceptibility.

**Comment by blockone-syncclient** [comment]
➤ Jimmy Calfee commented:

Since a transaction header already references a block height (and hash), it might be feasible to reject any ABI message call where the ABI or code was updated after the block referenced in the transaction's header.  That still leaves it to the API caller to manually check the ABI version, but it at least closes the window for an unexpected change to happen.

**Comment by blockone-syncclient** [comment]
➤ Jimmy Calfee commented:

Related:  https://github.com/EOSIO/eosjs/issues/11

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner Is this being considered at all?  I have not heard anything about plans on how to handle versions of the C API.  If I don't hear back on this I will presume this is OBE.

**Comment by arhag** [comment]
> @wanderingbort @heifner Is this being considered at all? I have not heard anything about plans on how to handle versions of the C API. If I don't hear back on this I will presume this is OBE.

This will not be going into the first consensus protocol upgrade. By this I mean the change to the chain logic to reject transactions that include actions of contracts that have changed since the TaPoS-referenced block.

Also I think we need to reconsider whether we even want this feature. After all, why should a simple bug-fix that doesn't change contract functionality or the ABI cause all in-flight transactions to be rejected?

Furthermore, with the proposed consensus protocol upgrade discussed in #6168, it would be possible to build an asserter contract which verifies that none of the assumptions about code versions have changed since the transaction was made assuming the transaction included an assertion action that included that information (or a commitment to that information via a single hash). This method of protecting transactions against updated contracts also works well with the `eosio.msig` contract. The asserter contract can also commit to particular ABIs as well since that information is also retrievable for accounts that have `setabi` after deployment of the system contract from eosio.contracts v1.3.0 (EOSIO/eosio.contracts#48).

**Comment by brianjohnson5972** [comment]
@wanderingbort So @arhag seems to say this should close, I'll give you a chance to respond, if I don't hear back I'm going to mark this as no longer desired.

**Comment by brianjohnson5972** [comment]
Based on @arhag 's input above, closing.
