### ISSUE TITLE
Managing permissions with eosc

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#185]

**Comment by nathanhourt** [comment]
Add support to eosc for creating, updating, linking, removing, etc. permissions. Make it nice and usable.

**Comment by pmesnier** [comment]
Hi Nathan,
As I added the stdin input feature for streaming / console support, I had a couple of extra thoughts. Add single pre/post commands for setting and clearing processing configuration, then for whatever script is being streamed in, define some level of client side meta-programming such as variable substitution and looping. In fact you'll see I left in some code that would collect streamed commands into a batch script and then repeatedly send the batch some number of times. I decided not to pursue this at the time since I was straying away from my intended goal of making eosc a vector for scripts to use to stream commands into eosd. However with your task here, I wanted to share.

**Comment by nathanhourt** [comment]
I think I'm missing the necessary context to understand your comment, Phil... Right now, I know very little about what eosc does, and even less about how it works. :)

I don't know what you mean by scripts streaming in. I was under the impression that eosc was not supposed to have any interesting scripting logic like variable substitution and looping, as the shell supports those things and eosc should be designed to work with the shell doing those things...

**Comment by pmesnier** [comment]
I added stream input as a way to avoid the overhead of process start when running multi-line  scripts through eosc. Allowing for uses such as:
multicommandgen | eosc - | downstreamproccess
or 
eosc - < batchfile
Then I threw in an isatty check and in that case eosc - spits out an "enter command" prompt.

**Comment by bytemaster** [comment]
eosc set account permission authority ${ACCOUNT} ${PERMISSION_NAME} ${AUTH} ?{PARENT_PERMISSION_NAME}
eosc set action permission ${ACCOUNT} ${CODE} ?{ACTION}  ${PERMISSION_NAME}
${AUTH} is a JSON blob containing an Authority structure.

if ${PERMISSION_NAME} is null then it should delete the link.
if ${PARENT_PERMISSION_NAME} is unspecified then it defaults to 'active'

**Comment by wanderingbort** [comment]
closing this as it is being rolled in to #402
