### ISSUE TITLE
Review action merkle tree for inclusion/exclusion of new features.

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1908]
The original construction of what is "provable" using a block's action merkle root likely has insufficient representation of newer features.  For instance, it does _not_ include the ability to prove that an action:

 - [ ] issued a deferred transaction 
 - [ ] canceled a deferred transaction
 - [ ] consumed a deterministic quantity of the account(s) resources

There may be other features which have been added to the chain between 2.x and our current release feature set which should also be included. 

The criteria for inclusion would be features which have significantly more value when there is chain-level support for concise proofs of the features' existence and/or artifacts on chain state. 

While this will not increase block size, it _will_ increase the burden on indexers/explorers that store the data necessary to generate these proofs.

**Comment by arhag** [comment]
Different types of actions have access to different state.

A context-free action should only have access to the following state:

- the unsigned transaction (which includes the transaction header and the context-aware and context-free actions explicitly included in the transaction)
- context-free data included in the `packed_transaction`

A context-aware action should have access (perhaps only indirectly and with limits) to the following state:

- the unsigned transaction;
- the implicit transaction (which is like the original transaction except also including the sequence of all context-free and context-aware actions that were dispatched by context-aware actions that executed up to the point just before the current context-aware action began executing);
- the account and permission state (`account_object`, `permission_object`, `permission_link_object`) which is needed for checking authorizations;
- some state in `global_property_object` (for `get_active_producers`) and some state in `dynamic_global_property_object` (for `now()`);
- EOSIO Persistent State (or at least some subset of it determined by CodeScopes) via the `database_api` as well as `resource_limits_manager` (for updating RAM usage due to modifications to EOSIO Persistent State);
- and, privileged accounts also have access to additional state in `global_property_object` (for setting and getting blockchain parameters) and again to `resource_limits_manager` (for getting and setting resource limits)

This is worth keeping in mind when we think about what a full node needs to be able to prove to a light (or rather medium) client that only wants to apply the actions that are needed to derive the subset of the Persistent State that they care about.

For example, the leaves of the action Merkle tree (`action_receipt`) need to at least commit to the implicit transaction that would have existed just prior to executing the action (if it commits to the whole implicit transaction, then it needs to also commit to the metadata needed for the proof verifier to know how to restrict the whole implicit transaction to just the subset that the action should have access to when executing).

We also need to review how the other parts of state (outside of EOSIO Persistent State) that a context-aware action could depend on can be given to a light/medium client with proof. For example, now that a context-aware action can explicitly call `check_authorization` and get a boolean return value, and given the fact that the permission tree / permission link graph can be modified with each action, how does that change what we need to commit to in the `action_receipt` to allow a full node to prove everything needed to a light/medium client so that the client can securely recover just the subset of the EOSIO Persistent State they care about without having to apply unnecessary actions?
