### ISSUE TITLE
eosio_exit and instruction counting

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1937]
# Description

Currently we inject our internal intrinsic `checktime` with instruction counts of the instructions we guarantee will execute on `block` and `loop` instructions in WASM.  However, if inside either of those logical collections of instructions there is a call to `eosio_exit` then we will over-count instructions.  

This is technically true for other modes of termination as well, such as asserts and violating the invariants of any intrinsic call (perhaps, requiring an authority that was not provided).

There are two main issues: 
 - User generated transactions which call `eosio_exit` do not see the intent of that call reflected in the instruction count that depletes their temporary allotted CPU bandwidth.  This, in turn, means that using `eosio_exit` is purely for _subjective_ gains and does affect our _objective_ measure of runtime.  
 - Deferred Transactions _can_ fail and there are 2 additional statuses under which a deferred transaction can be included in a block: soft-failure and hard-failure:
    - The accumulated runtime cost of a soft-failure should be the cost of running the transaction _to failure_ plus the cost of running the error handler (if present) _to success_
    - The accumulated runtime cost of a hard-failure should be the cost of running the transaction _to failure_ plus the cost of running the error handler _to failure_.  

# Concessions 

In the case where a contract terminates prior to completion we may want to distinguish explicit termination (calls to eosio_exit, eosio_assert, require_auth, etc) from implicit termination (memory access violations, integer divide by zero, etc).  

Explicit termination should be reflected in the instruction count accurately as it present an active choice by the contract author to "optimize" runtime.  For example, by moving a call to `eosio_assert` that often fails, earlier in the execution path.

Implicit termination can probably count to the end of the logical block as it represents an error and not a choice of the contract author.  Not to mention, most instructions/calls have some error conditions on bad data and tracking all possible errors would be too intense.

**Comment by spoonincode** [comment]
> However, if inside either of those logical collections of instructions there is a call to eosio_exit then we will over-count instructions.

That's putting it nicely. We pretty much over count everything and everywhere because branches of any sort (`br`, `br_if`, `if`, `else`, `call`, `return`, etc) don't modify the instruction count for the branch taken. Instruction counting correctness & improvement possibly deserves its own issue at this point. In general the changes I'd like to see are:

1. Take branches in to account and always update the instruction count based on it
2. Move instruction count completely inside of wasm; this should make the increment/decrement of instruction count very cheap for a quality JIT/AOT implementation
3. Consider only actually evaluating instruction overage at `loop` and start-of-function sites. Doing it at `block` just doesn't make any sense to me -- you can never branch _to_ a block, just to the _end_ of it. Often times WASM branching ends up looking like this
```
  (block $label$0
   (block $label$1
    (block $label$2
     (block $label$3
      (block $label$4
       (block $label$5
        (block $label$6
         (block $label$7
          (block $label$8
           (br_if $label$8
```
(taken from exchange contract) and it's insanely futile to checktime or do a instruction counting compare 9 times in a row for these constructs.

Another non-consensus improvement I would consider is to only do the checktime check after some multiple of x-number of instructions have been retired. That's a (relatively) expensive check at the moment and it is quite wasteful to constantly hit it if someone has the equivalent of
```
for(int i = 0; i < n; i++) {
   dosomething()
}
```
