### ISSUE TITLE
STAT-168 ⁃ Automated ABI generation for smart contract

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#197]
Currently developers need to manually write the ABI (JSON) for their application, this is error prone when all the data should be available through the contract code.

Acceptance test criteria for the ABI Generator:
https://github.com/elmato/abi-generator-atc

**Comment by bytemaster** [comment]
What is the design for this?

**Comment by elmato** [comment]
The idea is to have a set of annotations in the form of comments that adds specific information for the ABI generation. Like **action**, **table**, **typedef** (?)

Then a Clang plugin will collect all the types (structs, unions, classes) declared in the multiple contract files and only export the **action**s, **table**s and their corresponding base types to the _action_, _table_, and _structs_ section respectively.

https://clang.llvm.org/docs/ClangPlugins.html

TBD:
- What to do when we find a type with multiple inheritance (warn about it, cancel ABI json generation)
- What to do with templated type names (export mangled names?)

eg:
```
//@eos action
struct Transfer {
   AccountName       from;
   AccountName       to;
   CurrencyTokens    quantity;
};
```
```
//@eos table  
struct Account {
   Account( CurrencyTokens b = CurrencyTokens() ):balance(b){}
   const uint64_t     key = N(account);
   CurrencyTokens     balance;
   bool  isEmpty()const  { return balance.quantity == 0; }
};
```

**Comment by bytemaster** [comment]
I think I would use Doxygen to parse the comments rather than clang.

**Comment by bytemaster** [comment]
This is a really big task that I think probably needs to be factored out into first supporting strings and vectors in eoslib with manual abi generation.  Currently eoslib only supports fixed sized messages and that limits many use cases.

**Comment by elmato** [comment]
Working on this before doing a PR:

- A way to disable automatic generation (in case the contract developer for some reason wants to generate it manually or the plugin can't figure it out how to handle the types properly).
 Currently there is a **#pragma no_abi** directive that disable the generation, but i want to add also a command line parameter if possible eg: **make NOAUTOABI=1**

- Allow for simple table annotations by deeply inspecting the type (DRY).
  `//@abi table [name] [index_type] [key1,key2,..,keyN]`
  If name is not provided -> use the name of the struct
  If index_type not provided -> guess it (+key names/types)  from the first fields of the struct
  etc..

- Test corner cases

**Comment by elmato** [comment]
Updating on what we have so far in the ABI generator.

### Specifying an action 
```
//@abi context action
struct ActionName {
  ...
};
```
You can also specify multiple actions that uses the same interface (same struct)
```
//@abi context action action1 action2
struct ActionName {
  ...
};
```
### Specifying a table
```
//@abi context table
struct Table {
  uint64_t key;
};
```
The generator (using the size of the types of the first fields of the table) will try to guess the index type. In case of ambiguity (see below) the contract developer must specify the index type.
```
//@abi context table i64
struct Table {
  uint64_t  key;
  Name     name;
  uint64_t  age;
};
```
_a struct with 3 uint64_t can be both i64 or i64i64i64_

The 'context' parameter was added to the annotations to know what needs to be exported.

Otherwise when building a contract that includes header files from another contract the generator will export everything. Using the namespace in which types are defined (as the context) will have the limitation of only have automatic ABI generation for C++ contracts and no for plain "C" contracts.

### Disabling automatic ABI generation

Contract developers can use **#pragma no_abi** in any source or header file or set the **NOABI** environment variable to **1** to disable automatic ABI generation for the entire project.

> [ 97%] Generating ABI currency.abi
> ABI Generation disabled (#pragma no_abi)
> [100%] Generating WAST currency.wast
> 

Besides that we did a refactor of the implementation.

Since the clang::ASTConsumer is created and destroyed for every source file (.cpp), we moved all the logic to the AbiGenerator class to preserve our state. This class gets instantiated using a singleton and in the destructor we write the ABI file if necessary (we didn't find a better way to know when the plugin finished).

We start the ABI generation process after the textual assembly step has been completed, to be sure that the project was first compiled and linked successfully.

There still work to be done (variable size types, arrays, etc), but the generator is in a "good enough" state to be used for the kind of types we are using now.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

NOTE: new library required:

  * sudo apt-get install libclang-4.0-dev

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

I did a make install and installed eos. However, after that running this command throws up the following error:

MacBook01:case1 pravin$ eoscpp -g case1.abi types.hpp
/usr/local/bin/eoscpp: line 58: realpath: command not found
Generated case1.abi ...

**Comment by blockone-syncclient** [comment]
➤ Matias Romeo commented:

It seems that 'realpath' command is not included in OSX. 
I replaced its functionality in eoscpp using just dirname+pwd.
https://github.com/EOSIO/eos/pull/769

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~pravin.bezwada] [~matias.romeo] Is this ready to test again?

**Comment by elmato** [comment]
Yes, ready to test again.

**Comment by SheldonHH** [comment]
Related to #1933 and #1663
