### ISSUE TITLE
Address resource usage authorization design.

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2034]
# Description

There have been 2.5 unsatisfactory iterations of resource usage authorization:
 1. Over-Billing - Resources are authorized and billed from declared actors on transactions, where each actor is billed the full extent
    1. the list of actors can contain duplicates if the actors are mentioned multiple times
    1. the list of actors is unique so that each actor is billed exactly once
  1. Declared Billing - Resources are authorized and billed to the _first_ declared actor

## The problems with Over-Billing 

The major issue is that this bills too much for all but the most trivial transaction ( one with a single authorization on a single action ). 

## The problems with Declared billing

The major issue with Declared billing is that by using the permission system to authorize at _any_ level with an account you do not control (for instance, setting a permission that allows an employee to post to social media on your behalf).  Gives that account (and any account they in turn delegate to) the ability to completely use your resources.   This is mad obvious with a transaction with a lead action which is benign (post to social media) followed by N actions which are resource hogs and do not refer to the original authorizer. 

# What to do?

This issue is to investigate alternatives to the two solutions tried so far that do not require aggressive over-billing and do not dis-incentivize the use of the permission system as it is designed.

**Comment by wanderingbort** [comment]
This will address some parts left un-done or moved to RC2 in #1979

**Comment by arhag** [comment]
The latest design decision regarding who to bill is as follows:

- CPU and network bandwidth are billed to each account in the set of accounts that authorized any action within the transaction. The current behavior of the code does not reflect this because of a bug which issue #2193 will address.
- RAM usage for storing a delayed transaction is billed to the first authorizer of the transaction (that is currently implemented). If users collaborating on transaction signing wish to bill someone in particular, they have the following options:
  * If the actor that wants to be billed for the RAM is in the set of authorizers for the first action in the transaction, they that sequence of authorizers can be reordered so that the RAM payer is the first one for that action.
  * If the actor that wants to be billed for the RAM is not in the set of authorizers for the first action in the transaction, they can either be added as an unnecessary first authorizer of the first action of the transaction or a no-op action can be added as the first action of the transaction and the RAM payer added as the sole authorizer of that no-op action.
  * If this delayed transaction is proposed using the multisig contract then the RAM payer for delayed transactions is always the executor of the proposed transaction. So in this case, the designated RAM payer would wait until all the necessary approvals are met for the proposed transaction before triggering the execution.

**Comment by andriantolie** [comment]
@wanderingbort @arhag is this done?
