### ISSUE TITLE
Error 3010003: Contract Table Query Exception

### ISSUE THREAD

**Issue by Pritam231** [EOSIO/eos#2054]
Most likely, the given table doesnt' exist in the blockchain.
Error Details:
Table account is not specified in the ABI
Request Path: localhost:8888/v1/chain/get_table_rows
Request Post Data: {"json":true,"code":"currency","scope":"currency","table":"account","table_key":"","lower_bound":"","upper_bound":"","limit":10}
Can anybody suggest the solution for it

**Comment by zshchou** [comment]
cleos get table contract scope table

**Comment by andriantolie** [comment]
Currency contract is no longer available so this issue is no longer relevant. I'm going to close this issue. 

However, if you want to use the above command on eosio.token, it should be the following:
{"json":true,"code":"eosio.token","scope":"<THE_ACCOUNT_NAME_OF_THE_ACCOUNT_YOU_WANT_TO_CHECK","table":"accounts","table_key":"","lower_bound":"","upper_bound":"","limit":10}
