### ISSUE TITLE
Issue multiple token exceptions

### ISSUE THREAD

**Issue by xnfy520** [EOSIO/eos#2058]
`cleos get currency balance eosio.token eosio.token`
_19990 ADA
1000 EOS_

`cleos get currency balance eosio.token eosio.token ADA`
_19990 ADA_

`cleos get currency balance eosio.token eosio.token EOS`
_19990 ADA_

**Comment by andriantolie** [comment]
What exceptions did you get?

**Comment by halsaphi** [comment]
We will close this issue since we have not received feedback.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organised, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
