### ISSUE TITLE
DAWN-496 ⁃ Initialize Genesis from ERC-20 Snapshot

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#214]
1. Add snapshot script to /eos/programs/snapshot
2. Provide instructions on using this script in /eos/progams/snapshot
3. Create a program to convert snapshot.csv into snapshot.json file that can be used with eosd to start a properly configured blockchain
4. Check in an snapshot.json file that is ready to go for the test network

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10122&#x2F;snapshot+%28period+118%29.json">snapshot (period 118).json</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10121&#x2F;snapshot+118_csv.zip">snapshot 118_csv.zip</a>

**Comment by dskvr** [comment]
We will need to determine a the final block for the testnet snapshot.

**Comment by nathanhourt** [comment]
The EOS ERC-20 freezes all balances at the end of the sale, does it not? So knowing the exact ethereum block wouldn't matter, you just need some block after the sale ends?

**Comment by dskvr** [comment]
@nathanhourt Yes and no. The Token is frozen at end of crowdsale, but registration transactions could still happen, causing mismatch between different snapshots. 

Alice wants to verify the snapshot and runs generator. Meanwhile, Roger sends a Registration TX. Bob wants to verify the snapshot and runs generator. Alive and Bob compare snapshots but they are different.

However, this is mostly in regards to testnet screenshot. Ending block is important because no tokens are frozen, if multiple people generated a snapshot, they would all have different versions. That's not easy to verify.

**Comment by rangershi** [comment]
grate

**Comment by dskvr** [comment]
What is the deadline for snapshot.json?

**Comment by dskvr** [comment]
[ ] Add snapshot script to /eos/programs/snapshot
[ ] Provide instructions on using this script in /eos/progams/snapshot
[ ] Create a program to convert snapshot.csv into snapshot.json file that can be used with eosd to start a properly configured blockchain
[ ] Check in an snapshot.json file that is ready to go for the test network

**Comment by dskvr** [comment]
Snapshot specifications have changed since this issue was initially opened. Unregistered addresses will now be included in snapshot through a fallback strategy which is currently being tested. This change of strategy has a completely different approach from initial requirements, as it requires full supply monitoring. 

- [x] Wallet Balance Calculations
- [x] Reclaim transactions sent to Crowdsale/Token contract by mistake
- [x] Key Validation
- [x] Registration Validation
- [x] Database Structure
- [x] Crowdsale Utilities
- [x] Network-Wide EOS Token Supply Monitoring
- [ ] Contract State Synchronization (transfers, buys, claims, registrations)
- [ ] Wallet State DB Synchronization/Queueing [was complete, now needs to be refactored]
- [ ] Realtime Polling [was complete, now needs to be refactored]
- [ ] Daily Snapshots (end of period)

**Comment by dskvr** [comment]
The majority of business logic is complete but still working through some bugs. Aiming to have high priority tasks listed should be complete by Tuesday

**Comment by dskvr** [comment]
Almost all the numbers are aligned now. Once everything is aligned like it was in previous iteration, I'll be able to complete the remaining tasks.

**Comment by dskvr** [comment]
Need to refactor instantiation to accomodate various modes.

**Comment by jcalfee** [comment]
Refactoring is good..  I'm happy to review your work when it is ready.  Thanks for the updates..

**Comment by dskvr** [comment]
Reminder: There is almost nothing in common to pre-release code in 'genesis'. Completely different strategy due to spec pivots and web3 1.0 beta stability.

**Comment by dskvr** [comment]
Made use of the space from this and took a turn to simplify as much as possible. Did even more testing on EOS registration fallback, and still looking promising.

**Comment by dskvr** [comment]
Missed an update yesterday. Taking a break from aligning numbers and working on collecting as many public keys as possible and optimizing registration fallback method. Have an issue with not aggregating all buys for the last period of any given snapshot, have a feeling it's related to block number vs transaction timestamp. Jumping back the final stretch, which is closing the gap on a 0.014% margin of error when snapshotting up to period 109

**Comment by dskvr** [comment]
Got snapshot within appropriate margin of error on Sunday (worked through the weekend). Was going to write up docs and push yesterday, but ended up feeling some burnout so took a break.

**Comment by dskvr** [comment]
Moved the process for ethereum public key scanning into it's own step so testing supply validation can take 20 minutes vs 4 hours. Making the snapshot configurable so there's a map for docker config and so it can be configured without docker. Added a tools directory for some web tools, started on tool to check snapshot balance associated an ETH address/EOS public key.

**Comment by dskvr** [comment]
Been moving logic around for configurability, public key discovery is a wider scope now and wrapping up the various tests.

**Comment by dskvr** [comment]
Sped up public key discovery by ~20x, working on refactoring logging and making the script more portable. Spent a little time on some frontend interfaces. Starting on Readme.

**Comment by dskvr** [comment]
Margin of error is now consistently `-0.00000001%`. Modified some existing tests, added some new ones, removed others. Finishing readme. Started modifying existing genesis block generator.

**Comment by dskvr** [comment]
This was pushed to EOSIO/genesis repo yesterday. Less a `genesis.json` file.

**Comment by dskvr** [comment]
Accidentally closed. Committing a `genesis.json` file requires knowing which period the snapshot should be generated for.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Thomas Added:

EOS community is asking what Easter Eggs the genesis block will contain. Satoshi included some in the Bitcoin genesis block, apparently (e.g. some headlines from newspapers). Should we? And if so, what?

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~Sean.Mitchell] Is this still open?

**Comment by gleehokie** [comment]
OBE
