### ISSUE TITLE
Error 3030011: duplicate transaction

### ISSUE THREAD

**Issue by sailei1** [EOSIO/eos#2210]
<img width="578" alt="2018-04-07 21 41 21" src="https://user-images.githubusercontent.com/1625409/38455571-8d8621e0-3aac-11e8-992c-111e11c70c7e.png">

**Comment by andriantolie** [comment]
@sailei1 Can you try with the latest code again?

**Comment by andriantolie** [comment]
Duplicate transaction happened because you have sent an exactly same transaction previously. If you use cleos, usually the transaction will be different because of different expiry time/ ref block num, but this can happen if you sent the same transactions quickly. For the first error message, I just checked it and it doesn't appear anymore in the latest code, so I'm closing this issue
