### ISSUE TITLE
Memory leak via net_plugin's big_msg_manager::bcast_transaction

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#2211]
Long running soak tests of transmitting lots of transactions can cause significant memory bloat. I was at nearly 7GB of resident memory on one nodeos vs 130MB on the other after 24hr of soak testing.

I've traced this down to allocations occurring in netplugin's big_msg_manager::bcast_transaction when inserting in to the trx_state multi index container. My first suspect is that trx_state isn't getting pruned correctly but there could be other issues.

ATC
Run a multi-node testnet for a while. Provide a steady stream of transactions and verify that the memory size of the nodeos processes stay consistent. There will be some growth due to the blockchain, but there shouldn't be any case where one node becomes massively larger than any other.

Also, transactions that are not accepted by the chain should not be forwarded.

**Comment by pmesnier** [comment]
There are 2 tables involved, one for blocks and one for transactions. both are intended to give this node a sense of what its peers know about. This is done primarily to be a little smarter about  what data to send to whom. But there is no exit criteria for such data. 

Since the idea is to ensure that data isn't forwarded redundantly, we should hold on to the entries for a bit. So is it sufficient to add a fixed expiration time on the cached transaction or block status info? Or perhaps we can assume that once a transaction is in an irreversible block it will no longer be passed around and thus is safe to remove? Same with the block statuses as well. Once they are irreversible I suppose we can assume they won't be broadcast any more.

**Comment by spoonincode** [comment]
I thought expire_txns() was already intended to do that?

**Comment by pmesnier** [comment]
that is certainly a good place to do the evaluation for each of the connections. For the time being, expire_txns() only purges the local transactions cache. The locally cached transactions all have an expiration time that dictates when they should be eliminated. The cache of peer transaction indicators does not have expiration. at least as of now.

**Comment by spoonincode** [comment]
Yes, I see now, trx_state and blk_state. I was focused too much on local_txns.

**Comment by andriantolie** [comment]
The second ATC passes (transactions that are not accepted by the chain should not be forwarded).
Currently sending a stream of steady "create account" transaction (roughly 40 txs per block) to a multi-node testnet (in AWS)

**Comment by andriantolie** [comment]
After it's been running for roughly a day and creating almost 2 million accounts, I can see that both node memory usage are roughly the same (between 2.3-2.4GB).

ATC passes
