### ISSUE TITLE
cleos native contract support

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2257]
All native system contract features (e.g. actions) should have native cleos support:
- create producer
- vote for producer
- stake/unstake
- etc

**Comment by taokayan** [comment]
blocked by pull request #2543

**Comment by andriantolie** [comment]
I checked the subcommand one by one and here is the result
- newaccount - Pass
- regproducer - Pass
- unregprod - Pass
- voteproducer - Pass
- listproducers - Pass
- delegatebw - Pass
- undelegatebw - Pass
- buyram - Pass
- sellram - Pass
- claimrewards - Pass
- regproxy - Fail
- unregproxy - Fail
- canceldelay - Fail

**Comment by andriantolie** [comment]
For regproxy, the thrown error message is
<img width="1215" alt="screen shot 2018-05-16 at 3 20 04 pm" src="https://user-images.githubusercontent.com/6541441/40102976-884aa666-591e-11e8-9b40-4cde8f0c7667.png">
I think it's because we miss the "isproxy" field

For unregproxy, the thrown error message is
<img width="1156" alt="screen shot 2018-05-16 at 3 20 18 pm" src="https://user-images.githubusercontent.com/6541441/40102996-9ad11860-591e-11e8-8e43-34fdda1bfa2d.png">
I think it's because we don't have unregproxy action inside eosio.system.abi

For canceldelay, the thrown error message is
<img width="1241" alt="screen shot 2018-05-16 at 3 31 03 pm" src="https://user-images.githubusercontent.com/6541441/40103025-b5bf7ce8-591e-11e8-9791-84ef53d8d3ef.png">
I think it's because cleos specifies the argument as `cancelling_auth` while eosio_contract_abi.cpp specifies the abi as `canceling_auth` (single l) instead

**Comment by andriantolie** [comment]
Update:

After I pull the latest one, seems regproducer is also throwing an error
<img width="1240" alt="screen shot 2018-05-16 at 4 50 58 pm" src="https://user-images.githubusercontent.com/6541441/40106839-6914ea4e-5929-11e8-853f-2161d929826e.png">
I think it's because there is a new field added to regproducer in eosio.system.abi

**Comment by andriantolie** [comment]
PR #3202 added to fix the above errors. I'm going to remove the needs testing - fail label

**Comment by andriantolie** [comment]
PR 3202 is fixed and tested
