### ISSUE TITLE
Docker error: Missing Chain API Plugin

### ISSUE THREAD

**Issue by wanf425** [EOSIO/eos#2323]
step1. I pull eos/eosio image from Docker Hub at 2018/4/11 23:03

> docker pull eosio/eos

the tag is latest.

step2. I use 'docker-compose up' to run containers docker_nodeosd_1 & docker_keosd_1
step3. When I excute 

>cleos set contract eosio ../contracts/eosio.bios -p eosio

in docker_keosd_1，there is an an Error:

> Reading WAST...
Assembling WASM...
Publishing contract...
Error 3130001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration!
Error Details:
Chain API plugin is not enabled

**Comment by kaidiren** [comment]
see you config.ini and make sure that `plugin = eosio::chain_api_plugin` is exists and not be commented

**Comment by mjoecohen** [comment]
I had the same error but after noticing a bug in the documentation at https://github.com/EOSIO/eos/wiki/Local-Environment#3-docker **/opt/eos/bin/data-dir** should be **/opt/eosio/bin/data-dir** this problem came down to incorrectly mounted volumes.

Beyond that my docker compose env seems okay as running
`$ docker-compose exec keosd /opt/eosio/bin/cleos -H nodeosd get info` 
gives me back 
`
{
  "server_version": "269f084e",
  "head_block_num": 2998,
  "last_irreversible_block_num": 2997,
  "head_block_id": "00000bb6d2709d48b6ec88266842632146754d22ed1fe8a559d62d5576c91efe",
  "head_block_time": "2018-04-23T11:05:05",
  "head_block_producer": "eosio"
}`

However running the contract command
`docker-compose exec keosd /opt/eosio/bin/cleos -H nodeosd set contract exchange /contracts/exchange/exchange.wast /contracts/exchange/exchange.abi`
now gives me:
`Reading WAST/WASM from /contracts/exchange/exchange.abi...
Assembling WASM...
235004ms thread-0   main.cpp:1435                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('
{
^`

??
