### ISSUE TITLE
dawn-v3.0.0 rpc push_transaction error "itr != structs.end(): Unknown struct "

### ISSUE THREAD

**Issue by Hipponensis** [EOSIO/eos#2345]
First request:
`
curl http://10.10.0.137:8888/v1/chain/push_transaction -X POST -d '{"compression":"none","transaction":{"ref_block_num":551502,"ref_block_prefix":1081446710,"expiration":"2018-04-12T07:25:36","scope":["currency","inita"],"actions":[{"code":"currency","name":"currency","account":"currency","type":"transfer","recipients":["currency","inita"],"authorization":[{"actor":"currency","permission":"active"}],"data":"0000001e4d75af460000000000ea305520a1070000000000044355520000000006746573746572"}],"authorizations":[]},"signatures":["EOSKBBBCqgGYh6WVRb86uapTw9xysYDGFnkQiUnWsF5DCKd1euZxah5faZMzrod9Bftg8jwjRHQyw1k8oXPY7YNyQkiLQ2viv"]}'
`

First response:
`
{
    "code": 500, 
    "message": "Internal Service Error", 
    "error": {
        "code": 10, 
        "name": "assert_exception", 
        "what": "Assert Exception", 
        "details": [
            {
                "message": "itr != structs.end(): Unknown struct ", 
                "file": "abi_serializer.cpp", 
                "line_number": 184, 
                "method": "get_struct"
            }, 
            {
                "message": "Failed to serialize type", 
                "file": "abi_serializer.hpp", 
                "line_number": 439, 
                "method": "to_variant"
            }
        ]
    }
}
`

THEN, Second same request, the response was:
`
{
    "code": 409, 
    "message": "Conflict", 
    "error": {
        "code": 3030011, 
        "name": "tx_duplicate", 
        "what": "duplicate transaction", 
        "details": [
            {
                "message": "Transaction is not unique", 
                "file": "chain_controller.cpp", 
                "line_number": 1194, 
                "method": "validate_uniqueness"
            }, 
            {
                "message": "", 
                "file": "chain_controller.cpp", 
                "line_number": 328, 
                "method": "_push_transaction"
            }, 
            {
                "message": "", 
                "file": "chain_controller.cpp", 
                "line_number": 284, 
                "method": "push_transaction"
            }
        ]
    }
}
`

Maybe similar problem:
[dawn-v3.0.0 create account error happens, but DAWN-2018-03-30-ALPHA will works well!](https://github.com/EOSIO/eos/issues/2218)
but can't solve my problem.

**Comment by wanderingbort** [comment]
This a bad error message and we are fixing that. 

What it means is that code which explodes: `actions[...].data` into a more readable JSON object (instead of an opaque hex buffer) cannot find the type in the associated ABI.  This can mean that the ABI for the contract you deployed to the `currency` account was out of date OR that you didn't upload the ABI.  In 3.0 ABI upload is a separate action (which is automated for you when you use `cleos`)

This message happens _after_ the chain accepts the transaction when the RPC server is trying to format a response.  This is why you get the second error when you push the transaction again.  It was already accepted to the chain but that success was hidden by the first error.

I'm going to close this issue as we already have an issue to track and fix that original error message. 

If you feel that the above does not accurately reflect the issue please feel free to re-open

**Comment by BestSilent** [comment]
@wanderingbort this problem fixed?

**Comment by BestSilent** [comment]
@Hipponensis  Same issue here. this problem fixed?
