### ISSUE TITLE
Tic Tac Toe Example Broken

### ISSUE THREAD

**Issue by blackwatertepes** [EOSIO/eos#2357]
The tic tac toe example found in: `/Users/tyler/Github/eos/contracts`
generates a different ABI using eosiocpp, than the one ABI that's currently checked into the repo.
And after deploying this ABI, and pushing a create action, the following error is raised...

```
Error 3040002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'{"challenger":"inita","host":"initb"}' is invalid args for action 'create' code 'tic.tac.toes'
Invalid cast from object_type to string
```

There's a comment within the old ABI that's probably related to this issue...
"This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-12T21:37:40"

Is there something wrong with the .cpp, or the ABI generator?

**Comment by elmato** [comment]
Tic Tac Toe Example has the ABI file created manually.

This maybe change in the following release, but If you want to use **eosiocpp** to generate the ABI for that contract some changes needs to be made to tic_tac_toe.hpp since Tic Tac Toe uses the old contract style (not using EOS_ABI macro).

_tic_tac_toe.hpp_
https://gist.github.com/elmato/d191a7acb3bc101511e56dec5dd723a8

After that you generate the abi using
`eosiocpp -g tic_tac_toe.abi tic_tac_toe.cpp`

**Comment by ender233** [comment]
@blackwatertepes 
hello. have you solve the problem? help to share it .

**Comment by blackwatertepes** [comment]
In order to resolve this issue, either...

* The tic_tac_toe.hpp file needs to be updated to work with the latest version of the eosiocpp ABI generator
* You need to use an older version of eosiocpp to generate the ABI
* You need to hand write the ABI

I have not made any of the solutions listed above.

**Comment by quocle108** [comment]
@blackwatertepes @ender233 ,
Please use following code to check abi file and put the content here, I will help

```
$ cleos get code -a contract.abi contract
$ cat contract.abi
```

**Comment by andriantolie** [comment]
I've just added a PR yesterday to update the tic tac toe to follow latest eosio framework (it now uses EOSIO_ABI and supports eosiocpp abigen now). Hopefully it will be in soon :)
