### ISSUE TITLE
Review support for compiler-runtime symbols

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2487]
# Description

Currently, our WebAssembly Toolchain (aka clang) uses a predefined library per-platform to provide implementations for certain AST native operations that do not have native support on the architecture in question.  We can refer to this as `compiler-rt`.  Some examples are support for 128bit integer and floating point math.  

As we have no actual `compiler-rt` library for the webassembly-32 platform, these symbols are represented as imports in the resulting `.wast/.wasm` output of our toolchain.  

This has led to an entire collection of intrinsics that provide these implementations at runtime.  This makes the operation of these symbols part of consensus; if we change the implementation we will create divergent state. 

Ideally, our intrinsics would define "at rest" binary interfaces.  Meaning, for example, we can dictate that `long double` is an IEEE754 quadruple precision floating point when it is passed  but we may not want to dictate how contracts do math on them.  

related to #2482

# Proposal

We move all of the implementation details of the `compiler-rt` library into our toolchain so that the `.wast/.wasm` file is complete when it needs those implementations.   This would put the choice on the contract developer so long as they maintain the invariants of the ABI for passing data to/from remaining real intrinsics. 

To achieve this, we would produce a `compiler-rt` library targeting our flavor of WebAssembly-32 similar to how we build statically linkable units for the C and C++ standard libraries. 

As we upgrade that library, contract authors can adopt improvements/changes by recompiling and re-uploading without requiring chain forks.

**Comment by wanderingbort** [comment]
@larryk85 @arhag please review and comment

**Comment by spoonincode** [comment]
100% in favor of this. compiler-rt works with WASM today.

**Comment by larryk85** [comment]
#### I Agree, But...
I agree with this proposal, but there are a few caveats to this approach.  After working on this all day, I have gained some new insight into the problem of simply ```"linking"``` this like the other libraries.  @spoonincode can you elaborate on what you mean by ```compiler-rt``` works with WASM today?  
#### Problems
* I can compile ```compiler-rt``` just fine as-is with no modifications, but we have no means of directing clang to use this, as clang is looking for a static library.  
* Secondly, the ```compiler-rt``` function signatures do not match the generated calls and import signature for most of the builtins.  
  *  This is another big reason I would like to remove the ```compiler_builtins api```, because if clang does something different we would have to support both versions and do more work to link the correct implementation.
* Thirdly, the builtin calls are only added at the time of code generation (as in these will not be present in the ```*.bc``` files), this means that we have to have some form of an actual linker to link against this library.

#### Some Kind of Solution?
After a lot of contemplation of how to resolve this, I do have a proposed solution to the problem.  Because this linkage has to occur after clang compiles,  we are forced to work with the ```wast``` and no longer ```LLVM IR```. So, I could make a "linker" tool based off of wabt's libraries to parse the generated wast and add the correct functions from compiler-rt to satisfy any imports. <br><br>In addition to this I would have to fix the functions to take the correct parameters, but we could get to parity with where we are at and fill in the rest later or when needed. <br><br>Also, we would have to compile the ```compiler-rt library``` as a ```wast``` library and not an ```IR``` library in order for this to work (not a limitation just a side note).  
<br><br> Proposed toolchain change : <br>``` *.cpp => clang -> [*.bc + IR_libs] => llvm-link -> linked.bc => ... ``` <br>``` llc -> *.s  => s2wasm -> [*.wast + rt.wast] => rt_linker -> rt_linked.wast```

**Comment by wanderingbort** [comment]
@spoonincode , Do you know if the `master` version of LLVM's linker operates differently in this regard?

**Comment by spoonincode** [comment]
master and clang6 behave differently compared to what we're using now. There you effectively just do

```g++ file.cpp -o output.wasm```

and you get a full formed binary WASM ready to go. None of this crazy rigmarole that we're doing now. This also means you can do
```g++ file.cpp -c -o file.o
g++ nom.cpp -c -o nom.o
ar rcs lib.a nom.o file.o
g++ main.cpp lib.a -o output.wasm
```

The big problem is that the lld to do this in clang6 doesn't support "gc-sections" which means when we link against libc/c++ we end up with a monster WASM. master fixes this.

> compiler-rt works with WASM today.

The default lld behavior in at least lld master (maybe lld6 not sure) actually links by default to compiler-rt. compiler-rt is pretty much _required_ for newer clang.

**Comment by larryk85** [comment]
That all sounds great.  @spoonincode do you think we will be able to convert over to this before June 1st?

**Comment by spoonincode** [comment]
I think the big question is wether or not we feel comfortable shipping the WASM compiler based on master 🤔

**Comment by bytemaster** [comment]
Once we have more info this can go into the first protocol upgrade.

**Comment by arhag** [comment]
There is no need for the HARDFORK label on this issue since we need to support the compiler_builtin intrinsics for existing contracts anyway.

Furthermore, while the latest CDT can bring in compiler-rt into the generated WASM code entirely (meaning the contract does not need to use any of the compiler_builtin intrinsics), it bloats the contract size considerably. So for the reasons of reducing RAM cost, it will likely be preferably for contracts to continue to use the intrinsics.
