### ISSUE TITLE
Error code assert

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#2561]
Assert should take an error code, this can be defined as a table in the abi for printing human readable messages.  
Two versions of assert will exist:
* ```assert(uint64_t)```
* ```asserts(const char*, size_t)```

The ```asserts``` intrinsic is the same as the old ```assert```, but will now also take a length.

**Comment by arhag** [comment]
There will actually be three versions of the assert intrinsics:
```
void eosio_assert( bool condition, null_terminated_ptr msg );
void eosio_assert_message( bool condition, array_ptr<const char> msg, size_t msg_len );
void eosio_assert_code( bool condition, uint64_t error_code );
```

The `eosio_assert` function name will remain for backwards compatibility. It could in theory be implemented on the WASM side using the `eosio_assert_message` intrinsic (and `strlen`). But just like the `prints` and `prints_l` variations, both versions are provided because it is faster to do `strlen` on the native side than on the WASM side (particularly for binaryen).

The platform will accept any `uint64_t` number as the error code in the `eosio_assert_code` intrinsic, whether that error code is associated with a message string in the ABI or not. We do not want the ABI to become part of consensus.

User clients (like cleos) can then look up the error code in the ABI. If they find it, they can also print the human-friendly message in the error log. Otherwise, they will only print the error code.
