### ISSUE TITLE
voteproducer invalid iterator

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#2726]
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
iterator != -1: invalid iterator

**Comment by taokayan** [comment]
Would you provide the exact command/steps to produce this issue?

**Comment by brianjohnson5972** [comment]
Since this issue has gone silent for a long time, it is being closed.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
