### ISSUE TITLE
Editing the wiki

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#2748]
the wiki pages need help.  stuff is missing and the procedures don't work.  as I work my way through the issues I want to fix the documentation and given that they're a wiki, I'd expect that I can just change them, but I can't figure out how

do I need to fork the repo, change local versions and submit PRs? or is there a group I need to be added to so I can just change them?

**Comment by gleehokie** [comment]
@ekkis we require push access to the repo in order to be able to edit it which limits the editors to Block.one employees and contractors.  AFAIK GitHub does not support PRs for the repo Wikis.

That said if you do have some suggestions we want to encourage you to send them to us.  @rbw3821 tries to stay on top of the reports.  You can make note of the changes you recommend in issues here, note that you can attach files, so you could attach patch files if that works better for you.

The GitHub URL for the Wiki is https://github.com/EOSIO/eos.wiki.git.
