### ISSUE TITLE
Boot Sequence Testing

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2791]
1. verify that B1 account can only unstake at the rate of 10M EOS per year starting June 1, 2018
2. verify that no new tokens are created for producer or runner-up pay until at least 150M of stake has cast their first vote.
3. verify that no new producers are set until after 150M stake has voted.

**Comment by taokayan** [comment]
Hi, Is there any related pull request for this?

**Comment by gleehokie** [comment]
@taokayan this issue is referring to capability that should work currently but needs to be verified via a test

**Comment by abourget** [comment]
folks, the code currently talks about a `b1` account.. I suggest swapping that to `b1b1b1b1b1b1`.. because right now to inject the snapshot, we need the `eosio.system` contract loaded (to buy stuff and stake stuff).. so the 12 chars limit will be enforced at that point.. unless you want to special case that in the system contract.

I'm special-casing the `0x00000000000000000.....000000b1` ETH address in the snapshot to map to `b1b1b1b1b1b1` right now in `eos-bios`. just sayin' :)

**Comment by andriantolie** [comment]
ATC:
- Run unitests/unit_test --run_test=bootseq_tests and ensure everything passes

**Comment by abourget** [comment]
Ok, I'm not 100% sure it was always the case that newaccount allowed eosio to create them. We switched the sequence anyway to create b1 before loading eosio.system in.

Seeing the latest code here,  we probably can just create it with the rest :-) thanks
