### ISSUE TITLE
voteproducer went error   Invalid cast from type 'null_type' to Object

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#2814]
1808094ms thread-0   main.cpp:2151                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'null_type' to Object

**Comment by taokayan** [comment]
Can you provide your command?

**Comment by brianjohnson5972** [comment]
Since this is an old issue and it has gone silent, it is being closed.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
