### ISSUE TITLE
Shorter branch may take over much longer branch

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eos#2835]
An unexpected scenario in slim branch may happen in which the shorter branch takes over a (much) longer branch.

As illustrated below:
![lastirrnumber](https://user-images.githubusercontent.com/37097018/39747260-5a4a56d4-52df-11e8-8d23-46ad3d14259b.png)
4 producers A,B,C,D are producing in turns. After block 12, forks happen and result in 3 different branches: Branch A has producer A, branch B has producer B, branch C has producers C & D. From A's point of view, its last irreversible block number is 9. However, C&D's point of view, their last irreversible block number is 6. After then, branch A rejoined with branch C, C&D think that branch A has a bigger last irreversible number and switch into the shorter branch.

I'm wondering whether this is a design issue or something expected.

**Comment by taokayan** [comment]
test case created in pull request #2839

**Comment by wanderingbort** [comment]
This particular scenario's result is intended.  To understand why this is the case and, why it still holds that irreversibility is an optimization of pure DPOS (where longest chain wins) we have to play the scenario forward in time.  

What 2/3 + 1 producers on a given fork means is that, without detectable bad behavior, it should *eventually* produce the longest chain.  This is simple to understand because there can be at most 1/3 - 1 competitive producers on the minority fork and no matter what their lead is at some point in time, the 2/3 + 1 producers will eventually win.  Technically this is true with 1/2 + 1 vs 1/2 - 1 but for other reasons, the tolerance for DPOS is 2/3 + 1.

In your example we have 3 candidate forks: 
 - A in an isolated partition
 - B in an isolated partition
 - C/D in an isolated partition

None of these forks have 2/3 + 1 producers so, we don't have a clear winner for longest DPOS chain yet.  C/D is producing blocks faster _for now_ but it is not clear that another chain can not overtake it in the future.  

The rules are in place to make the best guess at what will be the longest chain in the end.  To review those rules are:

 - pick the fork with the most irreversible block 
 - break ties with the longest chain on top of that

So, when C/D reconnect to A they must decide which fork to support.  
 - Option 1) is their minority fork for which they can only prove that they are aware of (2 producers)
 - Option 2) is A's minority fork for which they can now prove that they AND A is aware of (3 producers)

The fun extra factor is where are A and B.  Inspecting only the state of the chain we are aware of we cannot know for sure but, it is possible that A and B are partitioned together somewhere and building a minority chain.  It is also likely that this chain includes A's blocks 13-15 because A had the first option for those blocks with respect to time.  

This gives us 
Option 3) a hypothetical minority fork with A/B built off of A's blocks (2 producers)
Option 4) a hypothetical minority fork with A/B built _without A's blocks_ (2 producers)

As for velocity, if option 2 is healthy it is a clear winner.  Options 3 and 4 have the _same_ velocity as Option 1 and Option 2 and 3 build off of A's shorter chain.  

Lets pop the stack, the decision at the present time is only, should we switch to the minority fork we are aware of?  There are 4 likely futures, if we consider them all equally likely our expected participation for choosing to ignore A is 2 producers and our expected participation for including A is 2.5 producers.  In the world of imperfect information, we chose to include A's blocks and start over on a shorter chain as it will probably eventually be longer.  

For the record, I consider it still possible that our current rules do not accurately reflect the best decision in all cases but, at least in this case I expect that our current rules do eventually produce the longest chain.  

For instance, given the rules and your scenario if B had produced 3 blocks in isolation and C/D had simultaneously learned about A and B's minority forks it is ambiguous as to which minority fork that can/should/will build on.  In the above breakout, that removes Option 3 from the table and replaces it with at least one that directly competes with the implied participation of Option 2 but requires a different immediate decision (A or B's minority fork).
