### ISSUE TITLE
the safety problem that two cleos connect one nodes

### ISSUE THREAD

**Issue by Phoenix117** [EOSIO/eos#2869]
I have one nodes and one cleos on the same machine, and I have another cleos on the other machine.
I start the nodes and set http-server-address '0.0.0.0:8888' to let another cleos on the other machine can connect the nodes.I use the first cleos to unlock the wallet on the first machine. After that, I use the second cleos to connect the nodes, and I find the wallet is unlocked, and I can use the second cleos to see the private and public keys of the accounts that have been imported into the wallet on the first machine.
**I wonder if it is necessary that the second cleos unlock the wallet on the first machine again.**

**Comment by jgiszczak** [comment]
All of the wallet handling code in the repository exists solely for testing purposes and proofs of concept.  It is not intended for use as production code.

In particular, using the wallet plugin in `nodeos` is not a suggested production configuration, and should not be used with private keys that need to remain private.

It is expected that community-created wallets, especially cross platform wallets, will provide production-ready EOS support, since that is their specialty.

**Comment by Phoenix117** [comment]
Got it，Thank you！
