### ISSUE TITLE
cleos command returns error

### ISSUE THREAD

**Issue by rogerone-shen** [EOSIO/eos#2905]
_alias cleos='docker-compose exec keosd /opt/eosio/bin/cleos -H nodeosd'
cleos get info_

After i run above commands, got this error:

_Host and port options (-H, --wallet-host, etc.) have been replaced with -u/--url and --wallet-url
Use for example -u http://localhost:8888 or --url https://example.invalid/_

**Comment by rogerone-shen** [comment]
I am trying to change command to this: _**docker-compose exec nodeosd /opt/eosio/bin/cleos -u http://localhost:8888/  get info**_  it works. 

Could some body help update the document:[](https://github.com/EOSIO/eos/blob/master/Docker/README.md)

**Comment by andriantolie** [comment]
It's because nodeosd is not located in the same container as keosd. The above command will work for read-only command, however, it won't work for a command that requires signing. 

`docker-compose exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888/ <your cleos subcommand here>` will solve the problem. The docker documentation has also reflected the change. Hope this helps :)

**Comment by rogerone-shen** [comment]
Great job

**Comment by ItsLeeOwen** [comment]
@andriantolie's alias works on my end, the wiki may be out of date:  https://github.com/EOSIO/eos/wiki/Local-Environment#execute-cleos-commands
