### ISSUE TITLE
unpacking field new_producers

### ISSUE THREAD

**Issue by soon14** [EOSIO/eos#2997]
2564341ms thread-0   main.cpp:99                   main                 ] 10 assert_exception: Assert Exception
(b & ~1) == 0: 
    {}
    thread-0  raw.hpp:332 unpack
optional<eosio::chain::producer_schedule_type>
    {"type":"eosio::chain::producer_schedule_type"}
    thread-0  raw.hpp:284 unpack
Error unpacking field new_producers
    {"field":"new_producers"}
    thread-0  raw.hpp:361 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    thread-0  raw.hpp:602 unpack

**Comment by taokayan** [comment]
Can you provide the detail steps to reproduce?

**Comment by brianjohnson5972** [comment]
Since this issue has been silent for a while, it is being closed.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
