### ISSUE TITLE
try to buyram, node crashed

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#3068]
![1526353234078](https://user-images.githubusercontent.com/1741302/40034446-91307d90-582f-11e8-950d-5f162b9a4f12.jpg)
![1526354212208](https://user-images.githubusercontent.com/1741302/40034876-7f20ea7a-5831-11e8-958d-ef70cbfd99f8.jpg)

**Comment by cppfuns** [comment]
I also encountered the same problem.
`root@surou-C-H110M-K-Pro:~/.local/share/eosio/nodeos# cleos system delegatebw eos.cos eos.cos '250000.0000 EOS' '250000.0000 EOS' --transfer
3396462ms thread-0   main.cpp:1002                 operator()           ] act_payload: {"from":"eos.cos","receiver":"eos.cos","stake_net_quantity":"250000.0000 EOS","stake_cpu_quantity":"250000.0000 EOS","transfer":true} 
3396463ms thread-0   main.cpp:418                  create_action        ] result: {"binargs":"0000000053043055000000005304305500f902950000000004454f530000000000f902950000000004454f530000000001"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"eos.cos","receiver":"eos.cos","stake_net_quantity":"250000.0000 EOS","stake_cpu_quantity":"250000.0000 EOS","transfer":true}} 
Error 3080001: account using more than allotted RAM usage
Error Details:
account eos.cos has insufficient ram bytes; needs 4138 has 0
root@surou-C-H110M-K-Pro:~/.local/share/eosio/nodeos# cleos system buyram eos.cos eos.cos '2500.0000 EOS'
3417367ms thread-0   main.cpp:418                  create_action        ] result: {"binargs":"0000000053043055000000005304305540787d010000000004454f5300000000"} arg: {"code":"eosio","action":"buyram","args":{"payer":"eos.cos","receiver":"eos.cos","quant":"2500.0000 EOS"}} 
Failed to connect to nodeos at http://localhost:8888/; is nodeos running?`

----------------------------------------------------------------------------------
3417381ms thread-0   apply_context.cpp:29          print_debug          ] 
[(eosio,buyram)->eosio]: CONSOLE OUTPUT BEGIN =====================

 payer: eos.cos buys ram for eos.cos with 2500.0000 EOS
free ram: 68719476736
ram bytes out: 17175575

[(eosio,buyram)->eosio]: CONSOLE OUTPUT END   =====================
3417382ms thread-0   apply_context.cpp:29          print_debug          ] 
[(eosio.token,transfer)->eosio.token]: CONSOLE OUTPUT BEGIN =====================
transfer from eos.cos to eosio 2500.0000 EOS
eos.cos balance: 999997500.0000 EOS
eosio balance: 9000002500.0000 EOS

[(eosio.token,transfer)->eosio.token]: CONSOLE OUTPUT END   =====================
Floating point exception (core dumped)
root@surou-C-H110M-K-Pro:/home/surou/eos/build# nodeos
3491617ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
3491617ms thread-0   main.cpp:101                  main                 ] /home/surou/eos/libraries/chainbase/src/chainbase.cpp(106): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database dirty flag set (likely due to unclean shutdown) replay or resync required

**Comment by bytemaster** [comment]
Are you using the latest master?   We fixed issues related to this yesterday.

**Comment by zformular** [comment]
Yes, master branch can do
