### ISSUE TITLE
[Error] Bancor protocol

### ISSUE THREAD

**Issue by hyunwoongJi** [EOSIO/eos#3070]
@bytemaster I have left comment to [the closed issue](https://github.com/EOSIO/eos/issues/3032) I opened before but I thought that it is kinda urgent issue, so I opened this issue again.

Yes the Bancor Protocol math is wrong in their "white paper"

If you wanted to fix it, you had to fix the following three lines:
https://github.com/EOSIO/eos/blob/2859389133e03acf2a3ecccdbaa6c1a9a5a8ceea/contracts/eosio.system/exchange_state.cpp#L7
https://github.com/EOSIO/eos/blob/2859389133e03acf2a3ecccdbaa6c1a9a5a8ceea/contracts/eosio.system/exchange_state.cpp#L25
https://github.com/EOSIO/eos/blob/2859389133e03acf2a3ecccdbaa6c1a9a5a8ceea/contracts/eosio.system/exchange_state.cpp#L38
It should be as follows:
```
real_type C(c.balance.amount); 
real_type R(supply.amount); 
real_type T = -1 * C * (std::pow( ONE - E/R, F) - ONE);
```
It will solve the problem

To see why this could be urgent, I append the following spread sheet. [spread sheet](https://docs.google.com/spreadsheets/d/19mJIeNupqTM-vF7jF68XC7ytPumfhLliOMFxvg4sLK8/edit#gid=0)

To apply Bancor protocol, initial total supply of ram and connected balance (in this case EOS) should be configured. This could be another governance issue to block producers.

**Comment by bytemaster** [comment]
Thank you for your interest in making sure our math is right, we can never have too many eyes. I have taken your spread sheet and integrated the buy/sell pattern into the eosio_system_tests/buysell test.

```
./unit_test -t eosio_system_tests/buysell -- --verbose
```

This test shows that after spending 560.0000 EOS in the same pattern as your spread sheet that alice buys 38461169 bytes of RAM.  We then sell this all back at once and the result is slightly less than 559.9998 (a loss of .0002 EOS to the buyer/seller).  This loss is a rounding error introduced by converting to integer and is aways in favor of the exchange. 

```
   total   = get_total_stake( "alice1111111" );
   bytes = total["ram_bytes"].as_uint64();

   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9993 EOS"), get_balance( "alice1111111" ) );

   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "10.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "10.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "10.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "30.0000 EOS" ) );
   BOOST_REQUIRE_EQUAL( asset::from_string("100000439.9993 EOS"), get_balance( "alice1111111" ) );

   auto newtotal = get_total_stake( "alice1111111" );

   auto newbytes = newtotal["ram_bytes"].as_uint64();
   bought_bytes = newbytes - bytes;
   wdump((newbytes)(bytes)(bought_bytes) );

   BOOST_REQUIRE_EQUAL( success(), sellram( "alice1111111", bought_bytes ) );
   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9991 EOS"), get_balance( "alice1111111" ) );
```

**Comment by bytemaster** [comment]
@hyunwoongJi I will update the test with larger magnitude.

**Comment by hyunwoongJi** [comment]
@bytemaster yes please do the test with larger magnitude, I have updated my spread sheet with larger magnitude also :)

**Comment by bytemaster** [comment]
larger magnitude test, equalling 5.6% of all EOS resulted in loss to user of .0048 EOS due to integer rounding.  System did not lose money.

**Comment by bytemaster** [comment]
Note that your "exchange" math assumes the exchange token is EOS... it is not.

RAM vs EOS is implemented as a relay where it is not possible to buy shares in the relay itself, only convert back and forth between the two sides of the relay.

**Comment by bytemaster** [comment]
Just for fun, I implemented your recommended changes to the code and it failed the very first test.

alice starts with 1000 EOS, and buys ram with 200 EOS.  She then sells the RAM she bought and ends up with 1000.0799 EOS for a profit of .0799 EOS.  

In all of my testing of Bancor I have found that the only math that results in NET 0 profit after extensive trading (millions of random trades) is the math we have implemented.  I even used long double and larger precision to ensure the math always comes back to 0 error with any micro-bias against the user.

**Comment by redjade** [comment]
I've read bancor formulas in https://drive.google.com/file/d/0B3HPNP-GDn7aRkVaV3dkVl9NS2M/view and think those formulas are okay IMHO.

Calculation of integral in bancor formulas requires initial value of S_0 and R_0, which are `supply.amount`(relay token RAMEOS supply) and `c.balance.amount`(EOS or RAM) in `exchange_state.cpp`. So, calculating `E` and `T` in `exchange_state.cpp` requires unmodified `supply.amount` and `c.balance.amount`. That means codes below are correct according to bancor formulas.

```
real_type C(c.balance.amount); // at convert_to_exchange()

real_type R(supply.amount); // at convert_from_exchange()
```

Especially, `convert_from_exchange()` from RAMEOS to EOS/RAM needs more attention. Input parameter value of RAMEOS delta `in.amount` in `convert_from_exchange` is always positive. But in fact it is a negative value because we are converting from RAMEOS to EOS/RAM, so it is a decreasing value. So, inside of std::pow() of T calculation, `E` should be `-E`.

And we are converting RAMEOS to EOS/RAM, `T` is always negative value. But `out` is subtracted from `c.balance.amount`, `T` needs to be positive. So, negative multiplication is necessary. That means code below are correct according to bancor formulas.

```
real_type T = -C * (std::pow( ONE - E/R, F) - ONE);
```

Therefore, I think suggestion by @hyunwoongJi is valid.

I tested with unittest `eosio_system_tests/buysell` and got results below. With code compliant to bancor formula, though inevitable rounding error, results shows more accurate `sellram` conversion.

```
diff --git a/contracts/eosio.system/exchange_state.cpp b/contracts/eosio.system/exchange_state.cpp
index b621bdef9..c57214794 100644
--- a/contracts/eosio.system/exchange_state.cpp
+++ b/contracts/eosio.system/exchange_state.cpp
@@ -4,7 +4,8 @@ namespace eosiosystem {
    asset exchange_state::convert_to_exchange( connector& c, asset in ) {
 
       real_type R(supply.amount);
-      real_type C(c.balance.amount+in.amount);
+      //real_type C(c.balance.amount+in.amount);
+      real_type C(c.balance.amount);
       real_type F(c.weight/1000.0);
       real_type T(in.amount);
       real_type ONE(1.0);
@@ -22,7 +23,8 @@ namespace eosiosystem {
    asset exchange_state::convert_from_exchange( connector& c, asset in ) {
       eosio_assert( in.symbol== supply.symbol, "unexpected asset symbol input" );
 
-      real_type R(supply.amount - in.amount);
+      //real_type R(supply.amount - in.amount);
+      real_type R(supply.amount);
       real_type C(c.balance.amount);
       real_type F(1000.0/c.weight);
       real_type E(in.amount);
@@ -35,7 +37,8 @@ namespace eosiosystem {
      // -1 can be expressed as std::expm1(n * std::log1p(x)). 
      // real_type T = C * std::expm1( F * std::log1p(E/R) );
       
-      real_type T = C * (std::pow( ONE + E/R, F) - ONE);
+      //real_type T = C * (std::pow( ONE + E/R, F) - ONE);
+      real_type T = -C * (std::pow( ONE - E/R, F) - ONE);
       //print( "T: ", T, "\n");
       int64_t out = int64_t(T);
 
diff --git a/unittests/eosio.system_tests.cpp b/unittests/eosio.system_tests.cpp
index d8417f854..fb034771f 100644
--- a/unittests/eosio.system_tests.cpp
+++ b/unittests/eosio.system_tests.cpp
@@ -474,7 +474,9 @@ BOOST_FIXTURE_TEST_CASE( buysell, eosio_system_tester ) try {
    wdump((init_bytes)(bought_bytes)(bytes) );
 
    BOOST_REQUIRE_EQUAL( true, total["ram_bytes"].as_uint64() == init_bytes );
-   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9993 EOS"), get_balance( "alice1111111" ) );
+   //BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9993 EOS"), get_balance( "alice1111111" ) );
+   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9998 EOS"), get_balance( "alice1111111" ) );
+
 
 
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100.0000 EOS" ) );
@@ -486,7 +488,8 @@ BOOST_FIXTURE_TEST_CASE( buysell, eosio_system_tester ) try {
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "10.0000 EOS" ) );
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "10.0000 EOS" ) );
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "30.0000 EOS" ) );
-   BOOST_REQUIRE_EQUAL( asset::from_string("100000439.9993 EOS"), get_balance( "alice1111111" ) );
+   //BOOST_REQUIRE_EQUAL( asset::from_string("100000439.9993 EOS"), get_balance( "alice1111111" ) );
+   BOOST_REQUIRE_EQUAL( asset::from_string("100000439.9998 EOS"), get_balance( "alice1111111" ) );
 
    auto newtotal = get_total_stake( "alice1111111" );
 
@@ -495,7 +498,8 @@ BOOST_FIXTURE_TEST_CASE( buysell, eosio_system_tester ) try {
    wdump((newbytes)(bytes)(bought_bytes) );
 
    BOOST_REQUIRE_EQUAL( success(), sellram( "alice1111111", bought_bytes ) );
-   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9991 EOS"), get_balance( "alice1111111" ) );
+   //BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9991 EOS"), get_balance( "alice1111111" ) );
+   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9996 EOS"), get_balance( "alice1111111" ) );
 
 
    newtotal = get_total_stake( "alice1111111" );
@@ -510,7 +514,8 @@ BOOST_FIXTURE_TEST_CASE( buysell, eosio_system_tester ) try {
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100000.0000 EOS" ) );
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "100000.0000 EOS" ) );
    BOOST_REQUIRE_EQUAL( success(), buyram( "alice1111111", "alice1111111", "300000.0000 EOS" ) );
-   BOOST_REQUIRE_EQUAL( asset::from_string("49400999.9991 EOS"), get_balance( "alice1111111" ) );
+   //BOOST_REQUIRE_EQUAL( asset::from_string("49400999.9991 EOS"), get_balance( "alice1111111" ) );
+   BOOST_REQUIRE_EQUAL( asset::from_string("49400999.9996 EOS"), get_balance( "alice1111111" ) );
 
    auto finaltotal = get_total_stake( "alice1111111" );
    auto endbytes = finaltotal["ram_bytes"].as_uint64();
@@ -520,7 +525,8 @@ BOOST_FIXTURE_TEST_CASE( buysell, eosio_system_tester ) try {
 
    BOOST_REQUIRE_EQUAL( success(), sellram( "alice1111111", bought_bytes ) );
 
-   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9943 EOS"), get_balance( "alice1111111" ) );
+   //BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9943 EOS"), get_balance( "alice1111111" ) );
+   BOOST_REQUIRE_EQUAL( asset::from_string("100000999.9975 EOS"), get_balance( "alice1111111" ) );
 
 } FC_LOG_AND_RETHROW()
 
```

@bytemaster please review my experiments. Thank you.

**Comment by sergioyuhjtman** [comment]
I agree with @redjade

**Comment by hyunwoongJi** [comment]
Thank you @redjade and @bytemaster. I will look into it 👍

**Comment by yudilevi** [comment]
Hey guys, Yudi from Bancor here.
The document linked in the original post is an older version that might have had some issues.
Please take a look at the latest whitepaper -
https://storage.googleapis.com/website-bancor/2018/04/01ba8253-bancor_protocol_whitepaper_en.pdf

The entire document was revised and the formula is a bit different (or rather, the representation makes more sense).

Regardless of the theoretical math, the implementation isn't supposed to have any issues and the EOS implementation should also be accurate and more importantly, can't be gamed.

**Comment by redjade** [comment]
Thank you for your replies, @hyunwoongJi, @sergioyuhjtman and @yudilevi from Bancor.

Before I wrote comment above, I had already read latest bancor whitepaper also and compared them.

AFAIK, theoretical math is identical in both papers, and only representations are changed as below.

* F in old one becomes CW in latest.
* R in old one becomes Connector 'Balance' of connected token in latest.
* S in old one remains same as 'Supply' of smart token or relay token in latest.
* E in old one becomes 'connected token paid out' when selling smart token or realy token, and 'connected tokens paid' when buying smart token or relay token in latest. 'Connected token' here is parent currency.
* T in old one becomes 'token destroyed' when selling smart token or relay token, and 'token issued' when buying smart token or relay token in latest. 'Token' here is smart token or relay token.

And I think that there are no other issues in math and formulas. It would be helpful with your clarification about ‘some issues’.

Representation in `exchange_state.cpp` is different with latest whitepaper, but math is same with latest whitepaper except what @hyunwoongJi pointed out before.

* R in `exchange_state.cpp` is 'supply' of smart token or relay token.
* C in `exchange_state.cpp` is connector 'balance' of connected token.
* F in `exchange_state.cpp` is CW in convert_to_exchange and 1/CW in convert_from_exchange.
* T in `exchange_state.cpp` is 'connected tokens paid' in `convert_to_exchange` and 'connected token paid out' in `convert_from_exchange`.
* E in `exchange_state.cpp` is 'token issued' in `convert_to_exchange` and 'token destroyed' in `convert_from_exchange`.

If math have changed from older version to latest version of bancor whitepaper and my understanding needs correction, please let me know.

If my understanding is correct, comment I wrote above is valid still. Therefore, changes suggested by @hyunwoongJi  is valid. And I think results with diff also show that. But I could be wrong, so it would be very helpful if someone else look into this issue.

> Regardless of the theoretical math, the implementation isn't supposed to have any issues

I agree. If a implementation of bancor is correct and compliant to math, then that implementation will surely work as intended. If not correct, will not work. Surely, we are talking about math and engineering, not alchemy.

> and the EOS implementation should also be accurate and more importantly, can't be gamed.

Sorry for my confusion about sentence above, because English is not my native tongue. Am I right in thinking @yudilevi  mean that you have verified that current bancor implementation in EOSIO is correct? Could you clarify for me? Thank you.

**Comment by yudilevi** [comment]
When I say 'some issues' I don't specifically refer to the formula but rather the representation that used to confuse some readers - we had multiple users complaining that the math doesn't add up - the main reason was negative input/output that confused some users.
The initial version also pointed out to a google sheet that used negative inputs and that further confused some users.
So the current WP version is valid as far as we can tell and is also in line with the implementation.

Re. EOSIO, I didn't check it myself but I have discussed the implementation with @bytemaster and I believe the current approach is sound.
On top of that, using the fixes above seemed to have generated results that allow users to gain more funds over time which means they would eventually break the system which (naturally) doesn't look right :)

**Comment by yudilevi** [comment]
I was referring to @bytemaster test results after the suggested fixes which gave users some profit - did you actually see different results?

**Comment by redjade** [comment]
Oh, I got it. I couldn't find @bytemaster test code with suggested fixes, so I cannot tell about it.

With my test code diff with suggested fixes included in my previous comment, you can reproduce what I saw.

See section below 'buysell' in `unittests/eosio.system_tests.cpp` and track balance of `alice1111111` and compare results without(current code) or with fixes(my diff).
https://github.com/EOSIO/eos/blob/master/unittests/eosio.system_tests.cpp

**Comment by sergioyuhjtman** [comment]
I propose to open a telegram group to discuss this issue  @hyunwoongJi @redjade . You can find me as "sergioyuhjtman"

**Comment by redjade** [comment]
@sergioyuhjtman, @hyunwoongJi and I opened a telegram group and we have discussed this issue so far. I implemented bancor with fixes and current (and similar) EOSIO bancor in C++. Those are without RAM int64_t conversion. gist below is code, its results and my findings.

https://gist.github.com/redjade/ca88d90e3f838c57ea7a1a287b23e30a
Result summary and notes:
* correct bancor implementation with fixes suggested by @hyunwoongJi
  * smart token scenario (CORE <-> RAMCORE) : works as expected.
  * relay token scenario (CORE <-> RAMCORE <-> RAM) : works as expected.
* current bancor implementation of EOSIO
  * smart token scenario (CORE <-> RAMCORE) : shows broken result. It is trivial to show that convert_to_exchange and convert_from_exchange is incorrect with this result.
  * relay token scenario (CORE <-> RAMCORE <-> RAM) : fortunately **works** because two-way conversion holds invariant.
    * invariant holds in current bancor implementation of EOSIO, verified by @sergioyuhjtman
    * invariant holds when S = S_0, m = 2, F1 = F2 in multiple reserve currencies, also verified by @sergioyuhjtman

I hope that two mathematicians, @sergioyuhjtman and @hyunwoongJi, will comment their findings, implementation recommendations and concluding remarks, and hope that B1 will correct their implementation of bancor algo in EOSIO.

**Comment by hyunwoongJi** [comment]
Thank you @redjade, I also verified that the invariant (by @sergioyuhjtman) under S = S_0, F1=F2. I think the constraint m = 2 is not necessary for this invariant but it is the only case for current implementation of eosio.

So, it is proven that current implementation has not critical hole in it. 

However, I think there could be a more precise code for selling and buying ram under the constraints, because the two function (sell ram & buy ram) consists of two sub functions, which incurs round-off error (relative to combined function). This means that there could be a better way to do so and not mean that there is a flaw.

**Comment by hyunwoongJi** [comment]
@bytemaster I have enhancement for current implementation. Please see the following : https://gist.github.com/redjade/ca88d90e3f838c57ea7a1a287b23e30a#gistcomment-2603647

Thank you @redjade and @sergioyuhjtman :)
