### ISSUE TITLE
Improve abi json to binary errors

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#3084]

**Comment by tbfleming** [comment]
Partially fixed in #3083. Long term, the arguments should be in a more readable form (e.g. ```name a, string b, ...```) instead of in abi json format.

**Comment by brianjohnson5972** [comment]
Since this issue has been silent for a while, it is being closed.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
