### ISSUE TITLE
How to deploy multiple nodes, and each node can generate blocks?

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eos#3112]
Now I can deploy three nodes,only one node generate blocks with producer eosio,i want to other two node generate blocks , What should I do???

**Comment by jgiszczak** [comment]
See https://github.com/EOSIO/eos/wiki/Testnet-Single-Host-Multinode for detailed instructions regarding bringing up a multinode network.

As of this writing, that page is slightly out of date. It is being updated as I write. When the JSON argument to the setprods command near the bottom begins with "schedule" instead of "version", it has been brought up to date.

**Comment by healthwallet** [comment]
i want to muiti-host ,not Single host,It's the same logic???
