### ISSUE TITLE
Proposal: Threshold signature for faster cross chain communication

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#3155]
For the block finality system, I'd like to propose a threshold signature scheme. These allow the producers to agree on a single public key where if a threshold (2/3ths) cooperates, they can produce a valid signature. This would reduce the transaction cost for cross chain verification from 2/3ths of the producers to 1.

Dfinity uses [BLS](https://en.wikipedia.org/wiki/Boneh%E2%80%93Lynn%E2%80%93Shacham) for it's uniqueness (always the same signature, regardless of the participants) and it's non-interactiveness (only one round). Neither of these properties are really necessary in this case, so we can choose a more classic scheme. There have been quite a few papers on threshold groups systems for elliptic curves, so that's a possibility as well.

**Comment by bytemaster** [comment]
I agree that this is the desired implementation. Are there any schemes that work with R1 or K1 curves?

**Comment by bytemaster** [comment]
https://www.cs.princeton.edu/~stevenag/bitcoin_threshold_signatures.pdf

**Comment by bytemaster** [comment]
https://eprint.iacr.org/2016/013.pdf

**Comment by toonsevrin** [comment]
https://eprint.iacr.org/2016/013.pdf sounds promising (especially that it does not have the key reconstruction problem that previous works had). But to quote the article:

> Since there are plenty of optimized threshold signature schemes for other algorithms, one who wanted to use a threshold scheme would generally just choose a different signature scheme that was well suited for the problem at hand. To the best of our knowledge, there has never previously been an application for which DSA was the only option.

Neither is our application. All though using it would probably decrease our attack surface.

**Comment by toonsevrin** [comment]
If the attack surface is increased by this scheme, it may be interesting to run this along with the individual producer signatures. 

This way light clients can choose themselves, or use the individual signatures as a fall-back mechanism (a dispute mechanism could easily prove that the threshold scheme is broken).

**Comment by wanderingbort** [comment]
I think this is a good suggestion for our "BFT" messages which @bytemaster has talked about in previous blog posts.  That augments the normal BFT mechanics allowing light clients to by assured of finality before the block-chain reaches it unless there are a large number of malicious actors.

That said, the DPOS irreversibly mechanic in EOSIO already amortizes to 1 signature per irreversible block in the nominal case.  This is because each signed block constitutes an implied signature on many other blocks.  

With 12 blocks per producer, and 21 producers (and the newest set of rules).  Finality of the first 12 blocks comes 349 blocks later if the network is un-forked and live.  After that, every 12th block constitues a new producer confirmation which can bring 12 more blocks to finality with a single signature.  If we didnt need the signatures on the other 11 blocks to finalize them later we could claim to amortize down to 1/12th of a signature alas, those are important.  So, once the pipeline is full and assuming no active forking scenarios the nominal network of producers should produce 12 new final blocks every 6 seconds for a single signature for an amortized cost of a signature per block.  

Our compact K1 signatures are 65 bytes plus a suite discriminator, so 66 bytes per half second or 132bytes/sec in signatures.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE (overcome by events).  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
OBE (overcome by events)
