### ISSUE TITLE
Testnet vs Mainnet Keys

### ISSUE THREAD

**Issue by ocZio** [EOSIO/eos#3169]
Using the Dockerfile and following the docker tutorial to generate a pair of private/public keys for EOS registration (instead of using the online website).

Was wondering if there is anything that needs to be changed in order to ensure the generated Keys are for the mainnet and not the testnet (if this actually is a thing?)

Like on Bitcoin network the testnet has different key Prefixes for the testnet/mainnet.

Thanks.

**Comment by jgiszczak** [comment]
There is no distinction between keys generated for use on a testnet and keys used on the mainnet.  There are various prefixes, but these indicate key types such as which curve was selected, and work regardless of the net.  It's entirely possible to use the same key on both a testnet and on the mainnet, but this practice is not recommended since key discipline is difficult when copying and pasting debugging output.
