### ISSUE TITLE
Issue delegating bandwidth to another account from cleos 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3309]
![image](https://user-images.githubusercontent.com/347290/40401419-4b33ab88-5e14-11e8-853d-e38adea73cb1.png)

![image](https://user-images.githubusercontent.com/347290/40401426-51b15b4a-5e14-11e8-9aa4-00a6961d866d.png)

If this doesn't work then we need unit tests to prove it.  Where are the unit tests that prove it *should* work?

**Comment by arhag** [comment]
This is a bug in the system contract. The unit tests were not proving it because all the staking with transfers were done by `eosio` which is handled as a special case in the `system_contract::changebw` function.

PR #3311 fixes the bug and adds an extra test case to `eosio_system_tests/stake_unstake_with_transfer` to trigger the conditions of the bug.
