### ISSUE TITLE
size.value*sizeof(T) < MAX_ARRAY_ALLOC_SIZE | JungleTestnet

### ISSUE THREAD

**Issue by sss-CRS-sss** [EOSIO/eos#3367]
Synchronization stopped at ~ 180K blocks and then the synchronization looped on a couple of hundred blocks. Hard replay did not help, synchronization with 160k reaches 180k and also falls into a cycle. A simple restart of the node causes an error:

```
3180131ms thread-0   chain_plugin.cpp:130          plugin_initialize    ] initializing chain plugin
3180135ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
3180135ms thread-0   block_log.cpp:123             open                 ] my->head->block_num(): 160849
3180135ms thread-0   block_log.cpp:129             open                 ] Index is nonempty
3180303ms thread-0   main.cpp:106                  main                 ] 10 assert_exception: Assert Exception
size.value*sizeof(T) < MAX_ARRAY_ALLOC_SIZE:
    {}
    thread-0  raw.hpp:560 unpack
```

https://trendsfuture.ru/uploads/block_before_hardreplay.tar.gz
https://trendsfuture.ru/uploads/block_after_hardreplay_2times.tar.gz

**Comment by InfoHunter** [comment]
I also encountered with this error

**Comment by InfoHunter** [comment]
#3047 seems relevant to this issue...

**Comment by InfoHunter** [comment]
I just removed the `shared_mem` and `blocks` directories and restarted `nodeos` with JungleTestnet settings, it seems fine now synchronizing the blocks. Waiting to see what will happen in minutes...

**Comment by jorfermo** [comment]
It's happening to us in several different instances when stopping and starting.

No way of safely restart. Only resync works

**Comment by brianjohnson5972** [comment]
Please report which tag you are using or what hash of the repo you have.  There have been several commits around addressing this problem since the DAWN-4.1.0 tag.

**Comment by brianjohnson5972** [comment]
Can you run: 
`git submodule update --init --recursive`

If after that you get a line like:

Submodule path 'libraries/chainbase': checked out 'cd77cf59cf61ca1740f715b39f404a1447b5a0d3'

then you didn't have the fix to guard against starting with corrupted shared_memory.  If that doesn't show up then we still have a problem.

Also, if the submodule is up to date, an easy way to test if the guard code is present is to start up a node and execute:

kill -9 <nodeos pid>

and then restart the node.  You should then get an exception indicating that you need to start nodeos with either "--replay-blockchain" or "--resynch-blockchain".  When you restart you may need to use "--resynch-blockchain" because there was separate work to fix having a block_log that had its last block corrupted.  If you don't  get the exception (and nodeos shutting down immediately) then you probably need to to a clean and rebuild.

**Comment by arhag** [comment]
@sss-CRS-sss Can you please provide the genesis.json file you used with this blockchain?

**Comment by sss-CRS-sss** [comment]
```
{
  "initial_timestamp": "2018-03-22T23:00:00.000",
  "initial_key": "EOS5UDp9v8rQfrZwUPog8KetBo7cEEbMRrSpBJjfPqB3489Mz2b47",
  "initial_configuration": {
    "max_block_net_usage": 1048576,
    "target_block_net_usage_pct": 1000,
    "max_transaction_net_usage": 524288,
    "base_per_transaction_net_usage": 12,
    "net_usage_leeway": 500,
    "context_free_discount_net_usage_num": 20,
    "context_free_discount_net_usage_den": 100,
    "max_block_cpu_usage": 100000,
    "target_block_cpu_usage_pct": 500,
    "max_transaction_cpu_usage": 50000,
    "min_transaction_cpu_usage": 100,
    "max_transaction_lifetime": 3600,
    "deferred_trx_expiration_window": 600,
    "max_transaction_delay": 3888000,
    "max_inline_action_size": 4096,
    "max_inline_action_depth": 4,
    "max_authority_depth": 6,
    "max_generated_transaction_count": 16
  },
  "initial_chain_id": "2018052300203000000000000000000000000000000000007472696e6974790a"
}
```

**Comment by arhag** [comment]
@sss-CRS-sss Thanks

**Comment by gleehokie** [comment]
Related to #3384
