### ISSUE TITLE
Add intrinsic to get current version number of the active producer schedule

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#3387]
Add a new intrinsic called `int64_t get_active_schedule_version()` which returns the current version of the active producer schedule.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
