### ISSUE TITLE
logging filters for critical info

### ISSUE THREAD

**Issue by dmore** [EOSIO/eos#3452]
considering the tendency of some block producers to share screens to the community, make sure private_key logging is always obfuscated so greping debug/info level logs for a private key returns nothing. ideally exceptions should also be protected critical tokens and overload private_key info if error contains a reference to it.

**Comment by gleehokie** [comment]
@dmore have you seen examples of private keys being logged?  If so please share them here.

**Comment by dmore** [comment]
the three I can think of are:
1) cleos --wallet-port 8899 wallet create
Creating wallet: default
Save password to use in the future to unlock your wallet
Without password imported keys will not be retrievable
"password_shown_here"

2) cleos create key
Private Key: privatekey....
Public Key: EOS5...

3) I've seen somewhere not sure where Private Key: Password Start ******** Password_End. I could be confused but to me that's also giving info regarding what grep to search for.

NOTE: until the console history is cleansed by history -c them passwords will be in the console of the instance. if these were generated they would be available on the instance logs which could be argued to be a sec treat. 

How to solve it? Maybe playing with the log level on the code, if the log level is debug show as it is, otherwise hide as much as possible? forcing production systems to simply not run on debug mode?, plus warning users on the logs that log level is important?. Maybe forcing users to clear history after a private key or password is displayed for a few seconds, followed by a clearing of history plus forcing a delete of the last few log lines on the cleos.log?

**Comment by wanderingbort** [comment]
(1) and (2) above do not appear in your command history but if you are logging the session they would appear somewhere.  We will create a new issue to support writing that data to a file instead of the console.  #4554

private key import will remain in the command history, that issue is tracked here: #4409 

There shouldn't be any private keys other than any local producer keys in the `nodeos` program and we've already squelched those outputs.  If you are aware of others please re-open.  Otherwise I'm going to close this issue in favor of the task specific tracking issues
