### ISSUE TITLE
erros:  "assertion failure with message: no active bid for name" when create account

### ISSUE THREAD

**Issue by bitcodernull** [EOSIO/eos#3480]
i create account local, but i got error
"assertion failure with message: no active bid for name"

the cmd is :
"./cleos.sh create account jinmao3 jinmao41 EOS5jhCJTagZHKEpPaSzMGHynFH3cpG5qQaxetyXXWykTM9av**** EOS5jhCJTagZHKEpPaSzMGHynFH3cpG5qQaxetyXXWykTM9av**** "

would you like to tell me what's wrong?

thanks

**Comment by bitcodernull** [comment]
maybe the creator is not correct?

**Comment by moskvanaft** [comment]
Since you get this error message, you certainly have system contract installed.
System contract doesn't allows to create only one short (<12 characters) account name per 24 hours (one that got the highest bid).
If you want to just create an account (without doing bidding) - the name should be exactly 12 characters long.
