### ISSUE TITLE
--enable-stale-production should override --max-irreversible-block-age

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3487]
when the user wants to reboot a blockchain they normally boot with -e, but unless --max-irreversible-block-age is set to something greater than the "down time" it will not start producing.

Because -e only applies to the first block a node probably doesn't want --max-irreversible-block-age to be changed from its default.

**Comment by abourget** [comment]
weee! thanks :)

**Comment by wanderingbort** [comment]
We have decided to solve this slightly differently.

`--enable-stale-production` and `--max-irreversible-block-age` serve different purposes.  

When we are in a state where a network has suffered a prolonged outage we need `--max-irreversible-block-age` settings to allow _all_ producers to proceed forward for an indeterminate number of blocks to get LIB to advance (it depends on network health etc).

So, the "fix" is to properly manage the `--max-irreversible-block-age` setting properly.  However, doing so via a reboot cycle is painful.  So, we will expose that setting to the producer api plugin ( #3297 ) so that it can be managed without a reboot.

**Comment by abourget** [comment]
w00t :) that's even better, you're good man :)
