### ISSUE TITLE
cleos confusingly complains about missing content-length on server error

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#3504]
When cleos encounters, for example, a 500 (internal error) from nodeos (or potentially any proxy between it and nodeos) it prints an error about a bad Content-Length.

cleos should instead investigate the http code before looking for or parsing the content-length.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
