### ISSUE TITLE
How to get my first account on mainnet?

### ISSUE THREAD

**Issue by shawdon** [EOSIO/eos#3534]
It is exciting that the mainnet is around the corner. However, I don't how to get my first account on mainnet. On bts and steem I can do it through a faucet.
I guess the boot node will create my account according to snapshot(I have registered my eos on ethereum), right?

**Comment by shawdon** [comment]
And https://medium.com/@thomas.cox_39839/magic-15-unlocking-the-eosio-blockchain-91ec54f7b48d refer that:

> first, all tokens start off fully staked, half for CPU and half for bandwidth. And the “unstake” command won’t work until we get that 15% threshold of token holders agreeing on a top 21.

But I can't find any implements in code, is there anything I missing?

**Comment by jgiszczak** [comment]
Creation of the initial accounts and initial token conditions is being handled by code in a separate repository.  See https://github.com/EOSIO/genesis for details.

**Comment by jgiszczak** [comment]
I can not say.  The genesis repository is no longer under the rubrik of EOSIO, since the community is responsible for the snapshot and boot strapping of the main net.

Copies of the original genesis repository may now be found at:
https://github.com/EOS-Mainnet/
and
https://github.com/EOS-distribution-collective/genesis
