### ISSUE TITLE
blacklist producers

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3581]
A node should be able to blacklist producers which produce blocks which may contain an infinite loop.

In general DPOS trusts producers due to the election model, this means we trust them not to produce blocks with infinite loops and the consequences can be dealt with in arbitration / etc.  If a producer does "go bad" and attempt to bring down the network everyone else should be able to respond quickly to minimize damage by ignoring that producer.

**Comment by abourget** [comment]
Is there a way to do that without hard-forking instantly ?

**Comment by Tweicx** [comment]
WTF! a Epic bug!holy shit !!!

**Comment by taokayan** [comment]
After discussing with @arhag , this turns out to be a tricky task. Making a blacklist on the producer plugin might introduce some synchronization issue between different producers. Also making it into a contract level might result in a big delay.

**Comment by nehtechnine** [comment]
"load"reviewatom"

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
