### ISSUE TITLE
Incorrect auth check in net_plugin if allowed-connection == 'producers'

### ISSUE THREAD

**Issue by algys** [EOSIO/eos#3617]
If 'allowed-connection' param set only on 'produsers', nobody can't connect to node.
This case check here:
https://github.com/EOSIO/eos/blob/ca03c3a7db7c7177a4790eb1655e444c3ad8b9bd/plugins/net_plugin/net_plugin.cpp#L2665

`found_producer_key` obtained here:
https://github.com/EOSIO/eos/blob/ca03c3a7db7c7177a4790eb1655e444c3ad8b9bd/plugins/net_plugin/net_plugin.cpp#L2664

but method [`is_producer_key`](https://github.com/EOSIO/eos/blob/ca03c3a7db7c7177a4790eb1655e444c3ad8b9bd/plugins/producer_plugin/producer_plugin.cpp#L426) returns `true` **only** if `msg.key` is our's producer key which configured in node start config:

It seems param `allowed-connection = produsers` designed to allow any **producer** nodes(not only our`s) connect to node. If i'm right, that is bug.

**Comment by jgiszczak** [comment]
The producer_plugin list of producer keys formerly contained a list of all keys of all producers.  That is no longer the case.  Rather than attempting to repair the feature, it should be removed entirely.  Producers are extremely unlikely to be directly connected, given the preferred topologies that are emerging in the community, and even if they were, they should be using separate authentication keys anyway.
