### ISSUE TITLE
Docker issue irreversible block is too old

### ISSUE THREAD

**Issue by macsilber** [EOSIO/eos#3618]
Getting this error 
1066501ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:7719466s, max:1800s]

After running 
docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2

Even after running a docker volume rm 62f2348779b4ea12f6542a791af15ff8150cd925d48c2d79f4a766514dbd8b16

following these instructions; https://github.com/EOSIO/eos/wiki/Local-Environment#3-docker

Same occurs with:
docker run --name nodeos -v ~/Apps/eos-docker-data/:/opt/eosio/bin/data-dir -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2

**Comment by hsejin314** [comment]
same issue

**Comment by chenji-kael** [comment]
same issue

**Comment by reliefs** [comment]
same issue

**Comment by SheldonHH** [comment]
same issue

**Comment by liudliu1992** [comment]
same issue

**Comment by spartucus** [comment]
Try run nodeos with `--max-irreversible-block-age -1` option.

**Comment by prayagk** [comment]
@spartucus 
thanks. this works for me

**Comment by reliefs** [comment]
When i do 
"docker run --name nodeos -v /root/eos:/opt/eos/bin/data-dir -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2 --max-irreversible-block-age -1"

I get this error now:
1030000ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1030500ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1031000ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1031500ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1032000ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1032500ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1033000ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1033500ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1034000ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1034500ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:0s, max:-1s]
1035000

**Comment by spartucus** [comment]
Don't know much about docker, maybe update and try again?

**Comment by reliefs** [comment]
my docker is updated.

**Comment by ItsLeeOwen** [comment]
@reliefs  -1 isn't working as expected on my end either, but a higher value is working

```
--max-irreversible-block-age 99999999
```

**Comment by HeyamGreenwood** [comment]
I have the same problem but I also can't use Docker - I have a problem with installation at the moment - 

--max-irreversible-block-age 99999999 is a docker command (?)

**Comment by reliefs** [comment]
no it's a eos command

**Comment by hsejin314** [comment]
My problem was, nodeos wasn't stopped wall. so I killed all of my nodeos process then I cleaned all of blocks. then i change max irreversible block and replay again

**Comment by raymondfx** [comment]
@hsejin314 how do I clean blocks... I have this error with my nodeos 

```
474191ms thread-0   main.cpp:113                  main                 ] 10 assert_exception: Assert Exception
db.revision() >= head->block_num: fork database is inconsistent with shared memory
    {"db":0,"head":1}
    thread-0  controller.cpp:243 init

    {}
    thread-0  chain_plugin.cpp:454 plugin_startup
```

**Comment by hsejin314** [comment]
kill nodeos process, delete all blocks/, state/and then replay the chian. (./start.sh --delete-all-blocks --hard-replay-blockchain)

**Comment by taokayan** [comment]
close this because this is solved.
