### ISSUE TITLE
Investigate differences between bitshare fc and eos fc

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#3671]
check if anything beyond #3664 is needed

**Comment by brianjohnson5972** [comment]
@wanderingbort  is this still pertinent, or can it be removed?

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
