### ISSUE TITLE
the eos code doesn't operate and look like dead 

### ISSUE THREAD

**Issue by zhaokanghuiasd** [EOSIO/eos#3827]
After I use the command as following:
./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

My eos node can't produce block and it seems like dead as the following pic:
![_15281849868763 1](https://user-images.githubusercontent.com/39476994/40962967-b0065ed2-68d9-11e8-870f-5970866e1886.png)

**Comment by moskvanaft** [comment]
@zhaokanghuiasd your node is not producing because you didn't enable producer_plugin.
If you want to run blockchain on a single node, you can try something like
```
nodeos --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --contracts-console --delete-all-blocks --genesis-timestamp now -e
```
(will start blockchain from scratch every time you re-run it, if you want to continue existing chain - remove `-delete-all-blocks --genesis-timestamp now`)

**Comment by zhaokanghuiasd** [comment]
![242754046573634246](https://user-images.githubusercontent.com/39476994/41015959-2d94485a-697f-11e8-8472-866ba7a06cef.png)
@moskvanaft After using your method, it still can't build block. It even miss the final two raws at the above pic. Can you help me?? Thank you

**Comment by moskvanaft** [comment]
@zhaokanghuiasd make sure that you have following parameters in you config file (not commented out)
```
producer-name = eosio
private-key = ["<public>","<private"]
```
