### ISSUE TITLE
How to get the packed transaction

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#3913]
Like ""packed_trx": "a8eb185baa00dc3b8641000000000100a6823403ea3055000000572d3ccdcd0100a6823403ea305500000000a8ed32322200a6823403ea30550000000000ea3055a0860100000000000453595300000000016d00","

Because I try push a transaction by HTTP API.

**Comment by eosmoto** [comment]
I write a python  a python EOS tool for pack sign and net request.
you can use this like 

`pip instll eosiopy
raw = RawinputParams("transfer", {
        "from": "eosio.token",
        "memo": "dd",
        "quantity": "20.0000 EOS",
        "to": "eosio"
    }, "eosio.token", "eosio.token@active")

eosiop_arams=EosioParams(raw.eos_params)
eosiop_arams.trx_json`
[eosiopy github](https://github.com/eosmoto/eosiopy)

**Comment by egonson** [comment]
How to get packed_trx without external code?

**Comment by ismyhc** [comment]
@sergmetelin Im interested in this as well. I've written a ByteWriter class in swift based on some others I've seen online, but keep running into the "Invalid Packed Transaction" error when pushing via push_transaction to rpc. Is there anywhere that documents the requirements on how exactly to pack a transaction so that it can be written in any language?

Here is my current version.
https://gist.github.com/ismyhc/8825bb4b560b061d91289967ddff45b7

**Comment by readygo586** [comment]
@yankunsam  As I know, there are 2 ways to get out packed_trx 
1. use _cleos convert pack_transaction_ ‘{JSON format trans } ’ , please refer cleos -h for more info
2. Rewrite the _packed_ function by yourself

**Comment by yankunsam** [comment]
@readygo586  Thanks for your reply. I think if eos supply this RPC, it will be better.

**Comment by andriantolie** [comment]
Yes, as @readygo586 said, you can use `cleos convert pack_transaction`
