### ISSUE TITLE
How can I create account using REST API?

### ISSUE THREAD

**Issue by fcsd** [EOSIO/eos#3940]
Hi! I got a problem. I need to create account using REST API. How can I do it?

**Comment by forfrt** [comment]
I found no way but using `cleos` to create account. Be aware that you should apend the option `--wallet-url` like `--wallet-url http://localhost:8888`, so the command is like:

```
cleos --wallet-url http://localhost:8888 create account eosio investor EOS6eTCvPqJc9MhaNdTWAWUL7raiPD8uKDrnhN9fYwsBCKMAFyUsj EOS6eTCvPqJc9MhaNdTWAWUL7raiPD8uKDrnhN9fYwsBCKMAFyUsj
```

It is because that command `cleos` and `curl` would use totally different wallet dir even with the same configuration file, which is ugly and cost tons of time and my splendid hair. Please fix it.

BTW, the RPC document is out of date especially for the push transaction section. See [issue 2295](https://github.com/EOSIO/eos/issues/2295) for details.

**Comment by fcsd** [comment]
I can`t use cleos to integrate this case on mobile development :(

**Comment by forfrt** [comment]
@fcsd then I wish you good luck to find the latest version of RPC document. I think they have this interface but forgot to keep the document updated.

**Comment by jgiszczak** [comment]
EOS.IO RPC is not strictly REST, but see https://github.com/EOSIO/eosjs for a complete implementation of a Javascript library using EOS.IO RPC, including account creation.

Note that there were a great many changes leading up to the release, so careful attention must be paid to the version compatibility table in the README.
