### ISSUE TITLE
Lost reference to entry within multi-index through `get` and `modify`.

### ISSUE THREAD

**Issue by iwasaki-kenta** [EOSIO/eos#4011]
Noticed this during the EOS HK Hackathon.

# Setup

Define multi-index for struct `Account`:

```cpp
//@abi table ledger i64
struct Account {
    account_name owner;
    uint64_t balance = 0;

    int64_t relaying = -1;
    string relayAddress;

    uint64_t primary_key() const {
        return owner;
    }

    EOSLIB_SERIALIZE(Account, (owner)(balance)(relaying)(relayAddress))
};

typedef multi_index<N(ledger), Account> accounts_index;
accounts_index accounts;
```

# Problem

Defining a constant variable `acc` whose value is successfully obtained from the `accounts` multi-index:

```cpp
accounts.get(account_name name, "Message to be reported on failure");
```

and providing it as a reference parameter to be modified by calling:

```cpp
accounts.modify(acc, _self, [&](Account & ref) { ... });
```
causes an exception where the data entry represented by `acc` does not seem to exist within the `accounts` multi-index.

This is remedied by calling `get` again and passing it as a reference to `accounts.modify` like so:

```cpp
accounts.modify(accounts.get(account_name name, "Won't fail"), _self, [&](Account & ref) { ... });
```

**Comment by arhag** [comment]
What is the error message?

Are both `accounts` variables the exact same `multi_index` instance? If not, you would see an error message like "object passed to modify is not in multi_index".

**Comment by iwasaki-kenta** [comment]
Both `accounts` variables are definitely the exact same multi-index instance, and yes; the error is: `object passed to modify is not in multi_index`.

**Comment by arhag** [comment]
Can you provide a full contract example that demonstrates this issue?

**Comment by iwasaki-kenta** [comment]
Here's an example contract I did for the hackathon w/ the exact case.

https://github.com/iwasaki-kenta/blockflare-contract/blob/63724ed906eb7fabd73753411115c3bc353e08b1/src/blockflare.cpp#L146

**Comment by arhag** [comment]
@iwasaki-kenta:

The `multi_index::get` returns a const reference to the type. So when you use `auto` on line 146, you create a stack-allocated object of type `Account` which is then copy assigned to the value that `multi_index::get` returns a reference of. And that stack-allocated object does not contain the metadata needed for `multi_index` to know which object in the native-side persistent data store to modify.

You should be using `const auto& account = accounts.get(relayer, "Cannot create account for some odd reason.");` instead. Or alternatively, `decltype(auto) account = ...`. There are other places in your contract code where similar changes need to be made.

Alternatively, you can use `find` instead of `get` and get back a well-typed `multi_index::const_iterator`. That way you don't have to worry about a typo (missing ampersand on `auto`) since a copied `const_iterator` can still be legitimately passed into `multi_index::modify` or `multi_index::erase`. 

While the check in `multi_index` which throws the `object passed to modify is not in multi_index` error does attempt to protect against these sorts of mistakes, that check can only occur at run-time which means the mistake may go unnoticed unless some corner cases of your contract are triggered in tests. By using `find` and `const_iterator` instead, those kinds of mistakes can be avoided or caught at compile-time.
