### ISSUE TITLE
Regression with get table producers

### ISSUE THREAD

**Issue by pete001** [EOSIO/eos#4025]
In the following `cleos` call:

```
cleos.sh get table eosio eosio producers
```

We used to receive a `last_produced_block` attribute in the json, which was incredibly helpful to us in regards to implementing producer failover strategies. We had a bash script like this: 

```
TIMESTAMP="$(./cleos.sh get table eosio eosio producers -l 150 | grep blockmatrix1 -A 8 | grep last_produced_block | cut -d':' -f2)"
DATE = date --date "@$((($TIMESTAMP * 500 + 946684800000) / 1000))"
```

This would allow us to determine whether our producer had fallen behind 2 minutes 6 seconds, and we could automatically switch to a backup producer (using a different signing key) via `regproducer`.

Without the `last_produced_block` attribute we are left with 2 options. Implement a stateful check against the `unpaid_blocks` attribute, or to parse logs on the active producer. Neither of these are ideal, and requires a lot more boilerplate to implement a solid failover strategy. 

Could this attribute be reinstated, or is there a recommendation for a more reliable method to detect producer failure?

**Comment by ankh2054** [comment]
+1 I’ve go a similar python script doing a check on the field.

**Comment by jchung00** [comment]
Agreed, this would be a great feature for failover.

**Comment by wanderingbort** [comment]
We can restore that tracking in our reference implementation however, this will not necessarily trigger an upgrade of any active chain out there in world.

**Comment by tbfleming** [comment]
For reference: this was removed in https://github.com/EOSIO/eos/commit/8d0417fd8a575220b0b0f1a16e7ceef5d348f174

**Comment by arhag** [comment]
I think contract developers should generally follow a principle of not including additional data in consensus state (i.e. EOSIO persistent state which contracts have access to) than what is needed for the operation of those smart contracts. 

When we start violating that principle we open ourselves to slowly justifying inclusion of all kinds of metadata that would be useful for some application or service but that serves no purpose to the smart contract itself. And all this additional data would need to be covered by the EOSIO RAM which due to its scarcity is typically expected to be quite expensive compared to alternative places this metadata could be stored.

In my opinion this metadata should either be tracked in custom-built plugins that can be loaded into a nodeos API node, or alternatively a service can derive the metadata using the logged and indexed data from a general purpose indexing plugin (e.g. the mongodb plugin that we are adding back in a near future release). This approach allows the plugins/services to be easily updated to track other metadata that can be derived from blockchain data and/or transaction side-effects without requiring the much more difficult process of, for example, upgrading a contract on a live blockchain.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
