### ISSUE TITLE
bidname is not closing after 24 hours

### ISSUE THREAD

**Issue by alienzin** [EOSIO/eos#4029]
In current EOS mainnet, it is possible to bid on a previous bid which had been passed more than 24 hours.
So bidname is not closing.

Is this feature going to work after the chain is activated (over 15% voting) ?

**Comment by arhag** [comment]
It will start working 2 weeks after activation. This is by design to give users enough time to learn how to use the tools, unstake some of their tokens so that they can be liquid for bidding, and allow fair participation in the bidding process so that technically sophisticated name squatters don't get an advantage over everyone else. 

And even after the feature has been activated, only the name with the highest bid will close each day (assuming it has been more than 24 hours since the last bid on that name).

**Comment by egonson** [comment]
Is the bidding done now useless?

**Comment by arhag** [comment]
@egonson: I wouldn't say it is completely useless. There just isn't any rush until 2 weeks after the 15% threshold has been reached.

It won't matter if you bid on a name now or, for example, 13 days after the 15% activation threshold is reached, except that if you vote now you might unnecessarily lock up your limited liquid tokens in a bid preventing it from being used for other purposes (like other bids or creating new accounts). So in that sense I guess it is a little foolish to bid now rather than waiting for later when you have more information available to decide what to do with your tokens.

**Comment by andresberrios** [comment]
This is for a different reason, but also involves auctions not closing after 24 hours when in this case they actually should have: https://github.com/EOSIO/eos/pull/4849
