### ISSUE TITLE
why not buyram quant always less than 200,Batch execution,There will be no cost?

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#4051]
void system_contract::buyram( account_name payer, account_name receiver, asset quant )
   {
      require_auth( payer );
      eosio_assert( quant.amount > 0, "must purchase a positive amount" );

      auto fee = quant;
      fee.amount /= 200; /// .5% fee

**Comment by arhag** [comment]
Yup, with that old code in place, buying RAM in increments smaller than 0.0200 EOS would effectively not have a 0.5% trading fee. On the other hand, any user who wants to buy up a lot of RAM would burn through a lot of CPU and network bandwidth if they were to split up the RAM purchase into many many transactions each buying up small amounts of RAM. So in the end, it may or may not actually be worth it.

That said, it is clearly better if the fee was rounded up so that everyone that buys RAM pays a non-zero fee. Which is what the system contract code now does with the changes in PR #4109.

Thanks.

**Comment by OracleChain** [comment]
no thanks,
please vote for bp `oraclegogogo`
