### ISSUE TITLE
Throw unexpected fails in apply_block - revisit

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#4159]
#4158 quick fix needs unittests. Also determine why existing unittests that push blocks to copy of chain did not catch this.

#4158 bug fix highlights that our determination of delayed/deferred transactions is subtle. transaction_receipt trx variant contains a transaction_id_type for delayed/deferred transactions. Add a method to transaction_receipt which provides clear indication of delayed/deferred. Note that the structure of transaction_receipt can't easily change as it is part of the signed_block.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
