### ISSUE TITLE
eosiocpp script is broken

### ISSUE THREAD

**Issue by littlekfc** [EOSIO/eos#4165]
It seems that eosiocpp script did not work now. It can not find contract location.

`eosiocpp -o exchange.wast exchange.cpp 

In file included from exchange.cpp:2:
./exchange.hpp:5:10: fatal error: 'exchange/market_state.hpp' file not found
#include <exchange/market_state.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`

**Comment by andriantolie** [comment]
You can't use eosiocpp to compile smart contracts inside the `contracts/` folders. It's because you don't have the `contracts/` folder in your include path.

The way the smart contracts inside `contracts/` folder compiled now is by using cmake. Notice that inside the smart contract CMakeLists.txt, ${STANDARD_INCLUDE_FOLDERS} is added as the INCLUDE_FOLDERS, that's why it can detect the #include <xxx/xxx.hpp> files. If you want to use eosiocpp to compile smart contracts inside `contracts` folder, you can use relative path instead (i.e. `#include "xxx.hpp"` instead of `#include <xxx/xxx.hpp>`)
