### ISSUE TITLE
are the net and cpu limits have something to do with users?

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4264]
I am not sure whether the net and cpu limits are statistic of one action call or total action calls? So, shall I add net and cpu if I get more users using my contract?

**Comment by xiaoshuyu** [comment]
mute the thread






At 2018-06-21 14:24:52, "Konquer your Mind" <notifications@github.com> wrote:


I am not sure whether the net and cpu limits are statistic of one action call or total action calls? So, shall I add net and cpu if I get more users using my contract?

**Comment by jgiszczak** [comment]
@xiaoshuyu There does not appear to be a way to mute Github threads via email.  Use the web interface, view the issue, and click the "Unsubscribe" button in the right column.

**Comment by jgiszczak** [comment]
Net and CPU limits are a function both of your own activity and the activity of the network as a whole.  You may need to stake more net and CPU time for your contract even if your own activity does not go up.  Activity on the rest of the net could reduce availability to such an extent that you are crowded out.  This is not likely to be an issue soon, but it is possible.  Otherwise, yes, the more transactions you want to conduct, the more net and CPU you need to stake.
