### ISSUE TITLE
Add support to enable setting up test net with 3 BPs 

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#4277]
It seems the number of BPs (21) is hardcoded in the code. How about make it a configurable compilation parameter so that a simple test net with 3 or 5 or 7 etc. total BPs can be setup? Would b1 merge the changes if it is  implemented?

**Comment by jgiszczak** [comment]
It's possible to run a consensus testnet using fewer than 21 producers already.  21 is an upper limit rather than a minimum.  In eosio.bios testnets, `setprods` can be fewer than 21 and as long as 2/3+1 of those producers are making blocks, the last irreversible block will advance.  In eosio.system testnets, it's possible to `regproducer` and vote for fewer than 21 and LIB will similarly advance if enough of them are producing.  When bootstrapping, there's only one producer, `eosio`, and LIB advances with it.
