### ISSUE TITLE
symbol list

### ISSUE THREAD

**Issue by AdamBylin** [EOSIO/eos#4337]
How can i get my own symbol list ？ 

I had try this  but only eos return, 

account "gy4dkmjzhege "symbollist  is  [EOS, EOSDAC] not just eos

what mistake i make?

=>rqst
https://api-halo.eosasia.one/v1/chain/get_table_rows {"json":true,"code":"eosio.token","scope":"gy4dkmjzhege","table":"accounts","limit":10}: 
=>rspd
{"rows":[{"balance":"76.6987 EOS"}],"more":false}

**Comment by jungrammer** [comment]
If you want to know the number of EOSDAC tokens

https://api-halo.eosasia.one/v1/chain/get_table_rows {"json":true,"code":"eosdactokens","scope":"gy4dkmjzhege","table":"accounts","limit":10}:

If I know the `code` for each token like this, (eos; eosio.token, eosdac; eosdactokens ....)
I would like to be provided with an API that allows me to know the token code and amount of tokens I have in only one http api call.

**Comment by jgiszczak** [comment]
It is not possible to retrieve all possible tokens in the system in an http API call.  The number of possible different tokens is limited only by the total number of accounts in the system, and whether or not any one of those accounts is hosting an instance of a token contract can vary from second to second.  Nor is it guaranteed that the token contracts are all identical.  The table name is not required to be 'accounts'.

It is inappropriate to hard code an http API for contract details that may change.  That's why the generic accessors exist.
