### ISSUE TITLE
ABI Serialization: shortcut for extended_asset

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#4338]
Support "1.2345 FOO@contract"

**Comment by conr2d** [comment]
@wanderingbort Do you have a plan to merge #6001 again? If there is a point to be modified, please let me know. If not suitable, keep it reverted. :)

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
