### ISSUE TITLE
cleos does not track multiple stakes

### ISSUE THREAD

**Issue by michaeljyeates** [EOSIO/eos#4449]
Account : eosdacserver
Block height : 3761844

I staked in the following order

stake 5000 cpu and 500 net
unstake 5000 cpu and 500 net

stake 3 more times because the account was over its cpu limit

Now cleos does not show the staked balances and they are missing from the total

```
EOS balances: 
     liquid:         5070.2255 EOS
     staked:           10.2000 EOS
     unstaking:      5500.0000 EOS
     total:         10580.4255 EOS
```

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
