### ISSUE TITLE
reclaim the last ram of an account

### ISSUE THREAD

**Issue by bitrocks** [EOSIO/eos#4452]
If I want to delete an account, can I reclaim the 4kb (necessary for the account) by some function like `relaim_account_resource(account_a, account_b)`, which delete account_a, and forward resource to account_b.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
