### ISSUE TITLE
#include <sys/mman.h> not found

### ISSUE THREAD

**Issue by tacc716** [EOSIO/eos#4466]
I was trying to do  something strange but i'm unable to include sys/mman.h file . When compiling with this header file i got error file not found. Can somebody help me ??

**Comment by jgiszczak** [comment]
Generally speaking if it's not part of the C or C++ standard libraries, the header is not available.  In the case of mman.h, it will not be available because nothing in it is useful in the context of a contract.  Memory mapped files are not allowed because using them can have nondeterministic results.  Contracts are not allowed access to the filesystem, the network, or to real time clocks.
