### ISSUE TITLE
eosiolib: extended_symbol inheriting from symbol_type creates hazards

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#4525]
```
struct extended_symbol : public symbol_type
```

This causes `extended_symbol` to inherit inappropriate behavior from `symbol_type`. e.g. `operator<` created a vulnerability inside exchange since it fails to compare the `contract` member.

`symbol_type` didn't define `operator<` directly. Instead it came through an implicit conversion operator.

There should probably be an audit of all types in eosiolib for:
* Types with inappropriate base classes. A base is inappropriate when operations on the base aren't compatible with the derived type and the involved functions aren't virtual. e.g. comparison operators.
* Implicit conversion operators and implicit single-argument constructors. They're handy, but they sometimes lead to incorrect code.

**Comment by tbfleming** [comment]
Here's chain's definition of this, which doesn't have this issue:

```
struct extended_symbol {
   symbol       sym;
   account_name contract;
};
```

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
