### ISSUE TITLE
Could the "get table" command is restricted to someone that is authorized to access only?

### ISSUE THREAD

**Issue by liliyongleo** [EOSIO/eos#4544]
For now, all the "Get table" command is open to everyone.  can it be configured to restrict to someone only that is authorized to do so? Thanks.

**Comment by taokayan** [comment]
Technically we can add the restriction to the source code, but it doesn't mean that everyone will apply the new code with the restrictions. Since the contexts of the table exist in every node including the non-producing node, they're technically seen everywhere. Therefore, it's not a much helpful to implement this. Alternatively, you can encrypt the data before storing them into the table.
