### ISSUE TITLE
Why I can't unlock wallet by RPC

### ISSUE THREAD

**Issue by vincentwang0736** [EOSIO/eos#4585]
I have created a wallet named "mtcreator". I can unlock this wallet by cmd:cleos, such like this:

> # ./cleos wallet unlock -n mtwallet --password PW5KLSh7x7qvRcbqHXV2vQ4twQYxvaJusLCK5feyqS473XoBRh41T
And I got this right result:

> Unlocked: mtwallet

But when I unlock it by rpc:

> # curl http://127.0.0.1:8888/v1/wallet/unlock -X POST -d '["mtwallet","PW5KLSh7x7qvRcbqHXV2vQ4twQYxvaJusLCK5feyqS473XoBRh41T"]'

I got this exception:

> {"code":500,"message":"Internal Service Error","error":{"code":3120002,"name":"wallet_nonexistent_exception","what":"Nonexistent wallet","details":[]}}

Anyone can help me? thanks a lot!

**Comment by tugmaks** [comment]
I have same problem(

**Comment by andriantolie** [comment]
Your wallet is running on 8900 by default

Try this one instead `curl http://127.0.0.1:8900/v1/wallet/unlock -X POST -d '["mtwallet","PW5KLSh7x7qvRcbqHXV2vQ4twQYxvaJusLCK5feyqS473XoBRh41T"]'`

**Comment by vincentwang0736** [comment]
Thanks a lot!
But I got "curl: (7) Failed to connect to 127.0.0.1 port 8900: Connection refused"
could you please tell me where i can setup the prot of wallet?

**Comment by andriantolie** [comment]
This is actually what's happening.
When you start cleos and you don't have keosd running, cleos will automatically start keosd running on port 8900 for you (`/usr/local/bin/keosd --http-server-address=127.0.0.1:8900`)

You got the above error message, likely caused by the fact that you don't have keosd running yet. Try to start keosd first and specify the port in `--http-server-address` param
