### ISSUE TITLE
http-server-address = 0.0.0.0:8888 not working!

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#4607]
i'm setting ip as 0.0.0.0 to access from external.
But, nodeos recognize that ip as '0.0.0.0' not *

so,  If I run "curl 0.0.0.0:8888", returns something,
but, "curl my_public_ip:8888" returns nothing.

**Comment by andriantolie** [comment]
Do you have firewall/ security restriction to that port 8888?

**Comment by wanderingbort** [comment]
We do have a bug where the 0.0.0.0 address expects the host 0.0.0.0 at an
HTTP Host level.  This can be worked around using the 'http-alias' config
to add host names and specific ips (you will need the port too if it's not
the standard http(s) ports.

I will link the issue here to track the resolution of 0.0.0.0 addresses

**Comment by Vamsikesav** [comment]
try http://localhost:8888
