### ISSUE TITLE
Can't find genesis-json field in config.ini

### ISSUE THREAD

**Issue by dksuper** [EOSIO/eos#4612]
I build up the eos v1.0.0 , but when go "~/.local/share/eosio/nodeos/config" to check the config file, i can't see the genesis-json field , the follow is my config file:

![image](https://user-images.githubusercontent.com/35549846/42627781-9d924eac-8600-11e8-892f-2dfa8c9bd568.png)
![image](https://user-images.githubusercontent.com/35549846/42627829-bd9236c2-8600-11e8-861b-12a320c5cb35.png)
![image](https://user-images.githubusercontent.com/35549846/42627845-d0d7d214-8600-11e8-9739-e1feb79c0136.png)
![image](https://user-images.githubusercontent.com/35549846/42627862-dbd4cdde-8600-11e8-8b7b-94f6bc6e8d4a.png)

Am I doing something wrong?

**Comment by jgiszczak** [comment]
`genesis-json` is no longer supported as a config.ini setting.  It is only available on the command line since it is only used once, when starting a new chain.  Subsequent runs of nodeos for the same chain require the argument to be absent.  If you're running a local testnet node, you may omit the argument entirely and all default values will be used.
