### ISSUE TITLE
cannot use jsoncpp array append in smart contract

### ISSUE THREAD

**Issue by hzou123** [EOSIO/eos#4723]
smart contract api is generated, but it falied when i set to to account.

code: 
        Json::Value arrayObj;   
        arrayObj.append(new_item);  

The error is 

2900127ms thread-0   main.cpp:2658                 main                 ] Failed with error: Assert Exception (10)
!"unresolvable": env._ZN4Json5Value6appendERKS0_

**Comment by jgiszczak** [comment]
When using libraries not included in eosiolib, you must statically link them into your contract.  Note this could result in extremely large contract sizes, so it may not be reasonable to use the desired library.

It's recommended that you set up your contract and its dependent library to be built with CMake the way the system and sample contracts are, since the library must be rebuilt in WASM in a form suitable for linking with your contract.  Setting it up in CMake in your eos source tree allows you to take advantage of the existing infrastructure to accomplish that task.  See `CMakeModules/wasm.cmake` for the definition of WASM_COMMAND, which compiles source files into contract linkable form.

**Comment by sulier2684** [comment]
are you success?in the wasm.cmake ,apend the commond "-ljson" or others,can you tell the detail?thanks!
