### ISSUE TITLE
how to run eosiocpp? No clear instructions

### ISSUE THREAD

**Issue by vijaytabhatt** [EOSIO/eos#4785]
I am using docker to build EOS , i had first build it using 

> docker build . -t eosio/eos 

but then i came to know that it does not include eosiocpp , so i then build 

> docker build . -t eosio/eos-dev
i am able to run keos and nodeos using 

> docker-compose up -d
but how to do i run eosiocpp to compile contracts? all the command either say eosiocpp does not exist or it is not a command , i tried solutions mentioned other ways but did not work.
please explain me if i am missing anything

**Comment by andriantolie** [comment]
The eosiocpp resides in your docker container, so you need to use docker exec for it. e.g.
`docker exec eosio eosiocpp -g <your_resulting_file.wast> <your_source_file_inside_your_docker_container>`. Please remember that you need to put your source file inside your docker container first.

For convenience, you can also alias the above command, i.e. `alias eosiocpp='docker exec eosio eosiocpp'`

**Comment by vijaytabhatt** [comment]
@andriantolie thanks for the reply  , so i did a fresh install of docker and got eosiocpp to work!! but now 2 issues
1) when i run eosio using

> sudo docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"

the eosio starts but http://localhost:8888/v1/chain/get_info does not give any output

Also i am able to create wallets successfully using 

> cleos wallet create -n testwallet  
, but when i run cleos wallet list it is empty  , is there some problem with keosd?

![error](https://user-images.githubusercontent.com/15885775/43060425-8482e6f8-8e6e-11e8-8bed-3e4d80a996fc.png)

**Comment by andriantolie** [comment]
Hey @vijaytabhatt 
1. v1.1.0 introduces http header validation, if the host header sent by the http request does not match the http-server-address defined by nodeos, it will throw an error. That's why if you put http://0.0.0.0:8888/v1/chain/get_info, it will work. To make it work with localhost, add `--http-alias=localhost:8888` arg to your nodeos.

2. Yeah, I noticed this today, docker exec with -t stops the automatically created keosd after the command finish execution. Since you have enabled wallet_api_plugin for your nodeos, you can use nodeos as the wallet, try to specify the wallet url inside your cleos: `alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'`

**Comment by vijaytabhatt** [comment]
@andriantolie  1 and 2 both worked !! thanks a ton

**Comment by vijaytabhatt** [comment]
@andriantolie  i am now trying to run hello smart contract , created a filed called hello.cpp but when i run it using

> eosiocpp -o hello.wasm hello.cpp

i get error
clang-4.0: error: no such file or directory: 'hello.cpp'
clang-4.0: error: no input files

**Comment by vijaytabhatt** [comment]
sorry duplicate issue https://github.com/EOSIO/eos/issues/4105
