### ISSUE TITLE
Inconsistent behavior on wallet

### ISSUE THREAD

**Issue by arkxu** [EOSIO/eos#4792]
This is my first try out of this project, the documentation seems a little bumpy to get it running in containers but I finally get it to work. 

The issue I have relates to the wallet. I can not import key into it. I am not even sure if the wallet exists or not. Here we go:

```
$ cleos wallet list
"/opt/eosio/bin/keosd" launched
Wallets:
[]
```

it seems there is no wallet. so I am going to create one:

```
$ cleos wallet create -n default
"/opt/eosio/bin/keosd" launched
Error 3120001: Wallet already exists
Try to use different wallet name.
```

it shows the wallet exists. hm.... try to open it

```
$ cleos wallet open -n default
"/opt/eosio/bin/keosd" launched
Opened: default
```

so it does exists! Let's import the key

```
$ cleos wallet import -n default
"/opt/eosio/bin/keosd" launched
private key: Error 3120002: Nonexistent wallet
Are you sure you typed the wallet name correctly?
```

REALLY???

**Comment by andriantolie** [comment]
After you opened it, you need to unlock it first

**Comment by arkxu** [comment]
`alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888'`

**Comment by andriantolie** [comment]
Seems like `-t` option (pseudo-tty) of `docker exec` will stop the automatically started `keosd` by the end of the execution.

I guess you are following this guide to start your nodeos https://developers.eos.io/eosio-nodeos/docs/docker-quickstart? In that case, since the wallet_api_plugin is enabled for nodeos you can just use nodeos as your wallet, i.e.
`alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'` instead of starting another keosd process inside your docker container

**Comment by arkxu** [comment]
awesome! thanks @andriantolie
