### ISSUE TITLE
Create an automated suite test with compiler checks

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#4816]
Create a nightly build/test with lib_c++ debug library and as many compiler debug checks enabled as possible.

https://clang.llvm.org/docs/SafeStack.html
https://blog.quarkslab.com/clang-hardening-cheat-sheet.html

Also investigate enabling safestack in all builds if overhead is as little as indicated.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
