### ISSUE TITLE
Why does not push_transaction(rpc) receive json type transaction?

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#4826]
'cleos push transaction' can receive the json type transaction as input.
But push_transaction rpc can't.
"error":{"code":3010010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[]}

I found push_transaction needs packed_trx input and that can be generated by eosjs library.

My question is that

"Is there a plan to have push_transaction rpc receive the json type transaction as input?"
and if so, when?

**Comment by jgiszczak** [comment]
The RPC push_transaction interface once accepted JSON transactions.  That functionality was removed, at least partially for performance reasons.  Marshalling and unmarshalling JSON is relatively expensive in CPU time, putting unnecessary limits on transaction execution time.

Since it was removed, that functionality is unlikely to be restored.  The existing two step process to first pack and then submit a transaction will remain.

**Comment by egonson** [comment]
I wrote an eos java library that generates packed_trx used in push_transaction. 
https://github.com/egonson/eosjpacker
Anybody can use it for free.
