### ISSUE TITLE
What are the possible reasons for "Error 3080006: Transaction took too long" for a push action (Mainnet)?

### ISSUE THREAD

**Issue by eosbutton** [EOSIO/eos#4856]
I have a contract on mainnet. I estimated my action to take around 2 to 3 seconds, but it still gives me the same error even I set the flag "-x 3600".
Does anyone know what are the possible reasons?

**Comment by jgiszczak** [comment]
Transaction expiration time is the time the transaction can sit in a work queue waiting to be incorporated into a block before expiring.  If the network is very busy, transactions can expire before a producer gets to them.  It does not affect the deadline required for an action to complete.

Mainnet is configured to limit the maximum transaction CPU time to 150000 microseconds.  You will need to split the required work into smaller batches in order to complete it.
