### ISSUE TITLE
get

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#4881]

**Comment by csquan** [comment]
can anyone could help?

**Comment by shalomz** [comment]
Are you running this for the same account, or for different accounts? If you're running for different accounts, it is expected to return different results.

**Comment by csquan** [comment]
same account ,I am sure

**Comment by shalomz** [comment]
Let me check as well. Will get back to you in a while

**Comment by brianjohnson5972** [comment]
I think you are running into the time limit.  There should be a flag that is in the json object indicating there are more messages, and then you need to repeat your request with something like:
int start_num = <last received> + 1;
int num_entries = 1000
get actions accountname start_num num_entries

And the reason that I think the list is different is because that account has been involved in new actions, so sequence number 0 (and possibly more) is different.

**Comment by csquan** [comment]
yes,as you say,when i run comannd get actions accountname start_num num_entries,I got different results,that confuse me .It doesn't work.
