### ISSUE TITLE
What does wallet apis of HTTP API work for?

### ISSUE THREAD

**Issue by maodaishan** [EOSIO/eos#4896]
At https://developers.eos.io/eosio-nodeos/reference#wallet_create
I find HTTP API contains many wallet APIs, like wallet/create,import_key,etc.
I wonder why supply these APIs? wallet should be maintained locally, so it doesn't make sense to supply these HTTP APIs.
If I'm wrong, please help correct me, thanks.

**Comment by jgiszczak** [comment]
`keosd` is provided as a sample wallet service.  It's a web-based service because everything is.  Large numbers of developers understand how to interact with such services.  `keosd` was designed to behave analogously to `ssh-agent` or `pageant`.  That architecture is not mandatory.  `cleos` could be written to read and write `.wallet` files directly, for example.  It just wasn't.
