### ISSUE TITLE
Error 3070000: WASM Exception While using eosio.token in own contract

### ISSUE THREAD

**Issue by devgg** [EOSIO/eos#4907]
Hi I would like to use the eosio.token contract in my own contract but get a wasm exception when I try to call `transfer()`.

```cpp
#include "../eosio.token/eosio.token.hpp"

void request::create(const account_name& requester, const account_name& requestee,
                     uint64_t tokens) {
  // works fine
  eosio::token t(N(vol.token));
  eosio::asset asset = t.get_balance(requester, volean::get_symbol());
  // throws the WASM Exception
  t.transfer(requester, requestee, asset, "");
```

```
cleos set contract ...
Assembling WASM...
Publishing contract...
Error 3070000: WASM Exception
```

Any idea on how I can fix this? I could copy the code for transfer and execute it myself but this seems less than optimal.

Thanks a lot!

**Comment by jgiszczak** [comment]
You must either copy the token code or dispatch an inline action to the eosio.token contract.  Use the `SEND_INLINE_ACTION` macro provided by eosiolib.  Note that you may have permissions problems to work through.  If you're attempting to transfer tokens from an account you don't actually own, those permissions problems are unsolvable.

`#include "../eosio.token/eosio.token.hpp"` does not actually work as intended since there's no corresponding linking of the eosio.token object code into your contract, unlike eosiolib.  Nor are the existing CMake scripts set up for that.  You would likely have to make substantial modifications to your contract's CMakeLists.txt to make it work.  Not impossible, but copying eosio.token's code into your own contract is considerably easier.

The idiomatic solution is an inline action.

**Comment by devgg** [comment]
Just to clarify: Do I have a way of knowing if the inline function succeeds?

**Comment by jgiszczak** [comment]
Yes, if the inline action fails, for lack of authorization or other reason, the transaction which generated it will fail on the spot.  Inline actions are all-or-nothing with respect to the contract action which triggered them.
