### ISSUE TITLE
Connecting To one Nodeos using two cleos in the same network

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#4959]
If i have a private node running in my pc how others can connect to the same is there any way in EOS to add peers or something similar.

**Comment by jgiszczak** [comment]
To allow others to access a node on your machine using cleos, in `~/.local/share/eosio/nodeos/config/config.ini` change `http-server-address = 127.0.0.1:8888` to `http-server-address = 0.0.0.0:8888` and restart nodeos.  This change has nodeos listen on all interfaces of the machine, including public interfaces, rather than solely localhost.

If you're accessing the nodeos machine using a DNS name, you may need to add matching `http-alias = ` lines to that same `config.ini`.

**Comment by hasnat98044** [comment]
how can we change the host for nodeos? For example my nodeos is running on the azure server and now I want to connect it to my project. How can I do that. I have already given the default host and port that 127.0.0.1:8888. how to do this.
