### ISSUE TITLE
Failed to connect to nodeos at http://127.0.0.1:8888; is nodeos running?but node is runing and port is listening..

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5041]
I had upgrade eos to 1.1.0 version ande run it,when i run command it remind me failed to connect to nodeos at http://127.0.0.1:8888; is nodeos running?but eos is running and 8888 port is listening..
I rember when run eos version 1.0.7 ,there is no above problem....anyone help me?

**Comment by csquan** [comment]
my config.ini port is 8888 ,netstat -anp|grep 8888 is right,find 8888 is listening....so,why?

**Comment by csquan** [comment]
I have created about 20000 accounts,then eos remind me  failed to connect to nodeos at http://127.0.0.1:8888; is nodeos running？I don‘t know why...is a bug?

**Comment by jgiszczak** [comment]
Is your OS kernel not cleaning up closed sockets quickly enough?  Show `nodeos` log output around the time of the `cleos` connection failure.

**Comment by navneetboghani** [comment]
any solution for that i have also get same error

**Comment by jgiszczak** [comment]
@csquan never answered my question, so no, there is no solution for his reported problem.

@navneetboghani For your problem, you'll need to be far more detailed if you want help.  The error message is always correct.  When `cleos` is unable to connect and reports that error, nodeos is either not running at all or is running on an unexpected port number.

**Comment by Tusharsb** [comment]
**Diagnose of problem**
The `nodeos` process inside my `eosio` container was running on port 7777 rather than on 8888 (i verified this using `netstat -nlp` command`, but for that i had to first run `apt-get update` and `apt-get install net-tools` inside the docker container)

**Solution**
I opened the `.bashrc` file of my host machine and changed
`alias cleos='docker exec -it eosio /opt/eosio/bin/cleos  --wallet-url http://127.0.0.1:5555'`
to rather 
`alias cleos='docker exec -it eosio /opt/eosio/bin/cleos  --wallet-url http://127.0.0.1:5555 --url http://127.0.0.1:7777'`

**Comment by dixia** [comment]
Closed as it is answered. please to go EOSIO stack exchange for this kind of question
