### ISSUE TITLE
Important scale request

### ISSUE THREAD

**Issue by dacom-dark-sun** [EOSIO/eos#5079]
Hello. 
Soft EOSIO has some technical complexity of scaling, which it is desirable to eliminate. In particular, in the eosjs-ecc library, the prefix "EOS" is hard-coded, which stay reason for fork of the library and creates some limitations for adding fork-chains to applications such as Scatter. 

The second technical problem, which is also relatively easy to remove, is in the FC module, where the prefix "EOS" is also hard-coded. This also causes the fork of the module only for change the prefix.

Both the first and second problems stand in the way of scaling, since they require certain skills in working with the blockchains. If in BitShares and Steem everything was simple (modification in one file), then in EOSIO, despite the fact that it was created for forks, to do forks is problematic.

For elimination, it suffices to transfer the definition of the prefix from the module FС to CMAKELIST and in library eosjc-ecc to config. I hope this problem will be solved, otherwise libraries will have a lot of unnecessary forks and developers will spend time to fix it, otherwise focus on develop. 

Thanks.

**Comment by lazaridiscom** [comment]
@tbfleming , as a general rule, nothing should be hardcoded, in order to ensure easy cloning/forking/branding, and thus adoption, and thus **scaling** (of the userbase), to use the term of the O).

Your comment could be placed in the relevant configuration file, just a dummy example:

```cpp

// The EOS prefix identifies the key format. If you change it then you make it more 
// difficult for users to port keys between compatible chains.
#define KEYFORMAT EOS
```

Ideally, the whole EOSIO software ecosystem would be configure in one central file, like `branding.cfg`. Recompile, and you have a whole new product.

**Comment by tbfleming** [comment]
The eosio codebase is for running and connecting to eosio-compatible chains. Making the K1 prefix configurable doesn’t aid that goal.

**Comment by tbfleming** [comment]
I was just reminded that the EOS key and signature prefix is for the legacy format. The legacy format will always remain a valid input, but nodeos and libraries will eventually start using the newer format on output. The newer format has a different prefix and a different encoding.

**Comment by lazaridiscom** [comment]
@dacom-dark-sun , without me knowing the full technical background, I think that you have a valid point, simply because a code-base like EOS should be highly flexible, to allow simple adoption (and forking) even in use-cases that the original developers/managers cannot see.

The standard-procedure is anyway to avoid hard-coding anything within a code-base.

**Comment by tbfleming** [comment]
@lazaridiscom, we see that other projects have asked you to leave them alone. Please don’t make us do the same.

**Comment by lazaridiscom** [comment]
related #5101
