### ISSUE TITLE
EOS_REST API_404 error when try to unlock the wallet | Sign a transaction | Push a transaction

### ISSUE THREAD

**Issue by LinhNTNguyen** [EOSIO/eos#5080]
Hi,
My purpose is can push a transaction successfully. 
Based on this guide link: https://steemit.com/eos/@noprom/using-eos-rpc-api-to-transfer-eos 
I am stuck at the step "Unlock the Wallet"
After entering the data in the postman, like the attached image below
![image](https://user-images.githubusercontent.com/19145198/43758353-0acf2130-9a46-11e8-860d-c76b076d597e.png)

I received the 404 error

The same case for Sign a transaction
![image](https://user-images.githubusercontent.com/19145198/43758448-52f29de8-9a46-11e8-9d1d-7318a819ec5c.png)

and Push a transaction
![image](https://user-images.githubusercontent.com/19145198/43758828-85064e5a-9a47-11e8-9562-2bb8f5abb944.png)

Please help me! I really don't know the root cause why I cannot complete these steps.
Please tell me my mistakes when I fill the data or the format of data or something like that I think so.

Thank you so much.

**Comment by jgiszczak** [comment]
For wallet unlock and sign transaction, the URL must change to address `keosd`.  If you've been using `cleos`, it may be running already, in which case your RPC calls should be to `http://127.0.0.1:8900`.  If it's not running, you'll need to launch it with the argument `--http-server-address 127.0.0.1:8900`.

`keosd` hosts wallets, which holds keys, acting much like `ssh-agent`.  `nodeos` hosts the chain.

The `push_transaction` result was not a 404.  It was a 400.  It failed because `nodeos` accepts only packed transactions.

For a fully functioning Javascript implementation interacting with EOS.IO RPC, see [eosjs](https://github.com/EOSIO/eosjs).
