### ISSUE TITLE
get transaction error

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#5084]
eos version:v1.1.3
os:centos 7
net:mainNet

![image](https://user-images.githubusercontent.com/9130123/43768501-17a7e904-9a6a-11e8-957e-ffc103476b0f.png)

`$./cleos.sh get transaction 362dee1fddcef3a7cdde7724b471ed1a48ef30b0beef60d2d03f7f7f7f10c9ee
Error 3200006: invalid http request
Error Details:
The server has rejected the request as invalid!
Please verify this url is valid: http://127.0.0.1:28865/v1/history/get_transaction
If the condition persists, please contact the RPC server administrator for 127.0.0.1!
`

Does the question relate to closing "filter-on" in the config.ini file?

config.ini
`

    agent-name = AgentName

    #blocks-dir = "blocks"
    chain-state-db-size-mb = 65536
    reversible-blocks-db-size-mb = 340
    contracts-console = false

    http-server-address = 0.0.0.0:28865
    p2p-listen-endpoint = 0.0.0.0:28866
    #p2p-server-address = !!YOUR_ENDPOINT_IP_ADDRESS!!:28866

    http-validate-host = false
    verbose-http-errors = true  
    abi-serializer-max-time-ms = 2000  
    access-control-allow-origin = *

    #p2p-max-nodes-per-host = 4

    # actor-whitelist =
    # actor-blacklist =
    # contract-whitelist =
    # contract-blacklist =
    # filter-on =

    allowed-connection = any

    log-level-net-plugin = info
    max-clients = 150
    connection-cleanup-period = 30
    network-version-match = 1
    sync-fetch-span = 2000
    enable-stale-production = false

    max-implicit-request = 1500
    pause-on-startup = false
    max-transaction-time = 30
    max-irreversible-block-age = -1
    txn-reference-block-lag = 0
    unlock-timeout = 90000

    plugin = eosio::chain_api_plugin
    plugin = eosio::history_plugin
    plugin = eosio::history_api_plugin
    plugin = eosio::chain_plugin
    plugin = eosio::bnet_plugin
`

**Comment by jgiszczak** [comment]
If that's the entirety of your config.ini, your node is not synching with mainnet.

You need to add `p2p-peer-address =` entries for at least one, and preferably several mainnet peers.  See [this page](https://eosnodes.privex.io/) for a list of public endpoints.  You'll also need a copy of the mainnet [genesis file](https://eosnodes.privex.io/static/genesis.json).  Once you've added peers, you will need to shut down `nodeos` and restart it with `--delete-all-blocks --genesis-json genesis.json` (may require a relative path to where you downloaded genesis.json).  The node needs to be started with those parameters only once.  Subsequent restarts should omit them.

After starting with mainnet peers, your node will begin synching.  This will take many hours, as mainnet is approaching 10 million blocks.  Your `get transaction` query will succeed near the end of the synching process, since you selected a transaction on a recent block.

**Comment by ddzyan** [comment]
This is only part of the config.ini file. What you said has nothing to do with my problem.

**Comment by ddzyan** [comment]
Does the question relate to closing "filter-on" in the config.ini file?

**Comment by jgiszczak** [comment]
If you expect reliable help, do not omit information.

Yes, `filter-on=` must have a value assigned or the history plugin will not retain any information.  Set `filter-on=*` to catch everything, and replay your block log.
