### ISSUE TITLE
EOS is vulnerable to a DDOS attach by push cpu-heavy  action repeatedly

### ISSUE THREAD

**Issue by itleaks** [EOSIO/eos#5116]
Any action eating much than 400ms CPU will cause a exception "Expired Transaction".This action really eat BP's cpu but charge no CPU of the account. So a account can push this kind of action repeatedly, then EOS system will be  busy to deal these DDOS actions and let normal actions alone.
So TPS will keep low.

**Comment by vjoke** [comment]
Currently, EOS  relies on grey list to defend such attacks. However, due to no fee transaction, malicious clients can use this flaw to attack the system without cost.  It's difficult to detect such malicious behaviors.

**Comment by taokayan** [comment]
EOS has some ways to protect this kind of attacks:
- There's a maximum cpu time(30ms) for every transaction.
- If a transaction failed, it will not be broadcast to other nodes, which means that hackers can only hacker one see node rather than any of the producer nodes.
- greylist feature further prevents from hackers stealing elastic CPU/NET resources.

**Comment by taokayan** [comment]
This is more related to the network settings. Theoretically BPs should not allow users to push transactions into their producing nodes. In this case any failed transaction will not be broadcast to producing nodes.

**Comment by jgiszczak** [comment]
Between the existing limitations, existing greylist features, and recommended network architectures, this issue can be mitigated.  All network services are subject to attack and require mitigation of this nature.  Given the available tools, this is primarily an architectural and operations problem.
