### ISSUE TITLE
eosio Block problem

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#5145]
I  have three node,One of them is an eosio node and the other two are producer nodes.one producer is producing,i tried to change number of votes for eosio being Production block.But all nodes do not produce blocks.How do I make eosio node to produce block?sir.

**Comment by taokayan** [comment]
Can you provide more information? steps to produce, config, logs, ... etc.

**Comment by wypsanity** [comment]
xiaoxiaoxiao  EOS6Rm1tYMpzwrnY4i5jKYfdeWXBQrd2fMjtw3T3K1jAtE6R9u6dw  https://xiaoxiaoxiao.com/EOS6Rm1tYMpzwrnY4i
5jKYfdeWXBQrd2fM 1.0000
xiaoxiaopeng  EOS5uLEupJwSfLKW4cKWjsX1xFyEya893YWSHwgFB3x9V8yqeTKGg  http://xiaoxiaopeng.com
                 0.0000
Now open three nodes,the two producers produce blocks, 
close two producers ,eosio node shows
2018-08-10T06:54:22.091 thread-0   net_plugin.cpp:3013           plugin_startup       ] starting listener, max clients is 25
how can the eosio produce blocks when the two producers are closed?

**Comment by wypsanity** [comment]
nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --p2p-peer-address 134.175.57.249:9877 --access-control-allow-origin=* --contracts-console --http-validate-host=false"
nodeos -e -p xiaoxiaopeng --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /xiaoxiaopeng/dev/data --config-dir /xiaoxiaopeng/dev/config --http-server-address=127.0.0.1:8889 --access-control-allow-origin=* --contracts-console --http-validate-host=false --p2p-peer-address 134.175.57.249:9876 --p2p-listen-endpoint 127.0.0.1:9875

**Comment by wypsanity** [comment]
eosio config
bnet-endpoint = 0.0.0.0:4321
bnet-follow-irreversible = 0
bnet-no-trx = false
abi-serializer-max-time-ms = 15000
chain-state-db-size-mb = 1024
chain-state-db-guard-size-mb = 128
reversible-blocks-db-size-mb = 340
reversible-blocks-db-guard-size-mb = 2
contracts-console = true
read-mode = speculative
access-control-allow-credentials = false
max-body-size = 1048576
verbose-http-errors = false
http-validate-host = 1
max-login-requests = 1000000
max-login-timeout = 60
mongodb-queue-size = 256
mongodb-wipe = false
mongodb-block-start = 0

enable-stale-production = false
pause-on-startup = false
max-transaction-time = 80000
max-irreversible-block-age = -1

**Comment by brianjohnson5972** [comment]
I am not sure if I am following all of your scenario, does this match it:
You start up a producer node that has eosio as the producer (our test scripts will refer to this as the bios node)
You start up other producer nodes
You vote for the producers that are in the new producer nodes
The voted for producers start to produce (and eosio is no longer in the producer list)
All the producing nodes shutdown
No more blocks are produced

Am I correct?
If I am, then your issue is that there are no **scheduled** producers alive, so no blocks can be produced.

For this to work, you will need to restart one of those producing nodes with "--enable-stale-production" set on the command line.  You may have to re-start it several times because of  https://github.com/EOSIO/eos/issues/4971 which means it will only restart producing if you start up that producer in the window where that producer would create blocks based on clock time, or you can build with the latest on develop branch, since the fix for that just went in.

If what I wrote above does not describe your scenario, please write up a detailed scenario, similar to mine, that does describe what is happening.

**Comment by brianjohnson5972** [comment]
If none of the scheduled producers are producing, the only option you have is to restart one of the those producing nodes and vote in another producer (or producers).  At any given time, the system relies on the current producers to define the list of producers that will be valid producers in the future.  If your current producers are not producing, then you would have no way of determining who was valid to produce in the future.
