### ISSUE TITLE
"cleos create key" still uses the legacy prefix of "EOS"

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#5155]
@spoonincode 
@wanderingbort 
Despite the commit `https://github.com/EOSIO/eos/pull/2441/commits/573be193254661b1c9d47b4467080ed992dac15c`

When running the command `cleos create key`, it still generates the public key with prefix of "EOS"?
Expected prefix should be "PUB.", right?

```
cleos create key
Private key: 5JHySACGYYtAWpJ1Fk4k6hucbX7QXZez98PSBPZtLnzapuB3ikH
Public key: EOS8F2hwTp6642BG9B3hdbzP8EPU2xkvUm8RyfAaLdc69urYVruMG
```

```
cleos version client
Build version: 6a2014aa
```

```
nodeos -v

1780487338

```

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
