### ISSUE TITLE
Push transaction when onblock in plugin

### ISSUE THREAD

**Issue by Frank-AFN** [EOSIO/eos#5241]
I wish to push transaction when onblock in my plugin. But there is an error **tx_duplicate: Duplicate transaction**. Does anyone have this problem before? 

![image](https://user-images.githubusercontent.com/12408187/44129912-6b4dd44c-a07d-11e8-90ec-b59812f4a9f4.png)

**Comment by jgiszczak** [comment]
`cleos` uses the `memo` field in a transfer transaction as a nonce to ensure transaction uniqueness.  If you are not using `cleos` to generate your transactions, you should emulate this behavior if they are transfers.

If your transactions are custom actions rather than transfers, consider adding a nonce field.

If you'd prefer not to have a nonce field, you will need to generate actually unique transactions.  The easiest way to achieve this is to use a different reference block in each transaction.  Start as many blocks back as you have transactions and simply assign each transaction a new ref block in sequence.
