### ISSUE TITLE
Error 3060003: Contract Table Query Exception

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5243]
GuangdeMacBook-Pro:cleos tg$ ./cleos -u http://api.main.alohaeos.com:80/ get table zyixjmpxrrpr zyixjmpxrrpr account

Error 3060003: Contract Table Query Exception
Most likely, the given table doesn't exist in the blockchain.
Error Details:
Table account is not specified in the ABI

**Comment by qq1032246642** [comment]
Can you provide your code and abi?

**Comment by oranke** [comment]
I queried your contract `zyixjmpxrrpr `'s abi...

```javascript
......
	"tables": [
			{
				"name": "funds",
				"index_type": "i64",
				"key_names": ["name"],
				"key_types": ["name"],
				"type": "fund"
			},
			{
				"name": "teams",
				"index_type": "i64",
				"key_names": ["name"],
				"key_types": ["name"],
				"type": "team"
			},
			{
				"name": "global",
				"index_type": "i64",
				"key_names": ["name"],
				"key_types": ["name"],
				"type": "game_state"
			},
			{
				"name": "games",
				"index_type": "i64",
				"key_names": ["number"],
				"key_types": ["uint64"],
				"type": "game"
			},
			{
				"name": "purchases",
				"index_type": "i64",
				"key_names": ["buyer"],
				"key_types": ["name"],
				"type": "purchase"
			},
			{
				"name": "tpurchases",
				"index_type": "i64",
				"key_names": ["buyer"],
				"key_types": ["name"],
				"type": "tpurchase"
			},
			{
				"name": "records",
				"index_type": "i64",
				"key_names": ["exec_time"],
				"key_types": ["uint64"],
				"type": "record"
			}
		],
......
```

but there's no table that has name `account`. :)

**Comment by isTg** [comment]
@firesWu @oranke Thanks

**Comment by trungtt1981** [comment]
I've also got this kind of error when trying to query the table `termpricing`

```
cleos --wallet-url http://localhost:6666 --url http://138.197.194.220:8877 get table fsmgrcode222 usertrung123 termpricing
Error 3060003: Contract Table Query Exception
Most likely, the given table doesn't exist in the blockchain.
```

The funny thing is that, another table `unitimg` has the similar structure but can be queried successfully.

The only difference between table `termpricing` (not query-able) and table `unitimg` (query-able) is as follows:

```
  struct termpricing {
    uint64_t id;
    uint64_t unit_id;

    uint64_t rent;
    uint64_t term;
    uint64_t start_date; //unix timestamp
    uint64_t end_date;   //unix timestamp


    auto primary_key()const { return id; }
    uint64_t by_unit()const { return unit_id; }

    EOSLIB_SERIALIZE(termpricing, (id)(unit_id)(rent)(term)(start_date)(end_date));
  };

  // @abi table
  struct unitimg {
    uint64_t id;
    uint64_t unit_id;

    checksum256 image_hash;
    string ipfs_address;

    auto primary_key()const { return id; }
    uint64_t by_unit()const { return unit_id; }

    EOSLIB_SERIALIZE(unitimg, (id)(unit_id)(image_hash)(ipfs_address));
  };

```

The generated ABI files:

```
    },{
      "name": "termpricing",
      "index_type": "i64i64i64",
      "key_names": [
        "id",
        "unit_id",
        "rent"
      ],
      "key_types": [
        "uint64",
        "uint64",
        "uint64"
      ],
      "type": "termpricing"
    },{
      "name": "unitimg",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "unitimg"
    },{

```

Clear to see the difference is that, in table `termpricing`, the 3rd element `uint64_t rent;` is of type `unit64` while the 3rd element in table `unit` is `checksum256 image_hash;` that is not of type `uint64`.

So, we can `conclude` that the generated ABI file has mis-interpreted the table `termpricing` in the way that it treats the 3rd element as foreign key although the 3rd element is not specified as foreign key.

This means that, in a table `struct`, the 3rd element must not be of type `uint64`. Otherwise, it will be treated as foreign key and this will result in `"index_type": "i64i64i64",`

How should I resolve this problem??

I've interacted with a private chain.
Block-producers version: 

```
    base        https://github.com/NebulaProtocol/eos.git
    branch      master
    rev         3b25100d4c796df5ebd2e03ebbe8da5e140ee4cf (Thu Aug 9)

     nodeos -v
    992284685
```

Client node version:

```
    base        https://github.com/NebulaProtocol/eos.git
    branch      sql_plugin
    rev         6a2014aaac65bbd8d40459c44976d6e7c77eaa21 (Thu Jul 26)

    nodeos -v
    1780487338
```

**Comment by midotrinh2** [comment]
I've been able to resolve my own problem  by simply adding a dummy element of type string between the 2nd element and the 3rd element of struct `termpricing`. But I don't wire this dummy element into the table "termpricing" via `EOSLIB_SERIALIZE`.

This really helps! Now it is possible again to query the table `termpricing`
