### ISSUE TITLE
when i run  "cleos --wallet-url http://localhost:8899"--Error 3200006: invalid http request, i already set "http-validate-host = 0"

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5246]
1、when i run cleos --wallet-url http://localhost:8899 set contract eosio build/contracts/eosio.bios 
![image](https://user-images.githubusercontent.com/11773000/44138719-6c68be58-a0a7-11e8-9669-ca1ebc54d227.png)
2、but when i change  localhost to 127.0.0.1 ,then i run "cleos --wallet-url http://127.0.0.1:8899 set contract eosio build/contracts/eosio.bios", it's ok:
![image](https://user-images.githubusercontent.com/11773000/44138786-9d7afa88-a0a7-11e8-8d17-e6a8fc74aa77.png)
3、in "~/.local/share/eosio/nodeos/config/config.ini " file "http-validate-host = 0":
![image](https://user-images.githubusercontent.com/11773000/44138844-ca43a786-a0a7-11e8-8b7b-af5ca0662812.png)
4、when i ping localhost ,it's ip is 127.0.0.1
![image](https://user-images.githubusercontent.com/11773000/44139446-b338301e-a0a9-11e8-9eb3-4bb7eb2efd0c.png)

**Comment by wanderingbort** [comment]
This is correct behavior, `keosd` does not read the configuration for `nodeos` that you have mentioned.  As `keosd` protects sensitive keys it requires the HTTP Host headers to be exactly validated.  you will need to replicate the `http-validate-host` setting in the config file for `keosd` 

If you are not running an installed build this is probably located in `${HOME}/eosio-wallet/` otherwise it is part of your installation

the reason (2) works is that the IP address is automatically a whitelisted host if that is the exact local IP you are connecting to.

**Comment by amActiveHello** [comment]
thabk you, now it's ok.but when i run "cleos --url http://localhost:8889 get info", it  produces the same error:
![image](https://user-images.githubusercontent.com/11773000/44181235-50744000-a133-11e8-9e6a-1d07466f1173.png)
I already set "http-validate-host = 0" in nodeo's config file (.local/share/eosio/nodeos/config/config.ini)：
![image](https://user-images.githubusercontent.com/11773000/44181256-6da90e80-a133-11e8-93bc-d63118e8f404.png)

**Comment by jgiszczak** [comment]
Be sure you have restarted `nodeos` since making the change to its configuration file.  It does not reread the config file while running.
