### ISSUE TITLE
when import privatekey into a not defalut wallet， cleos create account failed.

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5249]
1、
Private key: 5JgbL2ZnoEAhTudReWH1RnMuQS6DBeLZt4ucV6t8aymVEuYg7sr
Public key: EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg
2、when i creat an account ,it show:
![image](https://user-images.githubusercontent.com/11773000/44141917-227f2b6a-a0b1-11e8-9710-200025bfc7d2.png)
3、but 
![image](https://user-images.githubusercontent.com/11773000/44141949-37f69ed8-a0b1-11e8-8253-043733b85e34.png)
4、In my block chain ,eosio is a initial   producer , where can i find  the eosio Key。Is it still necessary for me to import eosio's key into wallet2?

**Comment by amActiveHello** [comment]
![image](https://user-images.githubusercontent.com/11773000/44144086-c2add562-a0b8-11e8-97d9-f85811ccf0cd.png)
sec@ll-B85M-DS3H-A:~/rgh/eos_719$ cd eos
sec@ll-B85M-DS3H-A:~/rgh/eos_719/eos$ git rev-parse HEAD
75635168e743c3e65bb6345a1eaedd905581e6b0
sec@ll-B85M-DS3H-A:~/rgh/eos_719/eos$  git branch -a
* master
  remotes/origin/1771-QA

**Comment by wanderingbort** [comment]
the error in 2 is because you cannot sign on behalf of `eosio`.  You will need to import that key into your wallet.

If you modified the `genesis.json` that you launched the chain with the the `initial_key` in that file is the public key for which you need to have the private key.

If you did not modify it or the build process then the default testing key is `EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV` and the corresponding private key is `5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`
