### ISSUE TITLE
block producer quality control

### ISSUE THREAD

**Issue by jjssoftware** [EOSIO/eos#5311]
EOSIO needs to natively support features to improve the quality and availability of active and stand by block producers.

- It's not acceptable for a top 21 BP to stop producing blocks for hours and remain in the top 21 with no perceivable consequence.
- It's not acceptable for a backup block producer to not be fully available to assume the role of an active BP at any time whilst at the same time collect daily rewards for their services which may or may not work when needed.

In both of these cases the suggestion to vote them out is impossible in the current climate of lack of voter engagement. Therefore in both of these cases we need to strengthen core EOSIO functionality with automated monitoring / grey listing / reduction and or removal of rewards mechanisms to add incentives for BPs to improve and maintain the quality of their services.

Suggestions:

1. Blocks produced by BPs are counted and monitored per BP
2. The [greymass producerjson](https://github.com/greymass/producerjson) smart contract be introduced as a core EOSIO feature
3. This contract be extended to enable the json data to be validated against a standard schema
4. On chain BP data via this contract be gradually introduced as a mandatory requirement for ALL block producers
5. The endpoints defined within the content of the BP data be used to monitor the availability of BP API endpoints as a core feature
6. Grey listing and reduction / removal of rewards features be introduced based on the detection of inadequacies in (1) and (5)

**Comment by wanderingbort** [comment]
Thanks for the submission.  Unfortunately, this issue is a little broad and seem applicable to the governance of a specific EOSIO-based blockchain (as the concept of producer rewards is a construct of the deployed system contracts).

It seems like some components would be appropriate as feature requests in the [eosio.contracts repo](https://github.com/EOSIO/eosio.contracts).  However, I'd encourage those requests to be as dry and succinct as possible. 

As the majority of this issue deals with governance IMO, I'm going to close it as off-topic for this repository and hope that you can find a more appropriate place to relocate it.  

If you feel that this is in-appropriate you can re-open but there would need to be some sort of substantive feature request or bug report.
