### ISSUE TITLE
cleos transfer  ok, but cannot find it on chain

### ISSUE THREAD

**Issue by past2017** [EOSIO/eos#5331]
eos version: v1.1.3
**I transfer a tx by cleos and it looks everything is ok, but I cannot find it on chain after 10 mintues**
```
alias cmd='$HOME/eos/build/programs/cleos/cleos --wallet-url http://127.0.0.1:8900  -u http://127.0.0.1:33333'
eos@b-stage-eth-btc-wallet:~$ cmd transfer eostosky1234 bkexeostest2 "0.013 EOS" "jjjll"
executed transaction: cf63b7a8afe5aa8b1e47bc69e935ac485e0d2124286e3307391092ef10fa41c8  136 bytes  8544 us
#   eosio.token <= eosio.token::transfer        {"from":"eostosky1234","to":"bkexeostest2","quantity":"0.0130 EOS","memo":"jjjll"}
#  eostosky1234 <= eosio.token::transfer        {"from":"eostosky1234","to":"bkexeostest2","quantity":"0.0130 EOS","memo":"jjjll"}
#  bkexeostest2 <= eosio.token::transfer        {"from":"eostosky1234","to":"bkexeostest2","quantity":"0.0130 EOS","memo":"jjjll"}
warning: transaction executed locally, but may not be confirmed by the network yet    ] 
```

![image](https://user-images.githubusercontent.com/25541244/44334075-2c9e5a80-a4a3-11e8-81ea-60532ec17ab3.png)

But on chain, I cannot find it
![image](https://user-images.githubusercontent.com/25541244/44334235-8c950100-a4a3-11e8-8db3-0ee735441ba3.png)
![image](https://user-images.githubusercontent.com/25541244/44334268-a20a2b00-a4a3-11e8-9308-5477176f2c18.png)

**Comment by jgiszczak** [comment]
The alias you are using refers to a local node.  If that local node is not synched with mainnet and the tool you are using queries mainnet, the tool will not ever see your transaction.  You have a commented-out alias for `-u http://mainnet.eoscalgary.io`.  You will need to use that alias rather than the one currently in use if your localhost node on port 33333 is not synched to mainnet.  Given the existence of the other alias, it seems likely it is not.
