### ISSUE TITLE
keosd Wallet unlock JSON RPC works only localhost, not external

### ISSUE THREAD

**Issue by psy2848048** [EOSIO/eos#5356]
Hi,

I tried to execute unlock API external but it runs only localhost.

Environment: Ubuntu 16.04, EOSIO v1.2.1

keosd is running as the below.

```bash
keosd --plugin eosio::http_plugin --http-server-address 0.0.0.0:8900 --access-control-allow-origin 0.0.0.0 --verbose-http-errors
```

With cURL in localhost, it works well.

```bash
curl --request POST   --url http://127.0.0.1:8900/v1/wallet/unlock --data '["default", "passcode"]'
{}

curl --request POST   --url http://127.0.0.1:8900/v1/wallet/unlock --data '["default", "wrong_password"]'
{"code":500,"message":"Internal Service Error","error":{"code":3120005,"name":"wallet_invalid_password_exception","what":"Invalid wallet password","details":[]}}
```

But in postman of my laptop, it only response 400.

<img width="904" alt="2018-08-22 9 02 07" src="https://user-images.githubusercontent.com/6794036/44435265-1f3fb800-a5ea-11e8-9cdd-7fe54f707602.png">

Does it block every external connection from v1.2.1, or unencrypted(HTTP, not HTTPS) request?

**Comment by wanderingbort** [comment]
to help mitigate DNS rebinding and blind CSRF attacks, we validate the HTTP level `Host:` header against a set of expected values.  By default, this only includes literal URL that `keosd` is configured to listen on and any direct IP values when that IP address _is_ the IP bound to the listening device (which is why `127.0.0.1` works) 

For all other host values you should append the argument(s) `--http-alias=hostname[:port-if-not-default]`

judging by your postman image, you should add `--http-alias=etos.ciceron.xyz:8900`

I will also caution that the HTTP RPC for wallets does no authentication outside of unlocking wallets so, any client able to successfully submit an HTTP RPC command to your external endpoint can use the wallets.  Please deploy such a configuration very carefully

**Comment by oslivan** [comment]
I had add the header, but also return 400, my log below:
```
root@eosnode:~# curl -v --header 'Host: 127.0.0.1:8900' --request POST --url http://127.0.0.1:8900/v1/wallet/list_wallets
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8900 (#0)
> POST /v1/wallet/list_wallets HTTP/1.1
> Host: 127.0.0.1:8900
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Connection: close
< Server: WebSocket++/0.7.0
<
* Closing connection 0
```
where is my problem? thanks.

**Comment by oslivan** [comment]
sorry, I found the problem, I bound keosd server as `0.0.0.0:8900`, so I also set header as `Host: 0.0.0.0:8900`.
