### ISSUE TITLE
EOS smart contracts and big data

### ISSUE THREAD

**Issue by oshek14** [EOSIO/eos#5366]
Hello guys. Imagine situation when I need to save a big data In smart contract (for example 1000 000 000 row of information - or just 1 TB). In case of ETH it's almost impossible because gas price goes to hell. How is the situation in EOS? I know that concept of gas doesn't exist here, but here we have RAM limit that depends on our stake, more stake more limit. but  how much stake will be enough? Is it common sense to save that much data it EOS smart contract? what's the solution?

**Comment by jgiszczak** [comment]
RAM is purchased outright rather than staked.  EOS.IO mainnet provides 70.07 GiB of RAM space as of this writing.  (The number is slowly ramping up.)  Storing 1 TB into RAM tables for a single smart contract is infeasible, and that will not be changing any time soon.  The solution is to minimize the amount of data stored in state RAM.  Typically this would mean storing solely a proof of some data being stored elsewhere.

Alternatively, if you wish to store immutable data, you may store it on the chain.  That is limited by your network and CPU stake, mostly network, which regenerates over time.
