### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#5371]
/home/eos-v1.0/eos/build/programs/cleos$ sudo ./cleos create account eosio eosio.token  EOS4txqUrQiv56ApNTHGjEXCyoKKoe4d2R8cGiRQHMN6bxGR2w4Zw

Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

**Comment by jgiszczak** [comment]
Load the private key for the `eosio` account into your wallet.  The [Getting Started With Smart Contracts](https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts) tutorial includes instructions for how to do this.  As it says at the beginning of the Token tutorial, you'll need to finish the Getting Started tutorial first.

**Comment by VtpVlan-oo7** [comment]
@jgiszczak 
 
hey i  follow the link   https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts  
did the same step by step as they suggested but still i am getting the error-

/home/eos-v1.0/eos/build/programs/cleos$ cleos set contract eosio build/contracts/eosio.bios -p eosio@active

got this error->

Reading WASM from build/contracts/eosio.bios/eosio.bios.wasm...
Error 3160009: No wast file found
Error Details:
no wasm file found build/contracts/eosio.bios/eosio.bios.wasm

and apartt from that i did 


/home/eos-v1.0/eos/build/programs/cleos$  sudo ./cleos set contract -f eosio  /home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.wasm /home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.abi /home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.wast

got this error ->

Reading WASM from /home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.wasm/home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.abi...
Error 3160009: No wast file found
Error Details:
no wasm file found /home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.wasm/home/eos-v1.0/eos/build/contracts/eosio.bios/eosio.bios.abi

**Comment by jgiszczak** [comment]
You need to provide the correct path to the contract directory.  You gave it a relative path, but your working directory is not the expected one.  Try:
`/home/eos-v1.0/eos$ cleos set contract eosio build/contracts/eosio.bios -p eosio@active`
Be sure your `pwd` is `/home/eos-v1.0/eos` if you paste that command verbatim.  Endless variants are possible if your working directory is someplace else.  It's up to you to make the necessary adjustments to the contract directory path if you deviate from the instructions.  The second paragraph of Step 3 told you what your working directory should be.  Since yours wasn't, the command failed.
