### ISSUE TITLE
EOSIO : How to get receiving information of my EOS account???

### ISSUE THREAD

**Issue by flygonsam** [EOSIO/eos#5437]
In the eos developers potal, I can't find API such as get_receive_actions, there is only get_actions.
It seems like show only send transactions. Am I right?
I want to see receive transactions of my account.............

Please help me........

**Comment by xJonathanLEI** [comment]
In fact, `get_actions` already include the actions you're looking for. The reason you're not seeing them, I guess, is that the node you're requesting from filters them out due to performance and disk space consideration.

To prove this, run a local testnet with `--filter-on "*"` and send some actions. Then use `cleos get actions` on the receiving account.

In your case, you'd probably need to run your own full node with `--filter-on` set to your account. Remember to use `--replay-blockchain` if this is not a fresh start.

Also note that the `history_plugin` is being deprecated, the MongoDB plugin should be favored at this point as the deprecated plugin will be removed in the `1.3.0` release.

**Comment by tbfleming** [comment]
The history plugin is not scheduled for removal at this time, but is deprecated. The mongodb plugin is recommended.

**Comment by xJonathanLEI** [comment]
@tbfleming You’re right. The one being removed is eosiocpp :)

**Comment by kstvigilante** [comment]
@xJonathanLEI why are you removing eosiocpp? how will i compile code if its scheduled to remove ? developers.eos.io still shows to compile it use eosiocpp

**Comment by xJonathanLEI** [comment]
I'm not from EOS... So it's not me removing it. Anyway, you're supposed to use `eosio.wasmsdk` instead of `eosiocpp`.
