### ISSUE TITLE
Invalid http response

### ISSUE THREAD

**Issue by amarinnotical** [EOSIO/eos#5469]
Whenever I am trying to set contract or create wallet/account the following error is showing-

Error 3200002: invalid http response
Error Details:
Invalid content-length response

**Comment by taokayan** [comment]
try to start nodeos with ```--http-validate-host=false```

**Comment by jgiszczak** [comment]
You may also need to start `keosd` with the same argument.  Alternatively, when specifying your `--wallet-url`, be sure to use an exact match for the binding address used by `keosd`.  If `keosd` is bound to 127.0.0.1:8900 for instance, use exactly `--wallet-url http://127.0.0.1:8900`.  If `keosd` is bound to localhost:8900, use exactly `--wallet-url http://localhost:8900`.  The two are not synonyms in this context since exact match is required.

You may also use the `--http-alias` option to add alternatives to the list of possible matches, e.g.
`keosd --http-server-address=127.0.0.1:8900 --http-alias=localhost:8900`
allows you to write
`cleos --wallet-url=http://127.0.0.1:8900` or `cleos --wallet-url=http://localhost:8900` and both work equally well.

**Comment by jgiszczak** [comment]
@flylee2004 Paste what commands you have tried and the resulting errors.  Preferably into a new ticket unless the error you are seeing is identical to the one in this issue.

**Comment by feleio** [comment]
@jgiszczak @taokayan I have the same issue. 
i have tried all your suggestion but still getting the same error.
```
cleost='docker exec -it eosio /opt/eosio/bin/cleos --url https://jungle.eosio.cr:443 --wallet-url http://0.0.0.0:5555' set contract xxxxtestacct /contracts/test
```
and i get back
```
Error 3200002: invalid http response
Error Details:
Invalid content-length response
```

**Comment by feleio** [comment]
here is how i start my docker
```

docker run --name eosio \
  --publish 7777:7777 \
  --publish 127.0.0.1:5555:5555 \
  --volume /Users/felix.ling/project/eosio/contracts:/contracts \
  --detach \
  eosio/eos:v1.4.2 \
  /bin/bash -c \
  "keosd --verbose-http-errors --http-validate-host=false --http-server-address=0.0.0.0:5555 & exec nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:7777 --access-control-allow-origin=* --contracts-console --http-validate-host=false --verbose-http-errors --filter-on='*'"
```

**Comment by feleio** [comment]
I have solved my problem by changing  --url https://jungle.eosio.cr:443 to  --url http://jungle2.cryptolions.io:80
