### ISSUE TITLE
Transaction submitted even after block production was paused

### ISSUE THREAD

**Issue by mamidi1211** [EOSIO/eos#5473]
Able to Submit a transaction and also able to look that info from the other peer node. 
Is this expected behaviour ?

If so what is the purpose of pause and resume of Block Production.

**Comment by jgiszczak** [comment]
This is expected behavior.  Transactions are propagated independently of blocks in order to reach the current producer to be incorporated into a block as soon as possible.  Each node propagating the transaction will speculatively execute it (unless it's synching), resulting in visibility of the transaction to queries.  Check again after expiration time of the transaction and you should see that it has been unwound and is no longer visible while block production is paused.
