### ISSUE TITLE
My contract transfer some EOS to eosio.stake as a random roll bonus automatically when unstack CPU bandwith.

### ISSUE THREAD

**Issue by lychees** [EOSIO/eos#5480]
Background :
https://eosflare.io/tx/394e4f40fe1720c073f6fb42c5786153ad35ed146a642402a18b6b6b40e0beeb
https://eosflare.io/tx/a9c2439267cf12fcefb89334447040624198299811008b66db20053324049993

Project :
https://happyeosslot.com/

Contract Code :
https://github.com/Andoromeda-Foundation/dapp-examples/tree/master/Contracts/EOS/happyeosslot

```
void happyeosslot::onTransfer(account_name from, account_name to, asset eos, std::string memo) {        
    if (to != _self) {
        return;
    }
    require_auth(from);
    eosio_assert(eos.is_valid(), "Invalid token transfer");
    eosio_assert(eos.symbol == EOS_SYMBOL, "only core token allowed");
    eosio_assert(eos.amount > 0, "must bet a positive amount");
    string operation = memo.substr(0, 3);
    if (operation == "bet" || ((operation != "buy") && (eos.amount >= 100000))) {
        const checksum256 seed = parse_memo(memo);
        bet(from, eos, seed);
    } else {
        buy(from, eos);
    }
}
```

Hi, I am the author of happyeosslot. It sounds like a ridiculous bug but, when I receive the unstack fund, it triggers the onTransfer() function as a bet, and transfer some EOS token to the eosio::stack automatically. So I wonder is there any possible way I can get my fund back?

Regards,
Minako

**Comment by jgiszczak** [comment]
Since you directly transferred to the `eosio.stake` account, an entry was not created in the refund table that would allow you to reclaim your tokens automatically.  You will need to appeal to mainnet ECAF arbitration for a ruling and an order to allow a refund to be created and approved manually.

At the moment, the only means of communication with ECAF appears to be Telegram, at https://t.me/eosarb

There is a proposal to move all ECAF deliberations into an on-chain forum, but the software is not yet written.
