### ISSUE TITLE
File to memory mapping, why only set data is stored in a DB file?

### ISSUE THREAD

**Issue by Sayplaydiv** [EOSIO/eos#5533]
Ask the EOS data is a file and then config. ini configuration inside the chain size needs to be constantly tuned up. Why not divide into multiple DB stores? What advantages do individual files have?

**Comment by Sayplaydiv** [comment]
This leads to the problem that each time a thread suddenly breaks, so many blocks need to be indexed from the new index, so I would like to ask if there is any solution?

**Comment by taokayan** [comment]
There's no advantage of dividing a single block log file into multiple files. Let's do a comparison:

Suppose you have 4 hard disks, each of them has a capacity of 10TB and has a write throughput of 200MB/s.

Option 1): 
4 hard disks are mounted to C:, D:, E:, F:, respectively. Then an application which would first fill into C:\log0.txt, then D:\log1.txt, then E:\log2.txt, then F:\log3.txt. You'll notice that at anytime only one of the hard disk is busy, resulting in a write throughput of 200MB/s.

Option 2):
4 hard disks are configured as RAID 0 with a total capacity of 40TB. The application only write into a single file. But in this case, since all the harddisks are operating together, it results in a throughput of 800MB/s.

Option 3):
4 hard disks are configured as RAID 5 with a total capacity of 30TB. The application only write into a single file. But in this case, since all the harddisks are operating together, it results in a throughput of 600MB/s but allowing any one of those to become malfunction.

obviously Option 2 & 3 are better than option 1.
