### ISSUE TITLE
Duplicate deferred transaction

### ISSUE THREAD

**Issue by enfipy** [EOSIO/eos#5596]
### I have a problem with deferred transaction
When I trying to send a transaction on the same action (method) that has been already sent deferred transaction - new transaction says `Error 3040009: Duplicate deferred transaction` but this transaction with new unique `sender_id`.
This is my [abi](https://gist.github.com/enfipy/7608c4c4d4ead78bbe09be4ed6b948b8) and [code](https://gist.github.com/enfipy/5c19360f8f54b4179b1be8ba7c2ae739).

**Comment by jgiszczak** [comment]
You are using `now()` to construct your `sender_id`.  The results of `now()` are unique only per block.  As long as you generate deferred transactions that are only ever scheduled once per block, your transactions will be unique.  Otherwise they are not.  To avoid effectively throttling yourself to one transaction per block, you need to incorporate more unique information in the `sender_id`, such as the subscriber.
