### ISSUE TITLE
Want to see scalability of eos with 1 block producer

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5610]
The simple question here is I am not able to perform more than 200 transactions with a single block producer should I increase the number of producers or should I do something else the error I am facing is expired expired_tx_exception explain briefly, please.

**Comment by taokayan** [comment]
The number of producers has nothing to do with the transaction throughput. To achieve a higher throughput, you may need to do the following:
- use a machine with higher CPU frequency (3+ GHz)
- run multiple validating (non-producing) nodes together with one producing node
- only push transactions into validating nodes, so that transaction abi serialization only happens on validating nodes.

**Comment by yashvadhvani** [comment]
can you tell me how to start a non-producing block please

**Comment by jgiszczak** [comment]
See the [documentation](https://developers.eos.io/eosio-nodeos/docs/environment-non-producing-node), both that document and the one it links to at the beginning of it.  To be perfectly clear, a non-producing node is an instance of `nodeos` running without the `producer-name` option defined anywhere, either in the configuration file or the command line.
