### ISSUE TITLE
get_table_rows gets confused with all numeric account name

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#5616]
Works as expected.  Note, the account name (the 'scope') is alphanumeric like most other accounts:

>$ curl --data '{"json":true,"code":"eosio.token","scope":"geydcmrxg4ge","table":"accounts"}' 'https://api.eosio.cr/v1/chain/get_table_rows'
{"rows":[{"balance":"0.1007 EOS"}],"more":false}

Possible bug, this account exists but did not return a balance record like the account above.  Note, the account name is all numeric:

>$ curl --data '{"json":true,"code":"eosio.token","scope":"112233445511","table":"accounts"}' 'https://api.eosio.cr/v1/chain/get_table_rows'
{"rows":[],"more":false}

To verify, this account does exist and has a balance:

>$ curl --data '{"account_name":"112233445511"}' 'https://api.eosio.cr/v1/chain/get_account'
{"account_name":"112233445511","head_block_num":15868066,"head_block_time":"2018-09-11T14:16:30.000","privileged":false,"last_code_update":"1970-01-01T00:00:00.000","created":"2018-06-19T17:26:45.000",**"core_liquid_balance":"0.0001 EOS"**,"ram_quota":8149,"net_weight":1000,"cpu_weight":1000,"net_limit":{"used":0,"available":68388,"max":68388},"cpu_limit":{"used":0,"available":12652,"max":12652},"ram_usage":2996,"permissions":[{"perm_name":"active","parent":"owner","required_auth":{"threshold":1,"keys":[{"key":"EOS8H489DAGcEQdy8N4P2p7ubDFZxdX66DQQzxszEyG9WVEfgD4nu","weight":1}],"accounts":[],"waits":[]}},{"perm_name":"owner","parent":"","required_auth":{"threshold":1,"keys":[{"key":"EOS6kiq5qxqgLGMVqFtyWdfpPyLaUk7KrxAQwoBETf2AG4mxN8GpC","weight":1}],"accounts":[],"waits":[]}}],"total_resources":{"owner":"112233445511","net_weight":"0.1000 EOS","cpu_weight":"0.1000 EOS","ram_bytes":8149},"self_delegated_bandwidth":null,"refund_request":null,"voter_info":null}
```

**Comment by jgiszczak** [comment]
Note that the correct balance is returned if the workaround is applied:
```bash
curl --data '{"json":true,"code":"eosio.token","scope":" 112233445511","table":"accounts"}' 'https://api.eosio.cr/v1/chain/get_table_rows'
```
```json
{"rows":[{"balance":"0.0001 EOS"}],"more":false}
```
This is a parsing problem with JSON.  Account names are representations of 64 bit numeric identities, which the parsing code will default to when it sees a purely numeric value.  The workaround forces interpretation in string form.  Javascript parsers are typically loose, interpreting `"112233445511"` numerically to be "helpful".  The fc library used by EOS.IO follows that precedent rather than strictly interpreting only `112233445511` numerically.

This is a known limitation, and at present there are no plans to switch to strict parsing.
