### ISSUE TITLE
why do I get different returns on "get actions" depending on which api node I use?

### ISSUE THREAD

**Issue by hsejin314** [EOSIO/eos#5624]
curl -X POST https://APINODE/v1/history/get_actions -d '{"account_name": "eos.io", "pos":"-1", "offset": "-1"}'

I get different returns depanding what APINODE is.

What can be the reason?

**Comment by taokayan** [comment]
This is possible because different BP may have different filter for account history. If you want a consistence result you may need to sync with mainnet using your own machine.

**Comment by jgiszczak** [comment]
To expand on @taokayan's answer, you also have no visibility into when a given node enabled the history plugin and whether or not it replayed the whole blockchain when it did.  There is no summary or status information available about how long the history plugin has been enabled.

It also happens when you specify "pos" and "offset" values less than zero.  To get consistent results from multiple nodes, you need positive "pos" and "offset" values that match and are small enough that all nodes being queried can successfully serialize the requested data in the limited time allotted.  Even then you might not get an exact match because of the aforementioned variances.

Running your own node is the only way to be certain you know the conditions under which you are operating.

**Comment by hsejin314** [comment]
thanks for advise!
