### ISSUE TITLE
Found vulnerabilities in a wasm.

### ISSUE THREAD

**Issue by kotbegemot** [EOSIO/eos#5694]
https://github.com/WAVM/WAVM/issues/93
https://github.com/WAVM/WAVM/issues/94
https://github.com/WAVM/WAVM/issues/96
https://github.com/WAVM/WAVM/issues/97
https://github.com/WAVM/WAVM/issues/98
https://github.com/WAVM/WAVM/issues/99
https://github.com/WAVM/WAVM/issues/100

**Comment by fproulx-eoscanada** [comment]
@kotbegemot at the moment the WASM is not executed with `WAVM`, `eosio` uses `binaryen`
https://github.com/EOSIO/eos/tree/75635168e743c3e65bb6345a1eaedd905581e6b0/libraries/chain/webassembly

`WAVM` can be used experimentally though, but none of the block producers use it in production.

**Comment by spoonincode** [comment]
Those particular crashes were reported to block.one via the bug bounty program (https://hackerone.com/eosio) and fixed in the WAVM code that eosio uses today. The reporter also submitted these directly to the WAVM maintainer after some additional time. It might be prudent to use fixes straight from WAVM instead of our original fixes, but we're protected from these issues regardless.

In the future I would encourage you to report potential security issues through the bug bounty program. block.one will probably not pay out for issues disclosed publicly first.

**Comment by kotbegemot** [comment]
@spoonincode 
I had no task to get bonuses. 
I had a desire to protect the system. 
Please show a list of commits that address these vulnerabilities .

**Comment by spoonincode** [comment]
Mostly through these
https://github.com/EOSIO/eos/commit/c7e050740b2bca9198c515881c7c82adcb544d3a
https://github.com/EOSIO/eos/commit/91ecbe78827286714bf9314bc4fb54d73232c7f4
