### ISSUE TITLE
get_account api returns strings instead of integers

### ISSUE THREAD

**Issue by michaeljyeates** [EOSIO/eos#5744]
Compare the results of get account with username `evilmikehere` and `kas` on jungle.  The cpu limits are sent as strings when the numbers are large.

`"cpu_limit":{"used":374139,"available":"4463243340","max":"4463617479"}`

vs

`"cpu_limit":{"used":71843,"available":112588030,"max":112659873}`

Number.MAX_SAFE_INTEGER is 9007199254740991 so any numbers below that should be safe to represent

**Comment by jgiszczak** [comment]
For 64 bit signed and unsigned integers greater than 0xffffffff and for doubles, the JSON converter stringifies the number by default.  There is a parameter available to avoid that, but `cleos` does not expose it.  This is because Javascript does not include standard support for 64 bit integers and can not parse them in numeric form when they're larger than that threshold.  The limits you are quoting are 64 bit integers, not doubles.
