### ISSUE TITLE
how to compress wasm

### ISSUE THREAD

**Issue by god2g** [EOSIO/eos#5745]
I wrote a contact with 79KB size. It cost around 80 EOS to publish to the mainnet. It is too expensive. Is there something I can do to smaller the size?

**Comment by artjoma** [comment]
> also try using different compile options to generate smaller code.

Could you pls provide an example for eosiocpp or compilation optimization only available for EOSIO.CDT ?

**Comment by artjoma** [comment]
@god2g use:
```eosio-cpp -O=2 ```
Include compiler optimization level to decrease RAM usage size:
from:
```memory: 
     quota:     936.6 KiB    used:     921.1 KiB 
```
to:
```memory: 
     quota:     936.6 KiB    used:     795.3 KiB 
```

**Comment by jgiszczak** [comment]
`eosio-cpp` supports -Os but not -Oz.  In Clang, -Os is identical to -O2.  `eosio-cc` supports -Oz, which drops `-vectorize-loops` but is otherwise the same as -O2/-Os.  It may be worth compiling manually using `eosio-cc`, as suggested in the documentation, if your contract code uses large loops.

taokayan's advice is probably the most pertinent.  Compiler optimization can not make up for excessively large libraries.

**Comment by Dexaran** [comment]
`eosio-cpp -Os -finline-hint-functions -fno-elide-constructors -O2`
