### ISSUE TITLE
An option to clear tables or not when doing "cloes set contract --clear"

### ISSUE THREAD

**Issue by yiran-ever** [EOSIO/eos#5758]
After doing "cleos set contract --clear", the tables can not be reached any more, and the ram is wasted. So we can add an option to let the user choose to clear the table or not.

**Comment by taokayan** [comment]
In fact you can still reach the table by setting the old contract back. There's no built-in functionality to clear the whole table in a single operation because one table can hold a huge amount of user data. However, contract owner can always enhance their contracts to provide actions to remove one or multiple rows from their tables at one time.
