### ISSUE TITLE
Multi node private EOS network deployment 

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#5762]
I understand from https://developers.eos.io/eosio-nodeos/docs/local-multi-node-testnet we can deploy multiple eos nodes on single machine, can you please share information regarding how to do multiple eos node deployment on multiple lets say ec2/azure cloud instances ?

**Comment by jgiszczak** [comment]
Simply follow the same tutorial, but copy your EOS.IO build to each instance, and modify the `--p2p-listen-endpoint` and `--p2p-peer-address` arguments to each node appropriately.  Rather than the localhost IP addresses in the sample, you would substitute the IPs of each of your nodes.

For an automated way of accomplishing this, you may wish to use `eosio-launcher`.  Getting all the listen addresses and peer addresses correct manually on each node is tedious and error-prone.  Run `eosio-launcher --help` for information about how to run it.  You'll need to compose a hosts.json or servers.json file specifying the instances you wish to use.  Use the `--output` argument to get a sample hosts.json file, which you can edit, substituting instance IPs as you would when manually following the tutorial.

**Comment by sivachaitanya** [comment]
yeah that worked for me, Thanks @jgiszczak
