### ISSUE TITLE
cannot include memory.hpp twice

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#578]
memory.hpp defines a variable memory_heap which causes linker issues due to multiple definitions if this file in included in more than one cpp file. This prevents us from using string.hpp (which internally uses memory.hpp). Problem does not occur in smart contracts if we have only one source file but test_api does not link anymore because it has multiple sources.

**Comment by bytemaster** [comment]
My understanding is that we would not build multiple .o files from multiple cpp files.  Instead, all CPP files for a contract should be built as a single compilation unit. If developers want to divide up their cpp files into "libraries" then it would look like this:

```
/** @file library.cpp */
#include <memory.cpp>
#include <contract.cpp>
 ```

Then you would simply compile library.cpp and be done with it.

Smart contracts shouldn't be all that big where multiple compilation units are required.

**Comment by brianjohnson5972** [comment]
If you look at api_test, there are multiple cpp files that end up creating
.bc files, which feed into one .wast file.

**Comment by bytemaster** [comment]
yeah, we need to make sure there is only one .bc

**Comment by brianjohnson5972** [comment]
Well my fix is fine too be in the code, but we should make a new task to
change was.cmake to make only one .bc file

On Oct 19, 2017 4:50 PM, "Daniel Larimer" <notifications@github.com> wrote:

yeah, we need to make sure there is only one .bc

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/EOSIO/eos/issues/578#issuecomment-338048056>, or mute
the thread

**Comment by brianjohnson5972** [comment]
Is this necessary for the STAT release? If it is, is it a nice to have, or
is it a must have?

**Comment by brianjohnson5972** [comment]
I should have looked more closely before I responded above.  So each *.cpp file is compiled to bitcode in a *.bc file, then all of the *.bc files are linked into a <target>.bc file (which for most of our contracts ends up compiling <target>.cpp to <target>.bc, then linking <target>.bc and overwriting it)

@bytemaster Is this what you were thinking should happen?

**Comment by heifner** [comment]
I took some time to look into this and I could not find a way to create a true global in wasm via c++. Extern doesn't work, static local in a function doesn't work, etc. However, if we go with Dan's recommendation above:

> My understanding is that we would not build multiple .o files from multiple cpp files. Instead, all CPP files for a contract should be built as a single compilation unit.

Then the need for a true global is not needed as there is only one compilation unit. Therefore, Brian is going to rework the cmake instructions so that only one compilation unit is in play. This will then allow the existing memory.hpp to work.
