### ISSUE TITLE
Sync some contracts transactions from mainnet

### ISSUE THREAD

**Issue by jacktang** [EOSIO/eos#5784]
Hello,

Follow the guide(https://medium.com/@cc32d9/running-a-full-eos-mainnet-node-d7da2d3b154f) I setup the synchronization with mainnet. However, in my dapp, I only want to watch some smart contracts' transactions. So my questions are:

1) Can I sync data from some specified block rather than block 0?
2) Can I filter transactions using contract address(account name)? I just read `chain_plugin` source code, and don't understand `contract-whitelist` option very much.

Thanks!

**Comment by jgiszczak** [comment]
You can not sync to the chain without starting from block 0.

To see only some contracts' transactions, simply name each account in your nodeos config.ini:
```ini
contract-whitelist = someaccount1
contract-whitelist = someaccount2
contract-whitelist = someaccount3
```
where `someaccount1` is the account on which `set contract` was executed for the contract you are interested in.  You may have as many or as few `contract-whitelist =` entries as you need.

To maintain the sanity of your node, you should include whitelist entries for all system contracts:
```ini
contract-whitelist = eosio
contract-whitelist = eosio.token
contract-whitelist = eosio.msig
```
You probably also want to see activity generated by those accounts, so you should include corresponding author-whitelist entries:
```ini
author-whitelist = someaccount1
author-whitelist = someaccount2
author-whitelist = someaccount3
```

You definitely want to see activity generated by the system accounts:
```ini
author-whitelist = eosio
author-whitelist = eosio.token
author-whitelist = eosio.msig
```

**Comment by jacktang** [comment]
@jgiszczak thanks for the reply :), and can I set some option to skip syncing the unrelated transactions? because the smart contract was deployed serval days ago, and it is easy to get the first block of the smart contract form mainnet block explorer.

**Comment by jgiszczak** [comment]
The whitelist functions as an exclusive list.  Anything not present in the whitelist will be ignored.

**Comment by jgiszczak** [comment]
`filter-on` is a setting for the `history_plugin`.  It determines what transaction history will be tracked.  `contract-whitelist` is a setting of the chain itself.  When there are entries in the whitelist, those and only those contracts are allowed to execute transactions on the chain, regardless of filter settings.

Sorry, `author-whitelist` was an error.  The correct setting is `actor-whitelist`.  I've edited my post.

**Comment by jgiszczak** [comment]
When replaying mainnet, the misaligned reference complaints from wabt are expected and benign.

If you are importing a block archive, the whitelist had no chance to take affect for any blocks in the archive, as they have already been processed.

If you are syncing with some existing public network, the whitelist and blacklist settings aren't all that helpful to you.  (And I should have said so at the beginning, since you did mention mainnet.  My apologies for the oversight.)  Instead, use the filter settings for the plugin you are using, such as `mongodb-filter-on =` and `mongodb-filter-out =`.  Your copy of the chain is required to have all transactions accepted by  its producers, even if they are of no interest to you.  However the data you track in some external searchable form can be filtered to include only transactions you care about.

Your dapp can then query your mongodb instance and it will retrieve only the transactions that match the filter settings and your search criteria.
