### ISSUE TITLE
Record not found when query table in contract but can find when query from cleos get table command line

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#5793]
We push action to contract from backend in order to process orders added by the other action of the contract. Therefore, we find new record by running `getTableRows` JS api every 200ms from the backend. However, around 1 out of 10 of the process action can not be run by smart contract successfully as the smart contract report that it doesn't find that record(fetch by id). We then try to push the action again after several seconds and it would success. May I know why would this happen?

**Comment by jgiszczak** [comment]
Verify your JS query matches the cleos query, especially that the key upper and lower limits are the same and that the row limit is the same.  The Javascript query may be too large to be serialized, or the record may be outside of the key limits being used.

**Comment by taokayan** [comment]
This is a normal behaviour. You have 2 transactions A & B, in which transaction B depends on the results of A. But since you're making transaction too fast, it's not guarantee that A will be always executed before B, as re-ordering might happens if transaction fails subjectively due to exceed of block resource. Furthermore, due to decentralized nature of blockchain, any transaction can't be confirmed until the block containing that transaction become irreversible. I suggest not to treat this as unexpected behaviour and have some retry logics to deal with it.
