### ISSUE TITLE
how to stop rollback when call transfer failure in a contract

### ISSUE THREAD

**Issue by neozju** [EOSIO/eos#5814]
there is a transfer action in my contract,if the receiver  is a contract and refuse to accept tokens,the whole transaction will rollback,but i don't want this,is there some way to ignore the transfer failure?
how to check a account is  a contract or just a account?

**Comment by neozju** [comment]
I know can't force the transfer,I just want ignore it and don't roll back the transaction.....cleos get code works,but i want get the hash in contract,how could I?  thanks!

**Comment by jgiszczak** [comment]
Rejected transactions get rolled back.  That's how the system works.  The changes the transaction attempts to make have been rejected, which means undoing them.

You can not get a contract has from within a contract.  At least not yet.  There is some discussion about enabling such a thing, but for now, there is no such feature, and since it doesn't exist now, it's a hard fork change to enable it.  Old versions of the system could not support contract code that does it, which induces a fork.  As such, it will be some time, if ever, that the feature is implemented and deployed.
