### ISSUE TITLE
THE CODE STYLE IS SUCKS

### ISSUE THREAD

**Issue by RyanKung** [EOSIO/eos#582]
ref: https://github.com/EOSIO/eos/blob/master/libraries/chain/fork_database.cpp#L27

```cpp

void     fork_database::start_block(signed_block b)
{
   auto item = std::make_shared<fork_item>(std::move(b));
   _index.insert(item);
   _head = item;
}

/**
 * Pushes the block into the fork database and caches it if it doesn't link
 *
 */
shared_ptr<fork_item>  fork_database::push_block(const signed_block& b)
{
   auto item = std::make_shared<fork_item>(b);
   try {
      _push_block(item);
   }
   catch ( const unlinkable_block_exception& e )
   {
      wlog( "Pushing block to fork database that failed to link: ${id}, ${num}", ("id",b.id())("num",b.block_num()) );
      wlog( "Head: ${num}, ${id}", ("num",_head->data.block_num())("id",_head->data.id()) );
      throw;
      _unlinked_index.insert( item );
   }
   return _head;
}

```

**WHY the indent is `THREE SPACES`;**

**AND WHY there are MULTI-SPACES in code;**

`void     fork_database::start_block(signed_block b)` (5 SPACES), and

`shared_ptr<fork_item>  fork_database::push_block(const signed_block& b)` (2 SPACES).

**ARE YOU CODING WITH MS WORD???**

**Comment by heifner** [comment]
See comment on PR #583.

**Comment by learnforpractice** [comment]
Maybe four is not a lucky number. :) That’s fine, you can adjust the tab width to three spaces.Also I recommend google c++ code style.https://google.github.io/styleguide/cppguide.htmlOn 20 Oct 2017, at 6:58 PM, Ryan Kung <notifications@github.com> wrote:ref: https://github.com/EOSIO/eos/blob/master/libraries/chain/fork_database.cpp#L27
void     fork_database::start_block(signed_block b)
{
   auto item = std::make_shared<fork_item>(std::move(b));
   _index.insert(item);
   _head = item;
}

/**
 * Pushes the block into the fork database and caches it if it doesn't link
 *
 */
shared_ptr<fork_item>  fork_database::push_block(const signed_block& b)
{
   auto item = std::make_shared<fork_item>(b);
   try {
      _push_block(item);
   }
   catch ( const unlinkable_block_exception& e )
   {
      wlog( "Pushing block to fork database that failed to link: ${id}, ${num}", ("id",b.id())("num",b.block_num()) );
      wlog( "Head: ${num}, ${id}", ("num",_head->data.block_num())("id",_head->data.id()) );
      throw;
      _unlinked_index.insert( item );
   }
   return _head;
}
WHY the indent is THREE SPACES;AND WHY there are MULTI-SPACES in code;void fork_database::start_block(signed_block b) (5 SPACES), andshared_ptr<fork_item> fork_database::push_block(const signed_block& b) (2 SPACES).—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EOSIO/eos","title":"EOSIO/eos","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/EOSIO/eos" class="">https://github.com/EOSIO/eos</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"THE CODE STYLE (#582)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/EOSIO/eos/issues/582" class="">https://github.com/EOSIO/eos/issues/582</a>"}}}
