### ISSUE TITLE
how to use inline_traces to confirm the result of the contract execution?

### ISSUE THREAD

**Issue by bixf** [EOSIO/eos#5820]
i see there are several fields in the inline_traces. which one can be that result? is there a example can show me what is like when contract failed during execution?
and , these details , is the only way to know for sure reading the source code? i am not familiar with c++ very much. thx

**Comment by taokayan** [comment]
These are two different things. "inline_traces" is an array of traces of all the inline actions within a transaction. It is likely a null array because most of the time an action likely won't invoke another action.

If you just want to know whether the transaction is executed or not, one of the simply ways is to look at the "status" in transaction receipt (not the trace).

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
