### ISSUE TITLE
How can develop EOS Dapp, but my computer only 4Gb RAM

### ISSUE THREAD

**Issue by stone89son** [EOSIO/eos#5854]
How can develop EOS Dapp, but my computer only 4Gb RAM?

**Comment by jgiszczak** [comment]
Start by using the precompiled Docker image.  From there, you can run a local testnet with only one node.  As long as you don't generate too much state data in your testnet, it will continue running.

Since you will likely need some sort of web-based UI for your dapp, use a small web server, such as lighttpd.  

Use a light weight text editor to edit your code rather than a full fledged IDE.

Finally, if you need a back end server for searching the chain, you could try the sql_db_plugin with SQLite 3.  That may not be working though.
