### ISSUE TITLE
V1.3.0版本的Fullnode 返回HTTP 400错误

### ISSUE THREAD

**Issue by discha** [EOSIO/eos#5858]
从1.2.4升级到版本1.3.0后，通过外网访问就会返回HTTP 400错误
XX.216.XX.113 - - [29/Sep/2018:12:34:51 +0000] "POST /v1/chain/get_info HTTP/1.1" 400 5 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
XX.216.XX.113 - - [29/Sep/2018:12:34:52 +0000] "GET /v1/chain/get_info HTTP/1.1" 400 182 "-" "-"

但内网访问正常：
10.1.94.56 - - [29/Sep/2018:12:05:30 +0000] "GET /v1/chain/get_info HTTP/2.0" 200 596 "-" "curl/7.58.0"
10.1.243.224 - - [29/Sep/2018:12:48:08 +0000] "GET /v1/chain/get_info HTTP/2.0" 200 596 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

在完全相同的网络环境下，1.2.4 版本的系统工作正常。

**Comment by readygo586** [comment]
@discha  in your test, 
1. nodeos version is v1.3.0 
2.  you access the nodeos from another computer?
Is my understanding right?

If yes, you can try the host = {0.0.0.0:8888} in postmain like below. In my environment, if this field is set, it return 200  otherwise return 400.

![image](https://user-images.githubusercontent.com/41469645/46247166-f5c04a80-c439-11e8-92c9-1a868e97ec39.png)

**Comment by wuyahuang** [comment]
try to add http-validate-host = false to config.ini

**Comment by discha** [comment]
添加http-validate-host = false到config.ini，解决该问题。
谢谢大家。
