### ISSUE TITLE
Multi index table performance

### ISSUE THREAD

**Issue by artjoma** [EOSIO/eos#5903]
Can somebody explain to me how multi index table fill with 10mil records inside with 9' uint64 fields? 
main questions:
1) lookup operations by primary index and secondary - performance degradation.
2) if split data to multiple scopes in the table, can it improve the situation?

**Comment by taokayan** [comment]
- the multi_index table is a key-value structure in which key (= table id + primary key) are ordered and storing using a tree structure. fields are serialized first into byte stream, so the number of fields will not significantly affect performance. there's another key-value struct to store the mapping of (contract + scope + table name) => (table id)

- secondary index are stored in another key-value structure in which key = (table id + secondary index position + secondary key +primary key) and value = (primary key). So performance degradation does happen because insertion/modification/removal need extra work to cater secondary indexing.

- unlikely improve, because all key accesses have logarithmic time. Splitting data will not result in less number of total rows. However scope can allow you to have one extra level of data hierarchy.
