### ISSUE TITLE
BadCast Error when Signing Transaction on RPC

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5904]
Hello,

How can I get a more verbose error when calling the RPC?  I am executing the http://127.0.0.1:8900/v1/wallet/sign_transaction

It returns: 
{"code":500,"message":"Internal Service Error","error:{"code":7,"name":"bad_cast_exception","what":"Bad Cast","details":[]}}

**Comment by jgiszczak** [comment]
Try adding `--verbose-http-errors` to your keosd command line.  Note you'll have to launch keosd yourself, rather than just using the one cleos launches automatically.

If that doesn't get you everything you need, your best bet is to use `cleos` with `--print-request` to see what it sends when it's signing a transaction, and compare it to what you're sending.
