### ISSUE TITLE
Verifying calculated CPU usage

### ISSUE THREAD

**Issue by gBaGu** [EOSIO/eos#5926]
Is it possible for BP to overcharge CPU usage of my transaction?
If so, is there any way for me or other BPs to check if CPU usage was calculated right?

**Comment by taokayan** [comment]
Theoretically they can, but this is unlikely to happen because this will make the network unhealthy and would not be any benefit to the BP.

There's no way to check for this as CPU usage is subjective. so each BP has to trust the CPU usage in the transactions of the block produced by other BPs.

**Comment by gBaGu** [comment]
I have some doubts about BP not having benefit from overcharging some account`s CPU usage.

Let's consider the situation when I want to do some damage to concurrent dApp.
I`m going to some BP, give him money and he starts to overcharge transactions to that dApp (for example by 100%).

So, if we assume that dApp has CPU bandwidth of x tx/hour and all of it`s transactions evenly distributed in time (each BP executes x/21 tx/hour)
We have a situation where that dApp will start to consume CPU bandwidth of x+x/21 tx/hour, which is more than dApp developers has estimated and could potentially cause some problems.
In such situation malicious actions of BP are unprovable because CPU usage is subjective.

The question is: What are the incentives for BP not to do such things?

**Comment by wanderingbort** [comment]
In most public EOSIO-based networks, the BPs are heavily montitored and
ranked based on their CPU billing.  Some auditors do this by crafting
benchmarks others do it by taking statistical measure of all the actions on
the chain.

A dApp specific attack would be identified by it's variation from the
clustered performance of similar BPs and a less specific attack would be
seen as operational incompetence that affects the whole network.

In both cases, because there is a strong commitment by the BPs to these
values, and independent auditors monitoring constantly, it is unlikely but
not impossible to use them offensively.  Theoretically, in a EOSIO-based
network which elects BPs, a BP risks their candidacy (and any long term
revenue that may imply) by agreeing to attack a dApp.

**Comment by gBaGu** [comment]
Understood.

Thank you all for the answers!

**Comment by jgiszczak** [comment]
Note that you can become an auditor yourself.  For a relatively precise audit, you can replicate the hardware of the BP of your choice, run your own nodeos, and submit transactions to your private network and compare the resulting CPU usage to the reported usage by the BP(s).  The resulting billed usage should be very similar to the billed usage of the BP you are comparing against.

If you don't want to go to the expense of reproducing the relatively high end machines the BPs use, you can still run nodeos on your own hardware and compare its results to the BP-reported usage.  Your own hardware is almost guaranteed to be slower than the BPs, so the resulting data gives you a very reasonable upper bound.  An honest BP should be at least as good as your own equipment.  If a BP starts billing CPU usage consistently higher than the slower CPU you are testing with, that's suspicious and justifies a detailed investigation.
