### ISSUE TITLE
Can not catch up with blocks when enabled history plugin？

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#6050]
Hi, we meet a problem: 
our three nodes which enables history-plugin, can't catch up with blocks. we almost far behind 5000~8000 blocks.
![image](https://user-images.githubusercontent.com/11972366/47138049-e9b60300-d2ea-11e8-80d9-e32d65e2d333.png)

we find that our machine's net in went down. I wonder there are something wrong between these conditions. Dose anyone know this？
![image](https://user-images.githubusercontent.com/11972366/47138000-c0957280-d2ea-11e8-973e-52ae15dc4711.png)

**Comment by brianjohnson5972** [comment]
history_plugin has been deprecated since it will eventually use up all your ram.  The recommendation is to use the mongodb_plugin and use mongodb to cache information about the blockchain, but even just maintaining the mongodb cache requires a lot of resources.  So if you have a problem with populating mongodb you will likely need a faster machine.
