### ISSUE TITLE
How to accurately calculate the RAM consumed by other users in my contract?

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#6087]
I am currently deploying a contract, and then let other users store data in me. How to accurately calculate the RAM consumed by other users in my contract?

**Comment by jgiszczak** [comment]
EOS Canada has created [eosq](https://eosq.app/) to help answer this question.  Otherwise, you'll need to study the implementation of [multi_index](https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/multi_index.hpp) to derive RAM consumption information.  At present there is no comprehensive documentation of exactly how RAM is used when storing contract state.
