### ISSUE TITLE
how to efficiently retrieve large amounts of data from multiindex ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#6091]
I am building an EOSIO dapp which store millions of records in the multiindex table, I have to feed this data to the analytics layer for analysis. What is the efficient and fastest way that I can fetch all this millions of rows of data from the multiindex table?

**Comment by jgiszczak** [comment]
You may want to rearchitect.  RAM on mainnet costs ~$0.533 USD per KiB as of this posting.  Millions of records would cost you hundreds of thousands of dollars or more, depending on your record size.

**Comment by jgiszczak** [comment]
Bearing in mind the previous comment, the most efficient way to manipulate millions of rows in RAM is to write a custom nodeos plugin and do as much of the required manipulation as possible in native data formats.  Conversions to and from text representations should be kept to an absolute minimum.

**Comment by sivachaitanya** [comment]
btw can you explain the reason why reads are going as transaction and are rate limited whereas ethereum or other blockchains allows free reads from a running local full node ? @jgiszczak  @taokayan

**Comment by jgiszczak** [comment]
The software is identical for all nodes, so there is no differentiation between public and private nodes.  The software protects itself from denial of service attacks by throttling the read rate.

Reads are slow because of the JSON marshalling required for the RPC API.  The CPU time required is extensive and therefore limited to be sure the node continues running normally for all users.

Demux is a third party plugin.  You'll want to consult its documentation for how to use it.
