### ISSUE TITLE
how to get the date from time_point in contract?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#6096]
Is there instances ?

**Comment by jgiszczak** [comment]
`time_point` is designed to store microseconds since an epoch.  The value may be retrieved using the `time_since_epoch()` accessor.  To retrieve it in seconds, use `sec_since_epoch()`.  How to turn that into a date depends entirely on how you instantiated the object.  You must know what epoch you used.

See also [system.h](https://github.com/EOSIO/eos/blob/f9a3d023c05d6b7984cbd7263a5a39e650c87e90/contracts/eosiolib/system.h#L74).

**Comment by yankunsam** [comment]
I use time_since_epoch(), but I have no idea to convert this timestamp to date(string). I can call stand library. 

So is there some solutions ? Thanks

**Comment by jgiszczak** [comment]
[http://lmgtfy.com/?q=C%2B%2B+how+to+convert+microseconds+to+date+string](http://lmgtfy.com/?q=C%2B%2B+how+to+convert+microseconds+to+date+string)

**Comment by oasis-eos** [comment]
@jgiszczak  I will have a try. Thanks!
