### ISSUE TITLE
Work on mainnet

### ISSUE THREAD

**Issue by SavostinVladimir** [EOSIO/eos#6121]
Hello! Can I create and connect to EOS mainnet my own node?
The aim is getting info about latest blocks on EOS mainnet as faster as possible!
Should I use the cleos to connect for any main node, such as https://www.eosnewyork.io/? Or can I use for this purpose my own node, but I don't know how...
I suppose if there is a way to use my own nodeos to connect mainnet it will be faster... But I'm not sure that is possible
Thank you!

**Comment by jgiszczak** [comment]
Yes, you can run your own full node.  Configure nodeos with `p2p-peer-address =` entries in the config file for the network you wish to synchronize with.  For mainnet, a list of public p2p nodes may be found [here](https://eosnodes.privex.io/).  You should configure just a few nodes, and remove any that reject connection.  You'll also need to provide a `--genesis-json` argument to `nodeos` on first startup with a copy of the network's genesis.json.  Mainnet's file can be found [here](https://github.com/CryptoLions/EOS-MainNet/blob/master/genesis.json).  If you wish to synchronize with Jungle Testnet, links to their genesis.json and peers are available on their Telegram channel.

`cleos` connecting to your local node is generally faster since there are numerous round trips in the protocol, all of which benefit from lower ping times.  In addition, you may run custom plugins in a local `nodeos` which can provide fast access of your own design.

Note that synchronizing with any long-running EOS.IO-based network, including mainnet, takes days and many gigabytes of disk space.

**Comment by SavostinVladimir** [comment]
> Yes, you can run your own full node. Configure nodeos with `p2p-peer-address =` entries in the config file for the network you wish to synchronize with. For mainnet, a list of public p2p nodes may be found [here](https://eosnodes.privex.io/). You should configure just a few nodes, and remove any that reject connection. You'll also need to provide a `--genesis-json` argument to `nodeos` on first startup with a copy of the network's genesis.json. Mainnet's file can be found [here](https://github.com/CryptoLions/EOS-MainNet/blob/master/genesis.json). If you wish to synchronize with Jungle Testnet, links to their genesis.json and peers are available on their Telegram channel.
> 
> `cleos` connecting to your local node is generally faster since there are numerous round trips in the protocol, all of which benefit from lower ping times. In addition, you may run custom plugins in a local `nodeos` which can provide fast access of your own design.
> 
> Note that synchronizing with any long-running EOS.IO-based network, including mainnet, takes days and many gigabytes of disk space.

**Comment by SavostinVladimir** [comment]
Thank you! Would you say how much disk space is required for full synchronizing with mainnet?? approximately...

**Comment by jgiszczak** [comment]
The gzip-compressed block log for mainnet is 41.81 GiB as of this posting.
