### ISSUE TITLE
Is EOS supporting Open source ?

### ISSUE THREAD

**Issue by sriharikapu** [EOSIO/eos#6126]
Cheers Everyone! 

I had been asking a lot of people and even the EOS telegram groups about the certain parts of EOS code which seems to be not transparent. Especially with the Repo of Genesis. "https://github.com/EOSIO/genesis/edit/master/README.md" 

This is the documentation page at the URL: https://eosio.github.io/genesis/

![screen shot 2018-10-24 at 5 07 45 pm](https://user-images.githubusercontent.com/6247133/47421397-19fe1580-d7b3-11e8-891c-501e070a056f.png)

When I look at the repo its either private or taken down.

![screen shot 2018-10-24 at 5 09 01 pm](https://user-images.githubusercontent.com/6247133/47421483-431ea600-d7b3-11e8-83e7-157a4b30f106.png)

I would be better if the repo is opensource too.

**Comment by jgiszczak** [comment]
The genesis repository was taken over by the community.  Its purpose was to generate the snapshot from Ethereum used to bootstrap mainnet from the ICO data.  Since block.one does not endorse any particular instantiation of the EOS.IO software, the software needed to extract the Ethereum snapshot was more appropriately maintained by others.
