### ISSUE TITLE
how to get the right table after contract upgrade

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#6156]
When I add a new item in table. For the previous items,
 "get table" will report:
```
2018-10-26T08:19:41.590 thread-0   main.cpp:3008                 main                 ] Failed with error: Out of Range (8)
read datastream of length 118 over by 1
```

**Comment by firesWu** [comment]
you should erase table data before you change table struct.

**Comment by yankunsam** [comment]
@firesWu  Maybe there should have a better solution.

**Comment by jgiszczak** [comment]
You own your data.  If you wish to change the format of your data, you must migrate your data.  You may migrate by erasing it all and reuploading it or by creating a migrate action that copies rows from the old table format to the new format.  Since only you know what transformation is required, you must write this migration function yourself.
