### ISSUE TITLE
my->pre_accepted_block_channel.publish(blk);

### ISSUE THREAD

**Issue by iamanopensourcer** [EOSIO/eos#6157]
I saw the code above,but I can't find code like this : 
app().get_channel<channels::pre_accepted_block>().subscribe()

_Originally posted by @iamanopensourcer in https://github.com/EOSIO/eos/issues/6153#issuecomment-433338719_

**Comment by jgiszczak** [comment]
`my->chain->pre_accepted_block.connect` is called [here](https://github.com/EOSIO/eos/blob/f9a3d023c05d6b7984cbd7263a5a39e650c87e90/plugins/chain_plugin/chain_plugin.cpp#L642).

You should not be filing issues just because you can't find what you're looking for while exploring the code.  Ask on the Telegram developers channel or on StackExchange.
