### ISSUE TITLE
recover_key returns truncated public key

### ISSUE THREAD

**Issue by miguelmota** [EOSIO/eos#6181]
I'm trying to derive the public key from the signature using eosio `recover_key` but the result I get is truncated. Here's the action:

```c++
  void ecrecover(std::string data, const signature &sig)
  {
    checksum256 digest;
    sha256(&data[0], data.size(), &digest);
    uint8_t pub[34];
    auto res = recover_key(&digest, (char *)&sig, sizeof(sig), (char*)pub, 34);
    printhex(pub, sizeof(pub));
  }
```

payload

```
cleos push action myaccount111 ecrecover '["hello", "SIG_K1_K3c9eTFA34HwqN1xNxr4ngbTzckSoDYWz2cYMneyMTTJLqfQ1yAQS1M4EYUJDqhVgzC1cN65mwBRqau2EhDBirWodhW8xb"]' -p helloworld54@active
```

Expected

```
0275b197d4f3543972f464453c13531ddf568aa64a2f0b7dca2620b0c60acef3e04ccb7114
```

```js
const bs58 = require('bs58')
const pub = 'EOS5nKgVwRvRnjf4tyViZ61iydQ6CiFMoURta36RUk9hxi5wpAkLb'
const pubhex = bs58.decode(pub.slice(3))
console.log(pubhex.toString('hex'))
// 0275b197d4f3543972f464453c13531ddf568aa64a2f0b7dca2620b0c60acef3e04ccb7114
```

Actual

```
000275b197d4f3543972f464453c13531ddf568aa64a2f0b7dca2620b0c60acef3e0
```

You can see `4ccb7114` is truncated from the result and can't figure out why

**Comment by andriantolie** [comment]
It's because EOS Public Key is a base58check, the last 4 bytes is the hash of the public key. However, unlike Bitcoin where the checksum is calculated using double SHA256, EOS checksum is calculated using RIPEMD160.

If you calculate the RIPEM hash of '0275b197d4f3543972f464453c13531ddf568aa64a2f0b7dca2620b0c60acef3e0' (EOS public key is 33 bytes), you will find out that the result will be `4ccb71145236ade5290314581b17e45475f37d40` which matches the suffix shown in your decoded base58. You can try to use this to verify https://www.fileformat.info/tool/hash.htm?hex=0275b197d4f3543972f464453c13531ddf568aa64a2f0b7dca2620b0c60acef3e0

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by miguelmota** [comment]
@andriantolie makes perfect sense, thanks so much!
