### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations.

### ISSUE THREAD

**Issue by snehap007** [EOSIO/eos#6207]
`Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations Ensure that you have the related private keys inside your wallet and your wallet is unlocked.`

I am getting above error when i publish my contract on EOS network using the following command 
`cleos set contract eosio contracts/hello -p helllo@active`

I am referring https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts

I searched a lot on this issue but still getting the same issue.
Please guide me on this thanks in advance

**Comment by jgiszczak** [comment]
The linked tutorial does not tell you to use the hello contract and your attempt to adapt it to that contract did not succeed.  You must continue to use `-p eosio@active`, since it is the `eosio` account you are attempting to add the contract to.

If you still have the problem and wish to discuss further, please post it in [https://eosio.stackexchange.com](https://eosio.stackexchange.com). To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
