### ISSUE TITLE
Deprecation of history plugin with get_key_accounts

### ISSUE THREAD

**Issue by leordev** [EOSIO/eos#6238]
With the deprecation of the history plugin, we don't have a way to list all accounts for a given public key. It's required for the dapp to integrate with a wallet that uses EOSJS `JsonRpc.history_get_key_accounts(key)`.

The only way to solve this right now is to ask the user to enter manually the account/permission that he wants to use (very poor ux).

**Comment by ansigroup** [comment]
we added this support to our API for mongo plugin:
https://github.com/CryptoLions/EOS-mongo-history-API

http://history.cryptolions.io/#/paths/~1v1~1history~1get_key_accounts/post

**Comment by vjoke** [comment]
@ansigroup yes,  the collection pub_keys stores  the mapping between public_key and account_name, however, these records cannot be taken as 'confirmed' without checking against LIB.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
