### ISSUE TITLE
cleos inexplicit convert an eosio::name type but does not have a option to look it up by name type

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#6243]
cleos get table has a feature to implicitly convert a name type for indices as the lower bound and upper bound. That definitely helps with look up items with multiple index table.

But conceptually the lower bound and upper map to a numeric value concept well but not for string type. As when we are looking for a value by one name it is looking for a value instead of range. so you would have to add -L 1 and --key-type name to get the result. But for a name type key, the value associated is always unique hence singular. So the limit one is hacky and redundant

also the implicitly converting it is not currently explain in the usage, can we add a look up by the name instead of range for the name type such as a syntax like below?

cleos get table addressbook addressbook people --name alice
cleos get table addressbook addressbook people -N alice

**Comment by arhag** [comment]
Related: https://github.com/EOSIO/eos/pull/6262#issuecomment-437487855

PR #6285 which will be incorporated into the next minor release of eosio will allow you to do what you want: `cleos get table addressbook addressbook people -L alice -U alice` would give you all rows with a key of `alice`. In that case, since it is a primary key and therefore must be unique, you should only get back either 0 or 1 rows. But more generally with secondary keys, since they do not need to be unique, you would get back the rows with the secondary key that exactly matches the value passed into both the `lower_bound` and `upper_bound`.
