### ISSUE TITLE
Provide access to transaction id

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#6289]
Add function to C Contract API to provide transaction id

**Comment by arhag** [comment]
I'm not sure if from a long-term perspective we want to go down the route of encouraging access from within contracts to the information available in or derived from the full transaction data (which of course includes the transaction ID). That breaks certain abstractions we are considering such as being able to emulate the execution of a transaction dispatched from a contract without relying on the deferred transaction facility.

Granted, we have intrinsics that already access transaction data and therefore already break those potential abstractions. And we will have to support the current intrinsics for a long time. But I don't necessarily want to make the problem worse by adding even more intrinsics that go in a direction opposite to what we are thinking about eventually heading towards.

Also, this can already be implemented without a new intrinsic (and therefore without a consensus protocol upgrade) using the existing `transaction_size`, `read_transaction`, and `sha256` intrinsics. So maybe this issue is more appropriate for the eosio.cdt repository. For the convenience of the contract developers, we could add a helper function to eosiolib that does the transaction ID calculation using the previously mentioned intrinsics (and caches it in a static member so it only has to happen at most once per action execution). Then adding a new intrinsic to get a transaction ID becomes a matter only of performance optimization rather than enabling features.
