### ISSUE TITLE
Is the smart contract the basis of EOS?

### ISSUE THREAD

**Issue by imlaochen** [EOSIO/eos#6296]
Hi, everyone, I am a newcomer to EOS. I have recently read the official documentation. I have some doubts and would like to ask you.

1: Is the smart contract the basis of EOS?
I understand that all transactions are based on the behavior provided by smart contracts.
For example, the EOS token transfer is called the transfer method provided by the eosio.token smart contract. Specifically, who transfers the money is passed as the data parameter to the transfer action.

2:
 ```
--filter-on <receiver>:<action>:[<actor>]
```
At first, I thought that reciever was the recipient of the token transfer, but after reading the document carefully, I felt that I was wrong.
Because the transaction includes transfer, issue, sellram, buyram..., not just transfer.

Therefore, I think the meaning of these parameters is as follows:
Receiver: smart contract instance (eg eosio.token, eosio.system...)
Action: the method provided by the contract (eg transfer, sellram...)
Actor: the account that called the contract method

Is i understand right? Thanks.

**Comment by jgiszczak** [comment]
1. EOS does intentionally include as much of its functionality as possible in smart contracts in order to facilitate upgrades to the system without forcing a hard fork of the blockchain.  The account permissions system and accounts themselves are native, as are the frameworks that provide contracts and transactions.  The contract state storage system is native.  The fundamental data types for accounts, keys, and signatures are also native.  The chain itself is, of course, native, including the details of how blocks are constructed and incorporated into the chain by communicating them to other producing peers.  The transport that provides the RPC APIs is also native.  Most of the rest of the system in implemented in contracts.

2. Your interpretation of `filter-on` is correct.
