### ISSUE TITLE
multi_index bug??

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#6330]
I'm following these tutorials.
https://developers.eos.io/eosio-home/docs/data-persistence
https://developers.eos.io/eosio-home/docs/inline-actions
https://developers.eos.io/eosio-home/docs/sending-an-inline-transaction-to-external-contract

In above tutorial  'addressbook', 'abcounter' is contract account and 'alice', 'bob' is user account. 

When I run 'cleos push action addressbook upsert '["test123", "n3wbie", "h4ck", "street", "ci
ty", "country"]' -p test123', it works fine.

But when I run 'cleos push action addressbook upsert '["abcounter", "n3wbie3", "h4ck3", "street3", 
 "city3", "country3"]' -p abcounter', following error occurs.
' Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)'

What I'm thinking is, if there is account with smart contract that uses multi_index table, can not push action to itself because there is already pk in multi_index structure.

Am I right? or is it just a bug?

**Comment by jgiszczak** [comment]
The multi_index structure does not arbitrarily insert a record with the primary key of the account running the contract.  Presumably you are only part way through the Data Persistence tutorial, as the final form of the contract modifies an existing row rather than generating an error.  Odds are the error is precisely correct: you have already inserted a row with key 'abcounter', while following earlier steps in the tutorial.

If there isn't an existing row (and you can test by implementing the erase method in the tutorial and executing it), then it's most likely a permissions problem, rather than a defect in multi_index.  I don't know of any reason why the `require_auth( user );` call in `upsert()` would fail if `user` equals `_code`, but I suppose it's conceivable.

I recommend further experimentation.  It's very unlikely to be what you think it is, or it would have been noticed by now.

**Comment by newbieh4cker** [comment]
@jgiszczak 
I'm done with tutorials.

![image](https://user-images.githubusercontent.com/23703741/48668972-9d095600-eb3c-11e8-8343-bc6fcec6ff1a.png)

As you can see from picture above(addressbook contract is deployed on h4ckthewor2d account), there is row with 'h4ckthewor2d' as key, and even 'erase' action is causing problem.

**Comment by wangyilin1987** [comment]
I have the same problem.and don't know why! only in some account's pk. and same error happen after multi_index data been clean.
