### ISSUE TITLE
BUG when two accounts send action at the same time to modify multiindex table

### ISSUE THREAD

**Issue by afreshman** [EOSIO/eos#6344]
It took me several days to find the bug.

I got a table like this

    TABLE t {uint64_t key, name player1, name player2, uint64_t status};
when the contract recieved the specific action , It will gothrough the table to find if there is a row which `status == 1` and player2 is empty, if not exist, It will emplace one. now it has one row like this
    
    {"key" : 1, "player1" : "bob", "player2" : "", "status" : 1}

When next player send the action ,he will find the row above and modify the player2 and status. It supposed to be like this.

    {"key" : 1, "player1" : "bob", "player2" : "jack", "status" : 2}

The bug comes when two players send action at the SAME time, they could both find the row that `status == 1` and player2 is empty ! Then the one who modify the table first will be overwitten by the next one. It will becomes like this, jack was overwitten by tom.

    {"key" : 1, "player1" : "bob", "player2" : "tom", "status" : 2}

 I'm wondering why would two player both find the same row, cause when a player find it he will modify the status to 2. so the next player will never find this row. Even if they both find the row,  can we lock the table before we modify it? 

I've been suffering from this bug for a long time, does anyone has some good advice?

It's my code here.
https://github.com/afreshman/bugeos

**Comment by ijoywan** [comment]
your code seem does not take care of  `p.status == 2`  or `player2` is null

**Comment by afreshman** [comment]
> are you sure this is a nodeos bug? You can use `print` in your contract and run nodeos with `--contracts-console` to see your console message.
I think so. It appears when over 100 users, I can't simulate in my local. But When I keep querying the bet table, I got a row with same key and same timestamp, but the player2 changes. I use eosio_assert before modify , it doesn't work.

**Comment by jgiszczak** [comment]
Your code is not taking into account the fact that there are multiple producers in the system.  Until a block or action propagates, they can not know that one of your users has issued an action that modified a row.  This can easily result in two actions submitted at the same time modifying the same row twice, because different nodes receive their actions and execute them independently.  They're guaranteed to be applied in the same order on all nodes when they're finally added to the blockchain, but nothing in your code prevents them from modifying the same row twice.  Your architectural flaw is your attempt to use `status` as a mutex when the processes accessing it aren't even on the same machine.

You will need to deal with synchronization yourself.  There's nothing in the libraries that can help with that.  The simplest solution is to enter bets on independent rows, then run a matching engine yourself to pair them up based on their timestamps.  Having them edit the same row is an exercise in frustration.  Read up on Lamport timestamps and vector clocks for attempts to solve the problem.  You will discover that even these techniques are only eventually consistent and can lose data.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
