### ISSUE TITLE
--suppress-duplicate-check  regression

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#6345]
deploy the same contract again with the following option:

cleos set contract --suppress-duplicate-check addressbook /Users/hanliu/docs_task/onboarding/inline_action/addressbook 

Got error:

Error 3160008: Contract is already running this version of code

shouldn‘t the cleos just re-deploy the code？

**Comment by dixia** [comment]
referred in a different issue #6343

**Comment by jgiszczak** [comment]
`--suppress-duplicate-check` only suppresses the client side duplicate check.  It removes one round trip exchange to the server and back again.  Nothing can suppress the server's duplicate check, which is what you are seeing.

The most common cause of duplicate failures is modifying something in your contract code that the compiler is optimizing out.  Changing it makes no difference to the compiled code, since the compiler removed it.  Generally speaking you must change code that is actually being used before your contract will compile distinctly differently.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
