### ISSUE TITLE
Can't access keosd through rpc

### ISSUE THREAD

**Issue by ChrysmOre** [EOSIO/eos#6415]
For some reason I can no longer connect to keosd through localhost:5555 like I used to. I have removed and rerun the docker image from scratch but nothing changes. Nothing else is using port 5555. There isn't an ~/eosio-wallet folder like there usually is to check the config.ini. This happened spontaneously everything used to work fine. I'm using ver 1.2.6. Any ideas?

**Comment by jgiszczak** [comment]
By default keosd listens on port 8900 in the docker image.  I'm not aware of a time when the default configuration made it available on port 5555.  Sounds like a site-local customization that you'll need to reapply if you still prefer that port.

I strongly recommend updating to v1.4.4.  There have been numerous bug fixes since v1.2.6, including some security fixes.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
