### ISSUE TITLE
state history: deferred and executed in same block

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#6446]
Handle transactions which are deferred and executed in the same block.

@arhag: create a way to test this situation

**Comment by arhag** [comment]
Good news, further analysis revealed that this isn't a problem. 

A contract-generated transaction scheduled and retired in the same block isn't a problem in the state history plugin since it only has one transaction trace in this case (that of the retired deferred transaction).

A delayed input transaction would be a problem for the state history plugin if it was to be scheduled and retired in the same block since the retired trace with overwrite the scheduled trace. But it shouldn't be possible for a delayed input transaction to be scheduled and retired in the same block.

The only way to indicate that an input transaction is delayed is by setting a non-zero value for the `delay_sec` field. The smallest possible value is 1, which would enforce that the delayed input transaction could not retire until at least the next block.

**Comment by hama** [comment]
when will happen a  contract-generated transaction scheduled and retired in the same block ?

**Comment by hama** [comment]
when will happen a contract-generated transaction scheduled and retired in the same block ?
@tbfleming
