### ISSUE TITLE
Missing Wallet API plugin

### ISSUE THREAD

**Issue by NathanKim91** [EOSIO/eos#6462]
I am testing "[Local Multi-Node Testnet](https://developers.eos.io/eosio-nodeos/docs/local-multi-node-testnet)" now.
However when I try to following shell command, there is some problem

<shell command>
cleos --wallet-url http://127.0.0.1:8899 push action eosio setprods "{ \"schedule\": [{\"producer_name\": \"inita\",\"block_signing_key\": \"EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg\"}]}" -p eosio@active
executed transaction: 2cff4d96814752aefaf9908a7650e867dab74af02253ae7d34672abb9c58235a  272 bytes  105472 cycles
#         eosio <= eosio::setprods              {"version":1,"producers":[{"producer_name":"inita","block_signing_key":"EOS6hMjoWRF2L8x9YpeqtUEcsDKA...

---

<my problem>

$ cleos --wallet-url http://127.0.0.1:8899 push action eosio setprods "{ \"schedule\": [{\"producer_name\": \"inita\",\"block_signing_key\": \"EOS6RxxLBrMG6bCBtC8VSXYiepD6zwFsaUNMBf3DjbC8xorBoqyHj\"}]}" -p eosio@active
Error 3110002: Missing Wallet API Plugin
Ensure that you have eosio::wallet_api_plugin added to your node's configuration!
Otherwise specify your wallet location with --wallet-url argument!
Error Details:
Wallet is not available

---

There is specified the wallet url. However why can not find the wallet api? 
Let me know what am I missing now.
Thanks

**Comment by jgiszczak** [comment]
Normally you do not need to specify wallet-url.  `cleos` by default launches keosd and communicates with it via a Unix socket, rather than TCP, to avoid exposing wallets quite as widely.  Use the same settings you were using in earlier tutorials when you loaded the private key for the `eosio` account into your wallet.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
