### ISSUE TITLE
Capture inline action data

### ISSUE THREAD

**Issue by vingo555** [EOSIO/eos#6521]
I wrote one contract and I want to use inline action to transfer token to another account and get the transfer MEMO after the action is done.

My question is : 
How can i get the inline action data ?  I not found the action transfer data inside the block.
Is that possible to get the inline action data inside contract ?

**Comment by vingo555** [comment]
I call the inline transaction code , I can't find the eos transfer action inside the block. while the transfer is really successful.


eosio_assert(total.is_valid(), "invalid quantity");
        eosio_assert(total.amount > 0, "must transfer positive quantity");        

        log("Start to transfer: \n");

        action(permission_level{player, N(active)}, N(eosio.token),
            N(transfer), std::make_tuple(player, _self, total, msg)).send();

**Comment by andriantolie** [comment]
Hi @vingo555,
> How can i get the inline action data ? I not found the action transfer data inside the block.
- The inline action information is not included inside a block, this is because the information can be inferred by the generating transaction when you do a replay
> Is that possible to get the inline action data inside contract ?
- If it is inside the same action which generates the inline action, you should have the information of the payload before you send it. If it is under different action, as far as I know there's now way for you to get the payload of inline action generated by another action.
> I wrote one contract and I want to use inline action to transfer token to another account and get the transfer MEMO after the action is done.
- If this is the use case that you want, and either the sender/ receiver is your contract, I think one possible way that you can do is by utilising the `require_recipient` of eosio.token::transfer. The `require_recipient` will forward the action payload to both the sender & receiver `apply` handler, and from there you can do whatever you want with the payload.
