### ISSUE TITLE
我查看表数据的时候为什么会出现这个错误，查看其它的表又没问题的Error 3010014: Invalid symbol  Error Details:precision 219 should be <= 18 Unable to unpack built-in type 'asset' while processing 'gacha.betamount'

### ISSUE THREAD

**Issue by danty94** [EOSIO/eos#6534]

**Comment by danty94** [comment]
![image](https://user-images.githubusercontent.com/34644760/50517510-98e13880-0aeb-11e9-8d8f-deeb5ef7df1c.png)

**Comment by jgiszczak** [comment]
This is caused by data that was written by a different version of the contract ABI.  It can no longer be deserialized correctly using the currently loaded ABI.  If it is an account you control, you should load a version of the contract that can read both formats and migrate the data from the old to the new format.  If it is an account you do not control, you will need to find the old format and deserialize the hexadecimal string yourself.

**Comment by evsward** [comment]
I met the same issue.  Are there any news?

**Comment by evsward** [comment]
I add a new field in the multi_index table and test in local net.  I've tried two ways:
- erase all records of table
- restart a new chain

The issue is still there.
```
Error 3010014: Invalid symbol
Error Details:
precision 112 should be <= 18
error unpacking eosio::chain::symbol
Error unpacking field sym
error unpacking eosio::chain::asset
Unable to unpack built-in type 'asset' while processing
```

**Comment by jgiszczak** [comment]
What does the table look like when you use `cleos get table` to retrieve the data?

**Comment by evsward** [comment]
"cleos get table" got the error just like the issue description. 在2019年02月01日 04:48，jgiszczak 写道： What does the table look like when you use cleos get table to retrieve the data? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jgiszczak** [comment]
As I said originally, the ABI must match the table definition, or deserialization won't work.
