### ISSUE TITLE
state history: deferred and executed in same block

### ISSUE THREAD

**Issue by hama** [EOSIO/eos#6561]
When will happen a contract-generated transaction scheduled and retired in the same block ?

**Comment by taokayan** [comment]
This is possible but unlikely to happen. Because deferred transactions are pushed in start_block function in producer plugin in the following order:

- previously unapplied transactions will be pushed first
- get all deferred transactions & pending incoming transactions up to this point
- push deferred transactions alternating with pending incoming transactions, configureable with parameter "_incoming_defer_ratio"

After start_block, other real-time transactions will be pushed into the current pending block. However, deferred transactions will not be pushed until the next "start_block" call.

Therefore, unless your transaction was rolled back and became unapplied transactions, deferred transaction will not be executed in the same block.

**Comment by hama** [comment]
Got it, Thank you, @taokayan
