### ISSUE TITLE
on startup nodeos needs to validate config.ini based on loaded plugins

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#6592]
If I have a config.ini that has the following items, for example, it logically does not make sense

```
[...]
#plugin = eosio::producer_plugin
producer-name = xxxxxxxxxx
signature-provider =  xxxxxxxxxxxxxxxxxxxxxx
```

The producer plugin is commented out, but we have a producer name and signature provider, which only work with the producer plugin.   nodeos should complain that producer-name and signature provider are invalid options... because the options only apply to the producer plugin and the producer plugin is not loaded.

Doing this sort of validation would prevent operational errors.

Above is only an example... applies to all configuration options which belong to a specific plugin.  Also applies to command line arguments.

**Comment by taokayan** [comment]
```producer_plugin``` is implicitly included in nodeos, and as a result,  ```producer-name``` is a valid option.
nodeos will warn users for invalid options, for example:
```
error 2019-01-15T09:47:39.540 thread-0  main.cpp:135                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option '--aaa=1'
```

**Comment by spoonincode** [comment]
The following plugins are always enabled in nodeos: chain_plugin, http_plugin, net_plugin, and producer_plugin. The original report probably should have used bnet_plugin, login_plugin, txn_test_gen_plugin, or such as a better example. For example, `bnet-no-trx = false` is allowed even when the bnet_plugin is disabled.

This is a reasonable request and should be considered. However, such a change cannot cleanly be performed at the moment because the default config generated always contains every config item -- we would break every default config.
