### ISSUE TITLE
how to get code of a contract account?

### ISSUE THREAD

**Issue by lixiaodong** [EOSIO/eos#6594]
There is so many attacks on dapps these day.

i have my questions here.

how do i prevent a account that is deployed a contract to transfer to my contract account?

how to get code of a contract account ? the function is the same like 'cleos get code'

i searched EOSIO repo,I cannot find.

somebody help??

**Comment by jgiszczak** [comment]
> how do i prevent a account that is deployed a contract to transfer to my contract account?
You can not.  Arbitrary actions can be pushed to any contract account.  Your contract must deal with them.  If you are using the recommended macros for constructing your `apply()` function, your contract will ignore unrecognized actions.  For recognized actions, your code must account for and deal with malformed actions.
> how to get code of a contract account ? the function is the same like 'cleos get code'
There is no way to retrieve the source code of a contract from the chain unless the contract has an action in it to retrieve a copy of its own code.  Otherwise it is up to the author of the contract to make source code available, and verification of that source code is a manual process of compiling it and comparing it to the WASM retrieved from the chain.

**Comment by lcg635** [comment]
Is there a way to determine if an account has deployed a contract?
I hope that only the account that has not deployed the contract can use my dapp.

@jgiszczak

**Comment by jgiszczak** [comment]
There is no reliable way to determine within a contract that another account has a contract deployed.
