### ISSUE TITLE
The EOSIO/eos repository on docker hub not updated for a month.

### ISSUE THREAD

**Issue by LeonSha** [EOSIO/eos#6627]
It is still version 1.5.2. Or this repository  will not be updated anymore?

**Comment by got3nks** [comment]
Looks like they discontinued the images on the Hub repository. But I'm having issues with the builiding of the image:

```
root@server:/home/eos/git/eos/Docker# docker build -t eosio/eos:1.6.0 --build-arg branch=1.6.0 .
Sending build context to Docker daemon  30.21kB
Step 1/16 : FROM eosio/builder as builder
latest: Pulling from eosio/builder
6b98dfc16071: Already exists
4001a1209541: Already exists
6319fc68c576: Already exists
b24603670dc3: Already exists
97f170c87c6f: Already exists
989c07c6edff: Pull complete
3cb5f57fd105: Pull complete
17e8c5aa3340: Pull complete
865a94241630: Pull complete
78c0dba4c581: Pull complete
80dfca640586: Pull complete
e56cf35e4a67: Pull complete
ec1eb8c6a441: Pull complete
Digest: sha256:46a332fb8dd9cfc6557e38473645dd1d8d5ca1813ccee8057714ebed7014e6f3
Status: Downloaded newer image for eosio/builder:latest
 ---> 6ba80d657683
Step 2/16 : ARG branch=master
 ---> Running in 24e844c0cf46
Removing intermediate container 24e844c0cf46
 ---> 308b25f75ca4
Step 3/16 : ARG symbol=SYS
 ---> Running in 50e80fa24de9
Removing intermediate container 50e80fa24de9
 ---> 2a75dce8ce62
Step 4/16 : RUN git clone -b $branch https://github.com/EOSIO/eos.git --recursive     && cd eos && echo "$branch:$(git rev-parse HEAD)" > /etc/eosio-version     && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++        -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build -DBUILD_MONGO_DB_PLUGIN=true -DCORE_SYMBOL_NAME=$symbol     && cmake --build /tmp/build --target install
 ---> Running in fc4022ae4460
Cloning into 'eos'...
fatal: Remote branch 1.6.0 not found in upstream origin
The command '/bin/sh -c git clone -b $branch https://github.com/EOSIO/eos.git --recursive     && cd eos && echo "$branch:$(git rev-parse HEAD)" > /etc/eosio-version     && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++        -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build -DBUILD_MONGO_DB_PLUGIN=true -DCORE_SYMBOL_NAME=$symbol     && cmake --build /tmp/build --target install' returned a non-zero code: 128
```

**Comment by LeonSha** [comment]
There is no branch 1.6.0, but there is a tag called v1.6.0. You can try this `docker build -t eosio/eos:v1.6.0 --build-arg branch=v1.6.0 .`

**Comment by got3nks** [comment]
https://github.com/EOSIO/eos/blob/master/Docker/README.md this needs to be updated then. ;)

**Comment by limulidae** [comment]
docker build -t eosio/eos:1.6.x --build-arg branch=release/1.6.x .

[538/1396] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o
FAILED: libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o 
/usr/bin/clang++   -I/eos/libraries/chain/include -Ilibraries/chain/include -I/eos/libraries/chain/../wasm-jit/Include -I/eos/libraries/wabt -Ilibraries/wabt -I/eos/libraries/fc/include -I/usr/local/include -I/usr/include/openssl/include -I/eos/libraries/fc/vendor/websocketpp -I/eos/libraries/fc/secp256k1/upstream -I/eos/libraries/fc/secp256k1/upstream/include -I/eos/libraries/chainbase/include -I/eos/libraries/wasm-jit/Source/Runtime/../../../chain/include -I/eos/libraries/softfloat/source/include -I/eos/libraries/softfloat/source/8086-SSE -I/eos/libraries/softfloat/build/Linux-x86_64-GCC -I/eos/libraries/builtins -I/eos/libraries/builtins../softfloat/source/include -Wall -Wno-invalid-partial-specialization -fcolor-diagnostics -O3 -DNDEBUG   -fcolor-diagnostics -std=gnu++14 -MD -MT libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o -MF libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o.d -o libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o -c /eos/libraries/chain/wasm_interface.cpp
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.1-10 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:

**Comment by andriantolie** [comment]
Hi @LeonSha, docker images in docker hub are deprecated and no new build will be generated starting from 1st January 2019. They will be removed on 1st June 2019.
