### ISSUE TITLE
injected checktime amplification of 2x

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#6661]
The "intrinsic" (nodeos exported wasm functions) wrappers always call a checktime() before calling the host function.

https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/webassembly/wabt.hpp#L672-L677

However injected checktime calls are nothing more then intrinsic calls. This means when an injected checktime is performed it's done twice: once in the intrinsic wrapper, and then once for the actual checktime() call.

**Comment by spoonincode** [comment]
This only affects wabt.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
