### ISSUE TITLE
what's the network struct of EOS mainnet?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6662]
what's the network struct of EOS mainnet?
I have build network service which base on eos private network,but it sometimes shut down.
so I want to know  the network struct of EOS mainnet?

**Comment by csquan** [comment]
I had know 21 BP + spare nodes to support EOS network,but how to configure spare node and make it effect?

**Comment by jgiszczak** [comment]
The block producers in mainnet are leveraging the `pause/resume` API available with `eosio::producer_api_plugin`.  A standby node is configured as a producer, with a valid producer name and signature provider, but production is paused.  If the live node goes down, a script automatically calls the `resume` API on the standby node.

Producer nodes are not exposed to the public, or even to other block producers, since there is no permissions mechanism for the APIs.  An intermediate node forwards blocks into and out of the producer node.  It does not have things like `net_api_plugin` or `producer_api_plugin` enabled.  For a private network, you may not need the intermediate nodes, depending on your topology and exposure to the Internet.

**Comment by csquan** [comment]
@jgiszczak ,if resume nodes of no-bp with script automatically ,eos require replay,how to do it?

**Comment by jgiszczak** [comment]
If the node is carefully allowed to shut down gracefully in response to SIGINT or SIGTERM, it will not require replay.  Nodes that are constantly interrupted without graceful shutdown will be unable to sustain a functional network as the chain gets longer.  Replay time will grow too long.  There is a minimum threshold of node stability below which EOS.IO will not function.

**Comment by csquan** [comment]
sometime eos will crush and this need replay too.
