### ISSUE TITLE
Has anybody ever encountered this problem?

### ISSUE THREAD

**Issue by cel105302** [EOSIO/eos#6726]
When I send the transfer transaction, this problem arises. Do you have any brothers who have the same problem?
   {"s":"memo length range 6-10!"}
    thread-0  wasm_interface.cpp:917 eosio_assert
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:72 exec_one

**Comment by jgiszczak** [comment]
How are you generating the transaction?

**Comment by cel105302** [comment]
@jgiszczak The problem has been solved. Thank you.

**Comment by zhuliting** [comment]
@jgiszczak Could you please explain what caused this error ?

**Comment by jgiszczak** [comment]
@zhuliting I can't explain the root cause as the original submitter never included the code used to create the transaction.

The token contract provided in EOSIO/eosio.contracts enforces a 256 byte memo length limit.  The original submitter is apparently working with a token contract or an API with a considerably more restrictive limit.  It is unclear whether the cited limit is 6-10 bytes or characters.

**Comment by cel105302** [comment]
thx!

**Comment by pengjichen** [comment]
eos 1.6.0
