### ISSUE TITLE
build error on mac: make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2

### ISSUE THREAD

**Issue by DreamWuGit** [EOSIO/eos#6763]
Anyone help to see below build error : THX in advance 
./eosio_build.sh 
  4%] Built target emscripten-optimizer
[  4%] Built target secp256k1
[  4%] Built target builtins
[ 25%] Built target softfloat
[ 25%] Built target chainbase
[ 25%] Built target Platform
[ 27%] Built target wabt
[ 28%] Built target eosiolib
[ 28%] Built target appbase_version
[ 30%] Built target libc++
[ 30%] contract...
[ 69%] Built target libc
[ 69%] Built target copy_skeleton_contract
[ 70%] Built target identity_common
[ 70%] Built target eosio-s2wasm
[ 70%] Built target identity_interface
make[2]: *** No rule to make target `/Users/wudream/Downloads/boost1.67/boost_1_67_0/stage/lib/libboost_thread-mt.a', needed by `libraries/chainbase/test/chainbase_test'.  Stop.
make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Built target fc
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by andriantolie** [comment]
Do you have the file /Users/wudream/Downloads/boost1.67/boost_1_67_0/stage/lib/libboost_thread-mt.a?

For easier debugging, I suggest you use the default configuration provided (where boost reside in your homebrew cellar for Mac or ~/opt for Linux) instead of using the boost library in your Downloads folder as you did above.

**Comment by spoonincode** [comment]
No response in nearly 2 months, closing
