### ISSUE TITLE
signature-provider is not required when specifying producer-name

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#6768]
Starting nodeos with a config.ini that contains "producer-name=" and but no "signature-provider" results nodeos starting, but it will never sign any blocks.

Should it be fatal error if no signature provider is given?

```
producer plugin:  plugin_startup() begin
producer_plugin.cpp:772       plugin_startup       ] Launching block production for 1 producers at 2019-02-18T17:00:03.808.
producer_plugin.cpp:784       plugin_startup       ] producer plugin:  plugin_startup() end
```

**Comment by jgiszczak** [comment]
This will not be supported.

The only reasonable way to implement it that is actually useful in the real world involves creating a hard dependency on system contract structures within nodeos code.  Specifically, nodeos would need to parse and process the `producer_info` structure retrieved from chainbase in order to validate signature providers in a useful way.  Any chain running without the baseline system contract would suffer endless spurious warnings, which is to be avoided.
