### ISSUE TITLE
smoke tests should use short tmp directories to store files needed for test

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#6837]
The smoke tests store the files generated by the tests (blocks, databases, logs, and most relevantly in this case, `.sock` files) inside the directory in which they are run from, which is the build directory. As part of the test, keosd runs with `unix-socket-path` set to the `eosio-ignition-wd/keosd.sock` file within the build directory. The problem is that the length of the path for a Unix socket cannot exceed approximately 100 characters. So depending on how long is the path of the build folder, the smoke tests may fail.

The smoke tests should be updated to place their files inside a unique temporary directory in `/tmp` with a short enough name to guarantee that the `.sock` file does not exceed 90 characters.

**Comment by kj4ezj** [comment]
I ran into this issue today.
Apple NP tests worked on the `eosio` pipeline, where the path to `/build/eosio-ignition-wd/keosd.sock` on mac was 99 characters. But using `eosio-beta` for the pipeline slug resulted in a path to `/build/eosio-ignition-wd/keosd.sock` which was 104 characters, causing all NP tests on both High Sierra and Mojave to fail except the first two.

**Comment by kj4ezj** [comment]
> But using `eosio-beta` for the pipeline slug resulted in a path to `/build/eosio-ignition-wd/keosd.sock` which was 104 characters, causing all NP tests on both High Sierra and Mojave to fail except the first two.

Unfortunately the `eosio-beta` pipeline containing the history and logs of which tests were effected by this issue was deleted because it was just a temporary pipeline for testing. I recreated the `eosio-beta` pipeline [here](https://buildkite.com/EOSIO/eosio-beta) and it should still exhibit the same behavior. I also created a pipeline with an even longer pipeline slug, `eosio-beta-with-some-very-long-pipeline-slug`, [here](https://buildkite.com/EOSIO/eosio-beta-with-some-very-long-pipeline-slug).  
  
This issue can also be replicated on any machine by cloning the eos repo to a spot in your filesystem where the path to `/build/eosio-ignition-wd/keosd.sock` from root `/` is greater than 100 characters.

**Comment by taokayan** [comment]
hi @kj4ezj @arhag I think it is pretty likely that the eosio-ignition-wallet will only be created by the bios_boot.sh script which is created by eosio-launcher. If PR https://github.com/EOSIO/eos/pull/7444 is merged, eosio-launcher will always assign a tcp port number for ignition wallet by the logic of ```calculate_port(cluster_id, 0, port_type::keosd)```. And because of this, we might not need to relocate the path of keosd.sock.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
