### ISSUE TITLE
Limited stack size for contracts

### ISSUE THREAD

**Issue by peosdev** [EOSIO/eos#6860]
Stack seems to be limited to 8k for smart contracts. This makes several libraries impossible to use without modifications. 

Is there a reason for this restriction? Are there any plans to make this larger?

**Comment by spoonincode** [comment]
The 8KB stack size is a default of eosio.cdt and nothing to do with EOSIO's WebAssembly smart contract environment. I would encourage you to file an issue over at https://github.com/EOSIO/eosio.cdt/ if desired -- I too was a little surprised eosio-cpp seemed to offer no way to adjust this on a cursory look. But closing this one here as it is not applicable to this repository.

Memory in a smart contract is a limited resource and therefore EOSIO does impose some limits on the layout of memory. eosio.cdt tries to be stingy so it doesn't needlessly waste resources. eosio.cdt lays out a the memory space as:

STACK
DATA (things like strings and initialized globals)
HEAP

It places stack first so that stack overflows immediately crash the contract vs getting spooky behavior by overwriting the data section. However, EOSIO's smart contract environment does impose a limitation such that all initialized data must be within the first 64KB of WASM memory. Given this layout, it means the user is only allowed to have 64KB-STACKSIZE of DATA. As such, it is prudent to keep the stack small so that the user has plenty of space available for data.

This layout is not a requirement though. It is possible to have, say, 60KB of data followed by a stack that is 1MB large. The only requirement EOSIO imposes is that the first 64KB is the only place a contract can have initialized data -- this limits the DATA section to 64KB.
