### ISSUE TITLE
Several locations swallow std::bad_alloc

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#6979]
If a plugin throws `std::bad_alloc` from a handler, `controller_impl::emit` will report `signal handler threw exception` and keep running. Many macros throughout the codebase, including fc, also swallow this exception.

Possibly related to #6377.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
