### ISSUE TITLE
fatal error about REX

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eos#7015]
I run my eos on my linux os,the version is following:
```
root@ubuntu:/home/time/resource/eosio.contracts/build/contracts# cleos get info
{
  "server_version": "686f0deb",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 15338,
  "last_irreversible_block_num": 15337,
  "last_irreversible_block_id": "00003be9826bcf85e875c361e1a23f4aa1eebb465568a58c677e3e64686cc4c0",
  "head_block_id": "00003bea223f694eb9dbcb5c5fb689f76b65f717fdc1443c7922bebd4ebe1ca5",
  "head_block_time": "2019-03-29T09:03:46.500",
  "head_block_producer": "bp1",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576,
  "server_version_string": "v1.7.0-dirty"
}
```
**however ,i deployed eosio.system contract from this( https://github.com/EOSIO/eos/tree/master/unittests/contracts/eosio.system  ),all things was good except when i buy rex, as we all know ,when buy rex should voter for 21 producer or voter a proxy,but when i deployed this contract , i can buy rex and did not ask to vote any account!!!**

**I re-dployed the eosio.system contract from this( https://github.com/EOSIO/eosio.contracts/tree/v1.6.0-rc3 ）,all the function is good.
Therefore, your eosio.system contract must got error in (https://github.com/EOSIO/eos/tree/master/unittests/contracts/eosio.system )!!!!!**

**Comment by andriantolie** [comment]
Hi @dawnFromDark,

If you take a look at the commit date of the link that you mentioned above https://github.com/EOSIO/eos/tree/master/unittests/contracts/eosio.system , you will notice that it is 4 months old which means it is very likely not to have the latest implementation of REX. Since that contract is only used to test the governance of eosio in the automated test framework, it is sufficient for it just to have the functionality that enables governance.

If you want to test the REX contract, please get the eosio.system contract from eosio.contracts repository and compile it.
