### ISSUE TITLE
how to update producer url?

### ISSUE THREAD

**Issue by wenweihu86** [EOSIO/eos#7096]
it is the url where info about producer can be found

**Comment by taokayan** [comment]
Please refer: ./cleos system regproducer [OPTIONS] account producer_key [url] [location]

**Comment by wenweihu86** [comment]
I have called regproducer with error url, and now I want to update the url.
May I call regproducer twice?

**Comment by jgiszczak** [comment]
In the canonical system contract you may call `regproducer` as many times as you wish.  Your previous registration will be found and updated.

Note that because this is a system contract feature, not all chains may implement `regproducer` the same way.  Consult the documentation for your target chain if there is any doubt.
