### ISSUE TITLE
Unit tests for signals emitted from chain library controller

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#7213]
`controller` in `libraries/chain` communicates to external dependencies (like plugins) using a set of signals.  At this time we do not have unit tests that validate that the order, content and quantity of these signals match expectations.  

unit test(s) should  emulate:

- normal operation where blocks and transactions are input
- operation where forks are presented and resolved
- normal replay
- replay without optimizations (as needed by the state history plugin)

The following signals should be covered:

- [ ] pre_accepted_block
- [ ] accepted_block_header
- [ ] accepted_block
- [ ] irreversible_block
- [ ] accepted_transaction
- [ ] applied_transaction
- [ ] bad_alloc

As an output of this task we should also produce a written version of the expected lifecycle of these signals in these scenarios for the docs team.  

Please note: at this time we are not considering this signal API to be an externally available API so it is still subject to changes.  However, this issue is a move towards solidifying the API contract.

**Comment by andriantolie** [comment]
# Documentation about the Signals

The following document explains the producer and consumer of the signals defined in the controller and their lifecycle during normal operation, fork, and replay.

## Signal Producer and Consumer

### pre_accepted_block (carry `signed_block_ptr`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | push_block | before the block is added to the fork db |
| | replay_push_block | before the replayed block is added to the fork db (only if the replayed block is not irreversible since irreversible block is not added to fork db during replay) |

- Consumed by

| Module | Usage |
| --- | --- |
| chain_plugin | checkpoint validation |
| | forward data to pre_accepted_block_channel |


### accepted_block_header (carry `block_state_ptr`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | push_block| after the block is added to fork db |
| | commit_block | after the block is added to fork db (only if you are the one who produce the block, in other words, this is not applicable to the block received from others) |
| | replay_push_block | after the replayed block is added to fork db | (only if the replayed block is not irreversible since irreversible block is not added to fork db during replay) |

- Consumed by

| Module | Usage |
| --- | --- |
| chain_plugin | forward data to accepted_block_header_channel |


### accepted_block (carry `block_state_ptr`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | commit_block | when the block is finalized |

- Consumed by

| Module | Usage |
| --- | --- |
| net_plugin | broadcast block to other peers |

### irreversible_block (carry `block_state_ptr`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | log_irreversible | before it's appended to the block log and before the chainbase db is committed |
| | replay_push_block | when replaying an irreversible block |

- Consumed by

| Module | Usage |
| --- | --- |
| controller | setting the current lib of wasm_interface |
| chain_plugin | forward data to irreversible_block_channel |
| mongodb_plugin | forward the data to irreversible_block_state_queue |

### accepted_transaction (carry `transaction_metadata_ptr`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | push_transaction | when the transaction executes succesfully (only once, i.e. when it's unapplied and reapplied the signal won't be emitted) |
| | push_scheduled_transaction | when the scheduled transaction executes succesfully |
| | | when the scheduled transaction fails (subjective/ soft/ hard) |
| | | when the scheduled transaction expires |
| | | after applying onerror |

- Consumed by

| Module | Usage |
| --- | --- |
| chain_plugin | forward data to accepted_transaction_channel |
| mongodb_plugin | forward the data to transaction_metadata_queue |

### applied_transaction (carry `std::tuple<const transaction_trace_ptr&, const signed_transaction&>`)

- Produced by

| Module | Function | Condition |
| --- | --- | --- |
| controller | push_transaction | when the transaction executes succesfully  |
| | push_scheduled_transaction | when the scheduled transaction executes succesfully |
| | | when the scheduled transaction fails (subjective/ soft/ hard) |
| | | when the scheduled transaction expires |
| | | after applying onerror |

- Consumed by

| Module | Usage |
| --- | --- |
| chain_plugin | forward data to applied_transaction_channel |
| mongodb_plugin | forward the data to transaction_trace_queue |

### bad_alloc
This seems to be never used anywhere in the code

## Lifecycle of the signals

### A. normal operation where blocks and transactions are input
1. When a transaction is pushed to the blockchain (through RPC or broadcasted by peer)
   1. Transaction is executed either succesfully/ fail the validation -> `accepted_transaction` is emitted by the controller
   2. chain_plugin will react to the signal to forward the transaction_metadata to accepted_transaction_channel
   3. mongodb_plugin will react to the signal and add the transaction_metadata to its queue to be processed later on
2. When a scheduled transaction is pushed to the blockchain
   1. Transaction is executed either succesfully/ fail subjectively/ soft fail/ hard fail -> `accepted_transaction` is emitted by the controller
   2. chain_plugin will react to the signal to forward the transaction_metadata to accepted_transaction_channel
   3. mongodb_plugin will react to the signal and add the transaction_metadata to its queue to be processed later on
3. When a block is pushed to the blockchain (through RPC or broadcasted by peer)
   1. Before the block is added to fork db -> `pre_accepted_block` will be emitted by the controller
   2. chain_plugin will react to the signal to do validation of the block forward the block_state to accepted_block_header_channel and validate it with the checkpoint
   3. After the block is added to fork db -> `accepted_block_header` will be emitted by the controller
   4. chain_plugin will react to the signal to forward the block_state to accepted_block_header_channel
   5. Then the block will be applied, at this time all the transactions and scheduled_transactions inside the block will be pushed. All signals related to push_transaction and push_scheduled_transaction (see point A.1 and A.2) will be emitted.
   6. When committing the block -> `accepted_block` will be emitted by the controller
   7. net_plugin will react to the signal and broadcast the block to the peers
   8. If a new block becomes irreversible, signals related to irreversible block will be emitted (see point A.5)
4. When a block is produced
   1. For the block that is produced by you, the block will be added to the fork_db when it is committed -> `accepted_block_header` will be emitted by the controller
   2. chain_plugin will react to the signal to forward the block_state to accepted_block_header_channel and validate it with the checkpoint
   3. Immediately after that (during commiting the block) -> `accepted_block` will be emitted by the controller
   4. net_plugin will react to the signal and broadcast the block to the peers
   5. If a new block becomes irreversible, signals related to irreversible block will be emitted (see point A.5)
5. When a block becomes irreversible
   1. Once a block is deemed irreversible -> `irreversible_block` will be emitted by the controller before the block is appended to the block log and the chainbase db is committed
   2. chain_plugin will react to the signal to forward the block_state to irreversible_block_channel and also set the lib of wasm_interface
   3. mongodb_plugin will react to the signal and add the transaction_metadata to its queue to be processed later on

### B. operation where forks are presented and resolved
1. When forks are presented, the blockchain will pop all existing blocks up to the forking point and then apply all new blocks in the fork.
2. When applying the new block, all the transactions and scheduled_transactions inside the block will be pushed. All signals related to push_transaction and push_scheduled_transaction (see point A.1 and A.2) will be emitted.
3. And then when committing the new block -> `accepted_block` will be emitted by the controller
4. net_plugin will react to the signal and broadcast the block to the peers
5. If If a new block becomes irreversible, signals related to irreversible block will be emitted (see point A.5)

### C. normal replay (with or without replay optimisation)
1. When replaying irreversible block -> `irreversible_block` will be emitted by the controller
2. Refer to A.5 to see how `irreversible_block` signal is responded
3. When replaying reversible block, before the block is added to fork_db -> `pre_accepted_block` will be emitted by the controller
4. When replaying reversible block, after the block is added to fork db -> `accepted_block_header` will be emitted by the controller
5. When replaying reversible block, when the block is committed -> `accepted_block` will be emitted by the controller
6. Refer to A.3 to see how `pre_accepted_block`, `accepted_block_header` and `accepted_block` signal are responded

**Comment by iamveritas** [comment]
PR for to address this here https://github.com/EOSIO/welcome/pull/155

**Comment by lparisc** [comment]
[docs/04_protocol/03_network_peer_protocol.md#221-signals-producer-and-consumer](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/03_network_peer_protocol.md#221-signals-producer-and-consumer)
[docs/04_protocol/03_network_peer_protocol.md#222-signals-life-cycle](https://github.com/EOSIO/welcome/blob/develop/docs/04_protocol/03_network_peer_protocol.md#222-signals-life-cycle)
