### ISSUE TITLE
recent Fortiguard reports

### ISSUE THREAD

**Issue by attritionorg** [EOSIO/eos#7267]
Recently, Fortiguard disclosed four vulnerabilities in EOS.IO:
https://fortiguard.com/zeroday/FG-VD-18-100
https://fortiguard.com/zeroday/FG-VD-18-101
https://fortiguard.com/zeroday/FG-VD-18-125
https://fortiguard.com/zeroday/FG-VD-18-126

They link to the HackerOne reports, but the H1 reports and their advisories do not link to corresponding tickets / PRs / commits. Could a project maintainer show those links? I believe that at least two of them may correspond with issues fixed in v1.6.2 and v1.7.0-rc1 but would like to confirm that. Thank you for any help you can provide!

**Comment by spoonincode** [comment]
FG-VD-18-100 related to binaryen wasm runtime. That runtime was removed in 1.4. We may have fixed the underlying issue before then but doesn't matter now.
FG-VD-18-101 was fixed in 1.2 see the H1 remarks for details.
FG-VD-18-125 & FG-VD-18-126 were both related with the wasm compiler that was superseded by eosio.cdt many releases ago and was finally removed from the main repo in 1.7.

**Comment by attritionorg** [comment]
@spoonincode Great, thank you for the details!
