### ISSUE TITLE
1.7 build script 18.04 - when using system provided cmake mongo isn't found

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7301]
On 18.04 I installed the system provided cmake (3.10) before running the eosio build script. This results in the build script not building its own cmake. But then when eosio builds it cannot find mongo's cmake modules.

This is due to the system provided cmake not searching $HOME as a CMAKE_SYSTEM_PREFIX_PATH. When we build cmake $HOME is added to CMAKE_SYSTEM_PREFIX_PATH and the mongo cmake modukes that are placed in $HOME/lib/cmake are found in that case

**Comment by NorseGaud** [comment]
Maybe something like this? ```
if [ $ARCH == "Linux" ]; then
   # Check if cmake is already installed or not and use source install location
   if [ -z $CMAKE ]; then 
      export CMAKE=$PREFIX/bin/cmake
   else
      export CMAKE_SYSTEM_PREFIX_PATH="${HOME};${CMAKE_SYSTEM_PREFIX_PATH}"
   fi
```

Or maybe ` export CMAKE_SYSTEM_PREFIX_PATH="${HOME}/lib/cmake;${CMAKE_SYSTEM_PREFIX_PATH}"`

**Comment by spoonincode** [comment]
you shouldn't change CMAKE_SYSTEM_PREFIX_PATH. we can probably just need to add $PREFIX to the CMAKE_PREFIX_PATH

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
