### ISSUE TITLE
Building EOSIO favors /usr/local/include/fc over libraries/fc/include

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#7352]
The include path search order should favor local directories over global includes.

Build fails on 1.7.3 if an old version of fc is installed at /usr/local/include/fc

Same happens for appbase and others.

**Comment by b1aafulei** [comment]
Hi Dan @bytemaster.

I was trying to reproduce your problem, but could not do so.

I would like to report my procedure and preliminary findings below.

------

First, I cloned `EOSIO/fc` repository, and established a soft link from `/usr/local/include/fc` to the header files in the repository.

Then I tried to run the build script `eos/scripts/eosio_build.sh` on the source code for both

1. the latest `develop` branch (commit `cbb329d586acfa187b29dea010ec2084fcd306e3`) and 
2. the latest `release/1.7.x` branch (commit `fb408bf24fe94b79d8feafcbe72b7bb506bb1b39`).

Before doing so, I had run `eosio_uninstall.sh` in order to ensure a clean installation.

However, it seems my build script searches and only searches the local `eos/libraries/fc` folder.

1. If I alter `eos/libraries/fc/CMakeLists.txt` to print a message, the message will show up.
2. If I rename a header file in `eos/librarires/fc/include/fc/`, the building process will fail. It seems the build script wasn't aware of the existence `fc` in `/usr/local/include/fc` at all.

My OS is mac OS Mojave.

------

If you or anyone have any comment, please leave it here and I would love to do more investigation.

Thank you.
