### ISSUE TITLE
unpacking variable-length integer should throw if number is out of bounds

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7378]
When unpacking `fc::unsigned_int` and `fc::signed_int`, the implementation should verify that the serialized variable-length integer is within the appropriate bounds (within bounds of `uint32_t` for `fc::unsigned_int` and `int32_t` for `fc::signed_int`). If not, it should throw an exception.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
