### ISSUE TITLE
Error Details: env.calloc unresolveable

### ISSUE THREAD

**Issue by ytz1203** [EOSIO/eos#7431]
当我部署合约的时候，出现这样的错误，只是合约里并没有找到使用calloc的地方

**Comment by spoonincode** [comment]
你能分享你的合约源代码吗？没有源代码, 很难找出calloc被间接调用的原因。

**Comment by ChristianDunst** [comment]
Can we please keep the communicating language in english, since other community members might run into the same problem and might not be able to understand the solution.

Short summary:
Community member encounters the above error when deploying a smart contract and the reply was a request to share the source code, since it's impossible to pinpoint the problem without.

**Comment by spoonincode** [comment]
No response, closing
