### ISSUE TITLE
CORS headers not set for all error responses

### ISSUE THREAD

**Issue by jnordberg** [EOSIO/eos#7446]
For some API error responses e.g. `413 Payload Too Large` CORS headers are not set making it impossible for browser clients to properly detect and handle the error.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!

**Comment by jnordberg** [comment]
I'm unable to re-open but this is still an issue

**Comment by sanaraufx** [comment]
Please try the latest version (2.1) and let us know if you're experiencing this issue
