### ISSUE TITLE
extended_symbol is different than in eosio.contract (can't use it for unit test)

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#7495]
https://github.com/EOSIO/eosio.cdt/blob/796ff8bee9a0fc864f665a0a4d018e0ff18ac383/libraries/eosiolib/core/eosio/symbol.hpp#L449

https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/symbol.hpp#L193

**Comment by tbfleming** [comment]
For the tester, I recommend creating and using your own symbol struct definition.

**Comment by kesar** [comment]
> For the tester, I recommend creating and using your own symbol struct definition.

Yup, that's what i ended up doing :)

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
