### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [EOSIO/eos#7505]
**Objective**: Implement and Support i2p in EOS
**Description**: Explore the possibility of using the EOS network over i2p.
**Why?**: Many reasons, mainly for privacy and security but also to support decentralized communications. 
**Related Projects**:
Kovri: https://kovri.io/

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75652750-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75652750)](https://www.bountysource.com/issues/75652750-feature-support-i2p)

**Comment by jgiszczak** [comment]
EOS.IO is compatible with I2PTunnel.  In order to access a particular network, an operator of a public node on the network would need to provide a destination key and hostname for the hosts.txt file used by the I2P software.  Each network needs to take such an action individually.  As such, this issue should be filed with the operators of the networks of interest.  No change to the software is required.
