### ISSUE TITLE
cleos send transaction command

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#7536]
it looks like the new RPC API send_tranasction has not been added to cleos.

this is send_tranasction function in cleos main.cpp but it is not added to the command list yet or maybe it is not meant to implement this RPC API.

https://github.com/EOSIO/eos/blob/5082391c60b0fa5e68157c385cd402bf25aea934/programs/cleos/main.cpp#L513

Could the new send transaction API be added to cleos command list and pointed to the correct endpoint?

**Comment by arhag** [comment]
The function you linked to is an implementation-specific function for cleos that has been there for a while. However, coincidentally, EOSIO v1.8.x does introduce a new RPC called `send_transaction` to the chain API.

You are correct that cleos does not currently support using the `send_transaction` RPC. One option is to add an option to the `push action` and `push transaction` cleos commands to force the use of either the `send_transaction` RPC or the `push_transaction` RPC (they basically do the same thing, except `push_transaction` rearranges the returned trace to avoid breaking compatibility with existing clients that don't support the new transaction trace structure). 

I would prefer if the default became using `send_transaction` because that is the more efficient RPC of the two (it doesn't have to go through the additional rearrangement step before returning the response). However, that won't work if cleos is talking to an older version of nodeos (before v1.8.x) that doesn't support the `send_transaction` RPC. Cleos could use the `/v1/node/get_supported_apis` endpoint to discover whether the node it is talking to supports `send_transaction`, and if it doesn't support it, it would fall back to the `push_transaction`.

**Comment by aaron-fu-block-one** [comment]
I would like to take this issue, and enhance `cleos push transaction` as proposed by @arhag:

- When `cleos push transaction` is called, use `get_supported_apis` to detect whether the node supports the newly introduced `send_transaction` RPC or not:
    - If the node supports, the more efficient `send_transaction` will be called
    - If it does not, the traditional `push_transaction` will be called
- If possible, will add an option to `cleos push transaction`, which will force using the old RPC `push_transaction` across all the cases.

**Comment by matthewdarwin** [comment]
FWIW, as a block producer, I don't expose the `get_supported_apis` endpoint as there is no way to control what APIs are listed.  I have more APIs available in nodeos that I don't make publicly available.  So using this logic while I would support send_transaction, you wouldn't know. (eg I might enable the 'net' plugin, so I can use the functions, but not make that available publicly).

I also find it interesting that `get_supported_apis` is not listed in the available api list it returns.

**Comment by arhag** [comment]
Another option is to just change the default behavior of `push action` and `push transaction` to use the new `send_transaction` RPC. (This new behavior in cleos would be introduced at the earliest in v2.0.x, so there is a good chance that everyone has been forced to update to v1.8.x by then, which supports send_transaction, because of the consensus protocol upgrade.) If it fails because the `send_transaction` RPC is not supported (for example it's an old version) it could print a message to the user suggesting to try using the `--use-old-rpc` option which would force cleos to use of the `push_transaction` RPC.

This approach also typically saves a round trip by being optimistic that most nodes will support `send_transaction` by the time this change is available in cleos.

**Comment by matthewdarwin** [comment]
That sounds like a better plan to me.

**Comment by aaron-fu-block-one** [comment]
> Another option is to just change the default behavior of `push action` and `push transaction` to use the new `send_transaction` RPC. (This new behavior in cleos would be introduced at the earliest in v2.0.x, so there is a good chance that all nodes have been forced to update to v1.8.x by then, which supports `send_transaction`, because of the consensus protocol upgrade.) If it fails because the `send_transaction` RPC is not supported (for example it's an old version) it could print a message to the user suggesting to try using the `--use-old-rpc` option which would force cleos to use of the `push_transaction` RPC.
> 
> This approach also typically saves a round trip by being optimistic that most nodes will support `send_transaction` by the time this change is available in cleos.
> 
> It also ensures that the user knows what type of trace will be returned. The default behavior will return traces in the new format, and it will only return the traces that were reorganized to match the old structure if the user explicitly provides the `--use-old-rpc` option.

Sounds a better plan to me, too. Will do this one.

**Comment by aaron-fu-block-one** [comment]
Pull request merged. I am closing this issue.
