### ISSUE TITLE
Misleading error message when contract lacks `eosio.code` permission and tries to send an inline action.

### ISSUE THREAD

**Issue by thekevinbrown** [EOSIO/eos#7548]
The error message you receive is:

```
Error: transaction declares authority '{"actor":"coinagegizmo","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"ginfhubtoken","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
```

It turns out that in fact I have supplied all the signatures needed, but that the `eosio.code` permission hasn't been set on `ginfhubtoken`. Which is somewhat mentioned in the error message, but since it says, "does not have signatures for it" I thought I was missing a signature, which is not actually the problem.

A better error message for this particular case in my opinion would be, `Contract attempted to send an inline action of `transfer` to `ginfhubtoken` but `ginfhubtoken` does not have `eosio.code` permission, so sending the inline action is not allowed.`

**Comment by taokayan** [comment]
The actually meaning is:

- You have the ```ginfhubtoken@eosio.code``` permission, which is an implicit permission.
- However, your ```ginfhubtoken@eosio.code``` permission can not satisfy the permission of ```coinagegizmo@active```

So what you need is to setup a link from ginfhubtoken@eosio.code to coinagegizmo@active so that coinagegizmo@active can be satisfied.

You can use ```./cleos set account permission``` to setup this link

**Comment by ChrisCates** [comment]
Just so other people are a bit more clear about how to set the permissions it should structured this way:

```bash
cleos set account permission [account] active
'{
  "threshold": 1,
  "keys": [
    {
      "key": "[public key]",
      "weight": 1
    }
  ],
  "accounts": [
       { 
       "permission": { 
         "actor": "[account]", "permission": "eosio.code"
       },
      "weight": 1 }
   ]
}'
owner -p [account]
```

You should condense the JSON into string escaped format

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
