### ISSUE TITLE
1.8rc2: unregprod does not have effect in testnet

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#7552]
I launched a testnet with 1.8rc2.  In the beginning, 3 producers (`prodx1 prodx2 prodx3`) were registered and voted (using `bios-boot-tutorial.py`), and the network was fully operational.

Then, I stared 3 more BP nodes, and registered 3 additional producers, and voted for them:

```
cleos system voteproducer prods useraaaaaaaa prodx1 prodx2 prodx3 prodaaaaaaa1 prodaaaaaaa2 prodaaaaaaa3
```
About a minute later, the schedule updated and all 6 producers started signing the blocks.

Then, I unregistered 3 producers:

```
cleos system unregprod prodaaaaaaa1 
cleos system unregprod prodaaaaaaa2
cleos system unregprod prodaaaaaaa3 
```

The schedule hasn't updated, and all 6 continued producing the blocks.

I re-voted, but the schedule still hasn't changed:
```
cleos system voteproducer prods useraaaaaaaa prodx1 prodx2 prodx3
```

Is it expected behavior? how can I remove BP from the schedule?

**Comment by cc32d9** [comment]
Voting for those producers which did unregprod is rejected because they are not registered. But the schedule continues running with 6.

**Comment by smlu** [comment]
This is due to how the system contract is designed to propose new schedule. The number of block producers in the newly proposed schedule can never be less then in the last purposed schedule. See [voting.cpp:100](https://github.com/EOSIO/eosio.contracts/blob/50b235c6a327e05e21699b2e837b81db26bd6d7b/contracts/eosio.system/src/voting.cpp#L100).

In your case, after you unregistered 3 out of 6 block producers and although those 3 were deactivated the contract couldn't propose new schedule since the size of new schedule was less then previous.

**Comment by cc32d9** [comment]
Thank you @smlu , it's clear now.
