### ISSUE TITLE
Create test account using EOSIO

### ISSUE THREAD

**Issue by mschaudhari** [EOSIO/eos#7614]
I am new with EOSIO.

I have created account using cleos command.
```

cleos create account eosio bob YOUR_PUBLIC_KEY 
cleos create account eosio alice YOUR_PUBLIC_KEY
```
It's successfully created. But, I wanted to create account using RPC API. So, I tried to find out "create account" API in API document, but there is not available. So, Is there any way to create account using http request?

Sorry for my bad english. Thanks in advance.

**Comment by jgiszczak** [comment]
Creating an account is simply a transaction with a `newaccount` action in it.  To see the complete sequence of composing and signing that transaction, use:
```bash
cleos --print-request create account eosio bob EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
```
You will see the series of 5 API calls required to get information, sign, and submit the transaction.  You may always use `--print-request` and `--print-response` to see what cleos is doing.

Rather than writing all the code to construct such a transaction yourself, you might consider the [eosjs library](https://github.com/EOSIO/eosjs).

If you still have questions and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
