### ISSUE TITLE
DAWN-190 ⁃ Node fails to sync when restarting

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#763]
When I started testing, 4 of the nodes were not functioning as intended.

3 were out of sync
1 was totally down

I have no information in this ticket regarding the reason of why the nodes did not perform correctly.

Next I restarted one node (host 2) however it would not sync up and continually threw the following error:

"got a block while syncing but no sync_receiving set to #XXXX", whereas XXXX seems to be the number of the head block.

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10049&#x2F;Screen+Shot+2017-11-22+at+3.22.25+PM.png">Screen Shot 2017-11-22 at 3.22.25 PM.png</a>

**Comment by pmesnier** [comment]
Sync_receiving is a structure attached to a p2p connection. It is used during initial synchronization. there are times when a node may enter a sync mode as the result of a new connection with a peer that has a higher last-irreversible-block number. Let's say node A has a connection to node B and both agree that LIB is number 0 because this is shortly after startup. now node A should have connected to node C, but node C wasn't available yet. Node C has a connection to other nodes and so when node A gets around to connecting again, it's LIB is somewhat higher than 0, thus kicking A into sync mode. But since A already had a connection to B, when it gets a block from B, it will report the message shown above.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Adding to sprint 6, it is assigned.  Understanding that Phil might not get to this one.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Christian, can you describe the steps you took to get to this stage?

I think this is a side effect of various issues we've recently resolved but I'd like to be sure.

The ATC for this issue would be to run the same start up sequence of steps and observe the nodes are synced.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

Withdrawn; superseded by newer tickets.
