### ISSUE TITLE
Determine if producer watermarks need to incorporate time

### ISSUE THREAD

**Issue by b1bart** [EOSIO/eos#7680]
It seems like we need `_producer_watermarks` to map to both the watermark block number and the watermark block time. We would update the watermark time both here and in `produce_block` (unless it would cause it to decrease).

_Originally posted by @arhag in https://github.com/EOSIO/eos/diffs_

**Comment by b1bart** [comment]
reference to diff

https://github.com/EOSIO/eos/pull/7404/files/510118ac3bb48c8eecffb44370a9c7fafc0b32b5#r307081955

**Comment by b1bart** [comment]
should also determine if `_start_time` is still needed provided the updated watermarks

**Comment by arhag** [comment]
Actually, it seems like it is fine to not incorporate timestamp into the watermarks. 

Nodeos should not be attempting to produce blocks at a timestamp earlier than the time at which it started. Similarly, timestamp watermarks don't need to be tracked because nodeos shouldn't attempt to produce a block at a timestamp no later than the timestamp of a block it produced locally. There could be some skew in the wall-clock time between two different nodes signing for the same producer, but there is already a (likely greater) risk that a block signed by one BP node doesn't propagate through the network to another BP node in time to prevent the second node from signing the block with the conflicting timestamps. This risk needs to be managed through the BP failover scripts allowing sufficient time before attempt to start signing on a backup (or better yet using a consensus protocol to manage to hand-offs). And if they did wait a sufficient time for the hand-off, then small clock skew shouldn't be a cause for concern of double-signing blocks.

However, investigation into this matter did reveal two problems with the current watermark tracking system:

1. It can potentially allow for the watermark block number to decrease.
2. It waits until after the block is applied before considering the block in the watermark tracking rather than considering it as soon as it passes header validation (which means it was correctly signed by the block producer).

These two limitations are addressed by PR #7702.
