### ISSUE TITLE
Make conversions for `shared_key_weight` and `shared_public_key` explicit

### ISSUE THREAD

**Issue by b1bart** [EOSIO/eos#7683]
_Originally posted by @heifner in https://github.com/EOSIO/eos/pull/7404_

link to diff: https://github.com/EOSIO/eos/pull/7404#discussion_r306417112

this is part of a gradual trend away from implicit `operator()` style type conversions for more complex types.

**Comment by b1bart** [comment]
I would like to invite @spoonincode  to weigh in as he originally made the changes to support bip::allocator aware structures here.

**Comment by spoonincode** [comment]
>As this was the pattern established in #7421 I'm going to promote this to an issue to handle outside of this PR

nah that pattern was established years before #7421 -- there was already a `shared_authority` with the implicit conversion so I just went along with it. I'm indifferent on this matter; would have no problem removing them

**Comment by b1bart** [comment]
fair point, I only meant that we had to create `shared_public_key` and `shared_key_weight` for that PR.  The implicit pattern of conversion has been there forever

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
