### ISSUE TITLE
Sugestion: add head_block_num and head_block_time in get_currency_balance response

### ISSUE THREAD

**Issue by vadim-di** [EOSIO/eos#7695]
Since part of nodes may send old data, its neccessary to control the fresh state of response.

**Comment by taokayan** [comment]
can you do a get_info first before getting the currency balance?

**Comment by vadim-di** [comment]
> can you do a get_info first before getting the currency balance?

Almost all nodes are dynamically proxied each other, so responses mostly will be from different nodes

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
