### ISSUE TITLE
Deny account permission

### ISSUE THREAD

**Issue by dariusdev** [EOSIO/eos#7738]
Currently, you can only create custom permission and link it to some contract action.

The case is when you - as an account owner - want to allow everything to "active" permission user except EOS token transfer.

Currently, it is impossible to deny something.

Possible solution. Allow creating custom permission with deny flag.

**Comment by taokayan** [comment]
I think you can use ```linkauth``` on the system contract to set a different permission (e.g. active2)  requirement to eosio.token::transfer, so that EOS token transfer action needs to satisfy active2 instead of active.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
