### ISSUE TITLE
once doing a pinned build, script always wants to do a pinned build

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7773]
If I run the eosio build script like
`$ scripts/eosio_build.sh -P -y`
and then later come along and do
`$ scripts/eosio_build.sh -y`

The expectation was a non-pinned build would be performed. However, that is not the case. The check at
https://github.com/EOSIO/eos/blob/8d84a95493d37f5d3ba56bc555083e079e65d4fb/scripts/helpers/eosio.sh#L160
forces a pinned build if it finds the pinned compiler.

In some ways the script knows this may be a problem -- without `-y` the script suggests deleting preexisting files. And indeed there will be problems because we can't link a pinned build of LLVM to a non-pinned nodeos.

Still, I don't believe this should silently occur because it means the builds aren't what are expected -- like in the case of the unpinned pipeline that is just sitting there doing pinned builds still

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
