### ISSUE TITLE
how to estimate ram for transfer and new account ?

### ISSUE THREAD

**Issue by benjamintshi** [EOSIO/eos#7776]

**Comment by benjamintshi** [comment]
can anyone help ?

**Comment by taokayan** [comment]
token transfer: it will not consume RAM from sender if the recipient already has a non-zero balance of the same token, otherwise the sender need to pay RAM for creating the balance row for the recipient which is around 200-300 bytes.

new account: you need to pass --buy-ram-bytes in the system newaccount action. a new account takes around 2-3 KB RAM.

**Comment by benjamintshi** [comment]
@taokayan，thanks 。
