### ISSUE TITLE
eosio/eos in the docker hub?

### ISSUE THREAD

**Issue by miraclegray** [EOSIO/eos#7796]
Hi, guys. I'm new to eos and I want to study about eos smart contract developing.
I want to establish eos environment on ubuntu with the help of developer guide - https://developers.eos.io/eosio-nodeos/docs/docker-quickstart.
After I installed docker, guide says to pull docker image with the following command.
$ sudo docker pull eosio/eos-dev:v1.5.2

But it returns error reads following.
"Error response from daemon: pull access denied for eosio/eos-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

plz help me with the installation of eos.

**Comment by NorseGaud** [comment]
Hey @miraclegray!

<img width="884" alt="Screen Shot 2019-09-23 at 9 52 01 AM" src="https://user-images.githubusercontent.com/5896030/65431678-ddce9d00-dde7-11e9-84fd-f77522bb592a.png">

However, I can see the confusion with this as `eosio/eos` != `eosio/eos-dev`. I've updated the message to clarify this. We highly suggest using the packages instead of docker.

**Comment by miraclegray** [comment]
thanks for reply, @NorseGaud
