### ISSUE TITLE
Optional element not allowed in array

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eos#7846]
https://github.com/EOSIO/eos/blob/be804bf63c5092a123c3e1a468559a8164bcd3be/libraries/chain/abi_serializer.cpp#L340-L343

Could you let me know why this restriction is necessary? I'm experimenting with JSON-like variant data type, but line 343 disallows next code.

``` c++
struct array; // forward declaration

using element = std::optional<std::variant<int64_t,double,bool,std::string,object,array>>;
struct array {
   std::vector<element> data;
};
```

**Comment by taokayan** [comment]
I guess you can try to make a temporary struct, for example:
```struct tmp {
  optional<int> member;
};```
then use ```std::vector<tmp>```

**Comment by conr2d** [comment]
@taokayan Thank you for reply, but I wanted to know the reason that line is added. The commit 7eb1b84d95d74a9429fc2d9a0684625894553a52 adds that, but I couldn't find clues what security vulnerability is fixed by this check.

**Comment by shinex** [comment]
Jeeyong Um <notifications@github.com> 於 2019年9月14日 週六 下午7:49 寫道：

**Comment by shinex** [comment]
Vvvv

Jeeyong Um <notifications@github.com> 於 2019年9月14日 週六 下午7:49 寫道：

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release. If you believe this issue is still relevant please feel free to reopen it or create a new one. Thank you for your continued support of EOSIO!
