### ISSUE TITLE
STAT-212 ⁃ EOSD Version comparison needs to be configurable

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#803]
Daniel Larimer, [Nov 28, 2017 at 8:43:32 AM]:
We should have "compatibility version numbers" that don't break just because of a build change.
I'm just saying that the current setup is so strict that we cannot test "unstable code" against the "stable nodes" and "stable nodes" should not crash based upon input from unstable nodes.

Daniel Larimer, [Nov 28, 2017 at 8:40:24 AM (11/28/17, 8:40:28 AM)]:
The strict version requirement will make test net unusable by masses. I am thinking that we should make that an option that we can enable for our testing purposes but otherwise is just a warning.

When I recompile to add a new plugin it shouldn't break compatibility with a live test network
option should default to false, only true in our internal test networks and it should only be enforced on the client side, server shouldn't enforce it. it is up to the client to determine if they care about exact matches.

The server should be resilient against all byzantine failures.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

When there's a log entry caused by this check -- Can we be sure that the log entry shows the version of both the remote responder and the local initiator?

**Comment by brianjohnson5972** [comment]
Just verified that it prints both expected and received.

On Nov 28, 2017 3:17 PM, "blockone-syncclient" <notifications@github.com>
wrote:

➤ Thomas B. Cox commented:

When there's a log entry caused by this check -- Can we be sure that the
log entry shows the version of both the remote responder and the local
initiator?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EOSIO/eos/issues/803#issuecomment-347666425>, or mute
the thread
