### ISSUE TITLE
in v1.8 How does the contract pay the cpu/net fee for the user?

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#8037]
after "ONLY_BILL_FIRST_AUTHORIZER" activation, in contract How to achieve pay cpu/net fee for user?have any example? thank you!

**Comment by jgiszczak** [comment]
A more detailed discussion of the feature and its implementation may be found [here](https://github.com/EOSIO/eos/issues/6332).  To cover the CPU and NET transaction costs after `ONLY_BILL_FIRST_AUTHORIZER` activation, simply submit the transaction with the contract's account as the first authorizing signature, rather than the user.  The user account will then not require any CPU or NET staking for the transaction to succeed.  Note this only covers the required stake for the transaction, which is not a fee.  `ONLY_BILL_FIRST_AUTHORIZER` has no affect on RAM costs, or which accounts pays them.

**Comment by wangyilin1987** [comment]
@jgiszczak user does not have private key for the contract account.What should i do in the contract to get this authorization approved?

**Comment by jgiszczak** [comment]
You should create a new permission under the contract's account with its own key, then link your chosen contract action to that key.  Then provide a portal of some sort, such as a web page or a web API, that can use the corresponding private key to sign user-initiated contract actions.  Your portal should validate and rate limit requests to it, as appropriate.  With care, you can set up the portal to keep that private key private, and because you will create a specific permission for the contract action, you won't be risking the account's owner or active private keys.

See the [documentation](https://developers.eos.io/eosio-home/docs/understanding-set-auth) for details.

**Comment by wangyilin1987** [comment]
this is like the service provider need provide some services to call the  contract's action for the user? If I understand it is right,this can be achieved without ONLY_BILL_FIRST_AUTHORIZER activation.

**Comment by wangyilin1987** [comment]
the example is create new permission and link to contract action。but how does the contract pay the cpu/net fee for the user still no example?this will lead to some details being misunderstood.

**Comment by jgiszczak** [comment]
With `ONLY_BILL_FIRST_AUTHORIZER` enabled, the contract inherently uses its own stake for CPU and NET, assuming it is the first authorizer.  No additional effort or distinctive characteristic of the transaction is required.  Until `ONLY_BILL_FIRST_AUTHORIZER` is enabled, any transaction requiring both the contract's and the user's signature will require the user to have stake to succeed.

You are correct that providing a service to call the contract is possible without activation of `ONLY_BILL_FIRST_AUTHORIZER` enabled.  What's not possible is providing contract actions signed by the user that the user can perform without their own stake.

**Comment by wangyilin1987** [comment]
if transaction requiring both the contract's and the user's signature: how use the user@active and contract@free permissions to simultaneously authorize the action.
