### ISSUE TITLE
Cpu resources cannot be restored

### ISSUE THREAD

**Issue by quarksgluons** [EOSIO/eos#8190]
My account has not been sent transaction for 4 days. Then it‘s cpu used resources should be restored normally. But the cpu still has not recovered. The cpu available is still 0.
used rate: 120.8%
used:2.05 ms
total: 1.7 ms
What is the reason?

**Comment by spartucus** [comment]
https://github.com/EOSIO/eos/issues/4474#issuecomment-433843346

**Comment by quarksgluons** [comment]
The problem is that the cpu is not recovering and the transaction cannot be successfully sent. Since the transaction cannot be sent, the usage information of the cpu cannot be restored. This is an infinite loop problem.

Why is it designed to send a transaction to recover instead of automatically recovering?? After all, there is a situation in which such a transaction cannot be sent out.

In this case, the account cannot be used. I think this is a big problem.

**Comment by heifner** [comment]
If the network you are interested in is supported by blocks.io check your account there. I believe they report available cpu with refresh time incorporated. There are probably other explorers available as well that show the same info.

As explained in the above link, the on chain account resource usage stats are only updated at the end of a successful transaction. Otherwise we would have to continuously recalculate them for all accounts or modify get_account to use the same calculation used on chain. get_account reports the raw chain values and lets block explorers report that as they like.

**Comment by jgiszczak** [comment]
To be clear, the system calculates pending resource limits [here](https://github.com/EOSIO/eos/blob/7d210b387ce5ec9089ab31e9cc0e237bceb25622/libraries/chain/resource_limits.cpp#L265).  The pending limits are calculated with the elapsed time taken into account.  The transaction is executed according to those pending limits, not the limits `cleos` retrieves at the time.  If the transaction passes the pending limits and is successfully incorporated into a block, the pending limits are used to update the limits visible to `cleos` while the block is being [finalized](https://github.com/EOSIO/eos/blob/7d210b387ce5ec9089ab31e9cc0e237bceb25622/libraries/chain/controller.cpp#L1531).  At no point does the account become permanently unusable.

If your newly submitted transaction is failing, it is legitimately failing against the restored limits of the account, not against the stale values visible to cleos.  Submit a smaller transaction, such as a transfer, and you will see it accepted and your limits updated.

**Comment by jsprice87** [comment]
Why do the conversations about this problem keep getting closed without resolution?

I have not made any transactions on either of my EOS accounts in several months and I still have 'Used 1.53 ms / 0.28 ms' CPU bandwidth.  My accounts are basically frozen because of this problem.  Please help get this resolved.
