### ISSUE TITLE
I push a transaction to my local node succeed. But i cant find it after a few minutes.

### ISSUE THREAD

**Issue by wangsen0518** [EOSIO/eos#8214]
I push a transaction to my local node succeed.And i get the transaction by the command
 curl -X POST http://localhost:8888/v1/history/get_transaction --data '{"id":"-----11f215280d57766b1084a729be01ed620e67034f61c037c4f774f3a------"}'

{
	"id": "-----11f215280d57766b1084a729be01ed620e67034f61c037c4f774f3a------",
	"trx": {
		"receipt": {
			"status": "executed",
			"cpu_usage_us": 207,
			"net_usage_words": 16,
			}
                 ......
		"console": "",
		"trx_id": "-----11f215280d57766b1084a729be01ed620e67034f61c037c4f774f3a------",
		"block_num": 89300397,
		"block_time": "2019-11-11T08:22:38.500",
		"producer_block_id": null,
		"account_ram_deltas": [],
		"except": null,
		"error_code": null
	}]
}
I got the block_num and trx_id. I think the transaction is accepted by the block chain.But after a few minutes, i cant find the transaction in my local node. why?

{"code":500,"message":"Internal Service Error","error":{"code":3040011,"name":"tx_not_found","what":"The transaction can not be found","details":[{"message":"Transaction -----11f215280d57766b1084a729be01ed620e67034f61c037c4f774f3a------ not found in history and no block hint was given","file":"history_plugin.cpp","line_number":471,"method":"get_transaction"}]}}

**Comment by jgiszczak** [comment]
Provide the `89300397` block hint and your transaction will likely be found.

Note that history plugin is officially deprecated and will eventually be removed from `nodeos`.  Consider migrating to state history plugin and one of its backing databases sooner rather than later.  It will be the only supported history solution.  As an added bonus, transaction ID lookups tends to be more reliable from it.
