### ISSUE TITLE
Need buildkite pipeline tests to install node

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#8230]
Integration tests need node installed, with the following modules:
eosjs
commander
node-fetch
zlib
ws

PR #8198 is blocked till this is resolved.

**Comment by zreyn** [comment]
I've started a separate conversation for us in Slack to discuss specifics, but the changes you are requesting actually need to be made in the eos branch from the PR.   Basically, the build and test steps in the pipeline run on the images defined in the eos/.cicd directory.  So, additional dependencies need to be specified there.   

Since those changes are actually part of the PR, I don't think we need to keep a separate issue open.  We can discuss on the PR or in Slack.
