### ISSUE TITLE
EOS Get Action Paramater return null

### ISSUE THREAD

**Issue by egetekiner** [EOSIO/eos#8262]
While synchronizing EOS wallet, I tried to list transactions of Kraken wallet with the following command,

`eos/build/programs/cleos/./cleos get actions krakenkraken -1 -20`

It returned empty output like the figure below,

![image](https://user-images.githubusercontent.com/20884156/69903676-aaba0400-136a-11ea-9192-588e2a97a3f5.png)

My config.ini file looks like this,

![image](https://user-images.githubusercontent.com/20884156/69903685-e2c14700-136a-11ea-90a8-58766dfb69d3.png)

![image](https://user-images.githubusercontent.com/20884156/69903694-fcfb2500-136a-11ea-9dc2-a26d032ff32b.png)

Should I make another change in config file? or should I do something different?

Note: This problem talked but unsolved for other versions.

**Comment by jgiszczak** [comment]
How much of the chain have you synced so far?  The `krakenkraken` account wasn't created until block #42140 on Mainnet.  Also check your history plugin action filters to be sure the traffic you are interested in isn't being filtered out.  I assume you are using heavy filters, since full history of Mainnet required more than 1.5 TB of RAM a year ago.

**Comment by heifner** [comment]
@egetekiner any update?

**Comment by ndcgundlach** [comment]
No response for a month.
