### ISSUE TITLE
v2.0.0 Whenever I run cleos, there will be a zombie process left behind

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#8357]
I am using Ubuntu 18.04 LTS and installed v2.0.0 through the .deb in Docker.
I found that everytime after I use cleos command, there will be two defunct process.

root     32763  0.0  0.0      0     0 ?        Z    09:03   0:00 [oc-monitor] <defunct>
root     32764  0.0  0.0      0     0 ?        Z    09:03   0:00 [oc-trampoline] <defunct>

**Comment by jgiszczak** [comment]
Every time or after specific commands?  Those two processes are spawned when nodeos is running with `--wasm-runtime eos-vm` and `--eos-vm-oc-enable` and a contract is being set on an account.

**Comment by shwuhk** [comment]
Every command that I run with cleos, even if I run `cleos get info`.
I am running the node with `wasm-runtime = wabt` without setting any `--eos-vm-oc-enable`

**Comment by jgiszczak** [comment]
And you get a new zombie pair each time, not just one persistent pair of zombie processes?

**Comment by shwuhk** [comment]
Yes, a new pair of zombie processes each time.

**Comment by spoonincode** [comment]
cleos gets linked to libchain. Linking to libchain brings in EOS VM OC's startup magic which forks a couple sandbox processes before `main()`. The design is a bit simple, but those sandbox processes are simply expected to KILL themselves when their parent exits (which is typically nodeos, but also cleos) and let init reap them.

In broken environments that lack a proper init (like a docker container with nodeos as pid 1), there will be nothing to reap these sandbox processes after they've KILLed themselves.

EOS VM OC's sandbox code should be cleaned up such that on a clean exit of nodeos/cleos it reaps these sandbox processes itself instead of letting them KILL themselves on their own and assuming init will clean up.

**Comment by dconry** [comment]
@shwuhk   just a follow up note to the above...  you can specify a `--init` argument to the `docker run` command to run a shim init process that should properly handle zombified procs.

For full details, see official docker run docs under "Specify an init process":

https://docs.docker.com/engine/reference/run/

**Comment by shwuhk** [comment]
Thanks @spoonincode  and @dconry .
You are very helpful! I would try it again with --init command. Thanks!

**Comment by spoonincode** [comment]
I don't believe we should close this. There is an actionable defect with the code: OC's sandbox should be properly cleaned up instead of relying on init to reap the processes. (and really cleos & keosd shouldn't be linking to the entirety of libchain either but that's a whole other design issue)
