### ISSUE TITLE
EOSIO replays transactions more slowly

### ISSUE THREAD

**Issue by weimumu** [EOSIO/eos#8376]
I started the nodeos node based on the block backup data and replayed the transaction, but the transaction replay speed is getting slower and slower. Finally, the nodeos CPU utilization is close to 0. I need all the trace of the all transaction in EOSIO main network。 Using the state-history-plugin is also slow.

**Comment by matthewdarwin** [comment]
Check that you have sufficient RAM on the server.
Also nodeos tends to 'leak' RAM on long replays, so restart nodeos every day or so.

**Comment by matthewdarwin** [comment]
Also, should mention if you are replaying EOS Mainnet, for example, the amount of transactions per block increases quite a lot over time.  You are saying "transaction replay" is slow, so are you measuring the speed of transaction replay or block replay?

Make sure you are using fast local storage (eg SSD).

**Comment by weimumu** [comment]
> Check that you have sufficient RAM on the server.
> Also nodeos tends to 'leak' RAM on long replays, so restart nodeos every day or so.

My server has  120G RAM

**Comment by weimumu** [comment]
> Also, should mention if you are replaying EOS Mainnet, for example, the amount of transactions per block increases quite a lot over time. You are saying "transaction replay" is slow, so are you measuring the speed of transaction replay or block replay?
> 
> Make sure you are using fast local storage (eg SSD).

At the beginning of the replay, the speed was very fast, and the CPU utilization was about 50%. However, at 700W blocks, the speed is slow, and sometimes the CPU utilization is 0.

**Comment by weimumu** [comment]
@matthewdarwin 
Excuse me, are the receipts and traces generated after replaying transactions stored in memory, and will the receipts and traces disappear after a node restart? I want to get receipts and traces of all transactions through cleos get transaction. I started filter-on = * and history plugin

**Comment by jgiszczak** [comment]
You can not use history plugin with `filter-on=*` on EOS Mainnet.  It required more than 1.5TB of RAM over a year ago.  It is far higher today.

History plugin does persist receipts and traces even through a restart, but it uses shared memory to do it, meaning it is limited by system RAM.  Look at your persistent storage I/O rate.  The slow replay rate you are seeing is probably I/O bound, at this point, which is why CPU utilization has dropped so low.

History plugin has been deprecated for some time now.  Strongly consider moving to state history plugin and [history tools](https://github.com/EOSIO/history-tools).
