### ISSUE TITLE
[docs] Add resource requirement for creating an account

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#8549]
Add a how-to on creating an account after the system contract is loaded?

Add resource requirement in `Before you begin` section

**Comment by dixia** [comment]
update issue description. it should be about `cleos system newaccount`

**Comment by iamveritas** [comment]
I am not sure how to go about this, we already educate our users that for creating an account (and doing anything on an EOSIO based network) one has to stake resources to be able to transact or/and store data on the chain.
There's really not an easy way to say how much of each resource is needed, again, we explain that already.
I'd say this issue is "not an issue" or "will not fix" resolution.

**Comment by dixia** [comment]
This issue does not require to describe how much resource is needed that would extend the scope of this issue.

As long as it describes the resource requirement it would already improve the doc as other documentation on system commands have already done

**Comment by dixia** [comment]
Also this is for the new users instead of for people who are already familiar with EOSIO

**Comment by iamveritas** [comment]
The "resource requirement" is described already here: https://developers.eos.io/manuals/eosio.contracts/latest/index/#stake
and yes it is addressing to new users that are getting familiar with EOSIO based blockchain concepts.
