### ISSUE TITLE
Loading dynamic types from db

### ISSUE THREAD

**Issue by sim31** [EOSIO/eos#919]
You can store arbitrary size structures (say with string type fields in it) in the database as values. You just  need to pack those structures properly, so it can be unpacked later. But when trying to load those rows, I encountered a problem of not knowing what buffer size to use for value part of the row. There are ways to find that out, but none of them seem very efficient. 

I think it would make loading structures with dynamic fields much easier and efficient if I could query size of the value before trying to load the whole value.

What do you think about adding this capability to the database api for contracts? Are there any reasons not to implement it? If so, how would you recommend loading dynamic types?

**Comment by wanderingbort** [comment]
in the eos-noon branch we have implemented a number of improvements to this.

passing a buffer tightly sized to the keys (aka 64bits for the i64 table, 256 bits for the i128i128 table etc) sized buffer to any of the database retrieval methods will return `-1` if the record isn't found.  Otherwise it will return the size of the whole record (keys included) without trying to write it to the buffer.  This allows you to determine the size of a record and then appropriately allocate the buffer for a read.   It requires back to back retrievals, but so would any method of size lookup.  

I am going to close this out for now, if you feel this is insufficient please feel free to re-open.
