### ISSUE TITLE
How to best use state_history_plugin

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#9795]
I have been using the mongo plugin, although it has very intuitive problems, such as slow to catch up with the latest block after falling behind. If the synchronization node exits unexpectedly, the data is dirty and needs to be replayed, that is a very sad thing. The relative point is that the mongo plug-in is simple to deploy and easy to view and back-end consumption data. For state_history_plugin, compared with existing open source projects, hyperion-history-api is currently relatively complete, but the data is still not as direct as mongo. Can anyone tell me how the state_history_plugin solution is currently being used? See 2.1.0 mongo plug-in has been clearly deleted.

**Comment by cppfuns** [comment]
@matthewdarwin

**Comment by matthewdarwin** [comment]
There are 2 well-known public solutions that are built on top of state-history-plugin: hyperion and chronicle.  
https://cc32d9.medium.com/eos-chronicle-release-1-0-13b677aac727

Many other non-public solutions also are built on top of state-history-plugin.

This issue seems more like a discussion topic rather than a issue that need investigation in the EOSIO codebase.  Suggest to close this.

**Comment by aclark-b1** [comment]
Thanks @matthewdarwin!
